import ArgumentParser
import Foundation

struct SimResource: AsyncParsableCommand { static let configuration=CommandConfiguration(commandName:"resource",abstract:"Manage simulator resources",subcommands:[SimResourceProfiles.self,SimResourceFeatures.self,SimResourceStatus.self,SimResourceMeasure.self,SimResourceDoctor.self,SimResourcePlan.self,SimResourceApply.self,SimResourceVerify.self,SimResourceRestore.self]) }
func resourceRun(_ req: SimulatorResourceRequest) throws { let r=try CLISimulatorResourceRuntime().execute(req); print(r.stdout) }
struct SimResourceProfiles: AsyncParsableCommand { static let configuration=CommandConfiguration(commandName:"profiles"); func run() async throws { try resourceRun(.init(action:.profiles)) } }
struct SimResourceFeatures: AsyncParsableCommand { static let configuration=CommandConfiguration(commandName:"features"); func run() async throws { try resourceRun(.init(action:.features)) } }
struct SimResourceStatus: AsyncParsableCommand { @Argument var simulator:String; static let configuration=CommandConfiguration(commandName:"status"); func run() async throws { try resourceRun(.init(action:.status,udid:simulator)) } }
struct SimResourceMeasure: AsyncParsableCommand { @Argument var simulator:String; static let configuration=CommandConfiguration(commandName:"measure"); func run() async throws { try resourceRun(.init(action:.measure,udid:simulator)) } }
struct SimResourceDoctor: AsyncParsableCommand { @Argument var simulator:String; @Option var requires:String?; static let configuration=CommandConfiguration(commandName:"doctor"); func run() async throws { try resourceRun(.init(action:.doctor,udid:simulator,requires:requires?.split(separator:",").map(String.init) ?? [])) } }
struct SimResourcePlan: AsyncParsableCommand { @Argument var simulator:String; @Option var profile:String="stock"; static let configuration=CommandConfiguration(commandName:"plan"); func run() async throws { try resourceRun(.init(action:.plan,udid:simulator,profile:profile)) } }
struct SimResourceApply: AsyncParsableCommand { @Argument var simulator:String; @Option var profile:String; @Flag var noReboot=false; static let configuration=CommandConfiguration(commandName:"apply"); func run() async throws { try resourceRun(.init(action:.apply,udid:simulator,profile:profile,noReboot:noReboot)) } }
struct SimResourceVerify: AsyncParsableCommand { @Argument var simulator:String; @Option var profile:String; static let configuration=CommandConfiguration(commandName:"verify"); func run() async throws { try resourceRun(.init(action:.verify,udid:simulator,profile:profile)) } }
struct SimResourceRestore: AsyncParsableCommand { @Argument var receipt:String; static let configuration=CommandConfiguration(commandName:"restore"); func run() async throws { let d=try Data(contentsOf:URL(fileURLWithPath:receipt)); let r=try JSONDecoder().decode(TKSimulatorResourceReceipt.self,from:d); try CLISimulatorResourceRuntime().restore(r) } }
