import Foundation
import TritonKitShared

func actionCommandSchemas() -> [TKCommandSchema] {
    let hostPort = schemaHostPortOptions
    let target = TKCommandSchemaOption(
        name: "--target/--device",
        type: "String",
        defaultValue: TKLocalTargetID,
        description: "Runtime target id from `triton list --json` or a host selector. iOS embedded actions use triton:ios-simulator:<udid> or triton:ios-simulator:<udid>/app:<bundle-id>; a pure coordinate tap with sim:<udid>, a raw Simulator UUID, booted, or current routes directly to host HID without embedded target fallback. --device is an alias."
    )
    let jsonText = schemaTextJSONFormats
    let formatJSONText = schemaFormatJSONTextOption
    let jsonAlias = schemaJSONAliasOption
    let inputCommandFailureCodes = schemaInputCommandFailureCodes
    let runtimeBaseURLOption = schemaRuntimeBaseURLOption
    let semanticActionFailureCodes = schemaSemanticActionFailureCodes
    let webViewTapFailureCodes = [
        "webview_not_found",
        "ambiguous_webview",
        "webview_id_not_found",
        "webview_provider_unavailable",
        "webview_element_not_found",
        "webview_element_not_interactable",
        "webview_navigation_changed",
        "webview_wait_timeout",
        "webview_wait_unsupported",
        "javascript_error",
    ]
    let tapFailureCodes = schemaInputCommandFailureCodes + ["text_not_found", "host_command_failed"] + schemaIOSHostAXFailureCodes + webViewTapFailureCodes
    let actFailureCodes = [
        "text_not_found",
        "validation_failed",
        "unsupported_capability",
        "server_unavailable",
        "target_not_found",
        "ambiguous_target",
        "request_failed",
        "host_command_failed",
        "action_failed",
        "target_unavailable",
        "runtime_unavailable",
        "runtime_ui_interrupted",
        "request_timeout",
        "invalid_payload",
        "semantic_action_failed",
        "action_not_supported",
        "unsupported_runtime_scope",
        "unsupported_scope",
        "target_lease_conflict",
        "geometry_required",
    ] + schemaIOSHostAXFailureCodes + webViewTapFailureCodes

    return [
        TKCommandSchema(
            name: "act",
            summary: "Workflow-level UI action surface for find, tap, type, paste, clear, swipe, press, focus, and form controls",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-ios|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "find", type: "Subcommand", description: "Resolve a UI target by visible text, label, identifier, or option title"),
                TKCommandSchemaOption(name: "tap", type: "Subcommand", description: "Tap a UI target by text, coordinate, oid, or AX node"),
                TKCommandSchemaOption(name: "type", type: "Subcommand", description: "Type text into a focused or oid-targeted input"),
                TKCommandSchemaOption(name: "paste", type: "Subcommand", description: "Paste exact text into a focused, coordinate-targeted, or oid-targeted input"),
                TKCommandSchemaOption(name: "clear", type: "Subcommand", description: "Clear a focused, coordinate-targeted, or oid-targeted input"),
                TKCommandSchemaOption(name: "swipe", type: "Subcommand", description: "Swipe inside the app using window-point coordinates"),
                TKCommandSchemaOption(name: "press", type: "Subcommand", description: "Press a device button when supported"),
                TKCommandSchemaOption(name: "focus", type: "Subcommand", description: "Focus a text input by selector"),
                TKCommandSchemaOption(name: "set-text", type: "Subcommand", description: "Clear and set exact text by selector"),
                TKCommandSchemaOption(name: "select-segment", type: "Subcommand", description: "Select a segmented control segment"),
                TKCommandSchemaOption(name: "set-switch", type: "Subcommand", description: "Set or toggle a switch"),
                TKCommandSchemaOption(name: "input", type: "Subcommand", description: "Run newline-delimited JSON actions from stdin"),
                TKCommandSchemaOption(name: "<query>", type: "String", description: "Visible text, AX label, identifier, value, or option title"),
                TKCommandSchemaOption(name: "<selector>", type: "String", description: "Visible text, AX label, identifier, or placeholder for semantic actions"),
                TKCommandSchemaOption(name: "<text>", type: "String", description: "Text value for type or paste actions"),
                TKCommandSchemaOption(name: "<value>", type: "String|Int", description: "Segment title/index or switch state for semantic actions"),
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Use iOS host AX, Android adb, or Harmony hdc explicitly. Omit --platform for iOS embedded runtime actions; canonical runtime ids stay embedded while pure coordinate taps with an explicit Simulator host selector use host HID."),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "Product-surface alias for text query or input text where supported"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Window coordinate selector"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Runtime view oid"),
                TKCommandSchemaOption(name: "--ax-oid", type: "UInt", description: "AX target/view oid"),
                TKCommandSchemaOption(name: "--ax-label", type: "String", description: "Exact AX label"),
                TKCommandSchemaOption(name: "--strategy", type: "smart|exact|ancestor", description: "Activation strategy for text matches; smart/ancestor can synchronously select UITableViewCell ancestors. UICollectionViewCell fallback returns unsupported_capability unless a nearer public UIControl or accessibility-activatable gesture succeeds"),
                TKCommandSchemaOption(name: "--allow-host-hid-fallback", type: "Bool", defaultValue: "false", description: "Explicit opt-in: after a resolved embedded UICollectionViewCell returns unsupported_capability, submit its validated geometry through the iOS Simulator host-HID adapter; the result remains submission-only and requires postcondition verification"),
                TKCommandSchemaOption(name: "--all", type: "Bool", defaultValue: "false", description: "Include all matching candidates for target resolution"),
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one matching candidate by 1-based index"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict matching to window bounds"),
                TKCommandSchemaOption(name: "--webview-aware", type: "Bool", defaultValue: "false", description: "Explicitly route act tap through the current WebView provider; first slice supports --selector only"),
                TKCommandSchemaOption(name: "--selector", type: "String", description: "CSS selector for --webview-aware WebView tap"),
                TKCommandSchemaOption(name: "--webview-id", type: "String", description: "WebView candidate id for --webview-aware disambiguation"),
                TKCommandSchemaOption(name: "--page-session-id", type: "String", description: "Expected WebView page session id; fails if navigation changed before tap"),
                TKCommandSchemaOption(name: "--expect-text", type: "String", description: "Expected WebView text after --webview-aware dispatch; required to prove business completion"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "3", description: "Timeout in seconds for --expect-text"),
                TKCommandSchemaOption(name: "--lease", type: "String", description: "Target lease token from `triton target lease acquire`; mutating actions fail with target_lease_conflict when another flow holds the lease"),
                TKCommandSchemaOption(name: "--secure", type: "Bool", defaultValue: "false", description: "Redact inserted text details"),
                TKCommandSchemaOption(name: "--exact", type: "Bool", defaultValue: "false", description: "Use exact text insertion when supported"),
                TKCommandSchemaOption(name: "--start-x", type: "Double", description: "Swipe start x coordinate"),
                TKCommandSchemaOption(name: "--start-y", type: "Double", description: "Swipe start y coordinate"),
                TKCommandSchemaOption(name: "--end-x", type: "Double", description: "Swipe end x coordinate"),
                TKCommandSchemaOption(name: "--end-y", type: "Double", description: "Swipe end y coordinate"),
                TKCommandSchemaOption(name: "--width", type: "Double", description: "Optional screen/window width"),
                TKCommandSchemaOption(name: "--height", type: "Double", description: "Optional screen/window height"),
                TKCommandSchemaOption(name: "--duration", type: "Double", description: "Gesture or button duration"),
                TKCommandSchemaOption(name: "--button", type: "String", description: "Compatibility input for device button"),
                TKCommandSchemaOption(name: "--fail-fast", type: "Bool", defaultValue: "false", description: "Stop NDJSON input on first failed action"),
                TKCommandSchemaOption(name: "--summary", type: "Bool", defaultValue: "false", description: "Print a final input batch summary"),
                TKCommandSchemaOption(name: "--strict", type: "Bool", defaultValue: "false", description: "Exit non-zero when any input action fails"),
                formatJSONText,
                jsonAlias,
            ],
            usageForms: [
                TKCommandUsageForm(form: "triton act find <query> --json", kind: "Subcommand", description: "Resolve a target before acting"),
                TKCommandUsageForm(form: "triton act tap --text <text> --json", kind: "Subcommand", description: "Product-language tap entry; positional text remains supported by the underlying tap command"),
                TKCommandUsageForm(form: "triton act tap --device <selector> --at <x,y> --json", kind: "Subcommand", description: "With sim:<udid>, a raw Simulator UUID, booted, or current, submit a pure coordinate tap through host HID without resolving an embedded runtime"),
                TKCommandUsageForm(form: "triton act tap --webview-aware --selector <css> [--webview-id <id>] --expect-text <text> --json", kind: "Subcommand", description: "Dispatch a WebView DOM click and verify expected WebView text"),
                TKCommandUsageForm(form: "triton act type <text> --json", kind: "Subcommand", description: "Type text into the focused field"),
            ],
            examples: [
                "triton act tap --text 登录 --json",
                "triton act tap --device sim:00000000-0000-0000-0000-000000000000 --at 180,420 --json",
                "triton act tap --webview-aware --selector '#submit' --expect-text 成功 --json",
                "triton act type hello --json",
                "triton act find 登录 --json",
            ],
            successShape: "Delegates to the selected action primitive output contract, or WebView-aware tap { ok, action:act.tap, status:passed|failed|uncertain, context:webview, selector, target?, attempts[], verification, recoveryCommand?, sourceCommands[], note }",
            failureShape: "{ ok:false, error:{ code, message, endpoint?, hint, nextAction? } }",
            outputSemantics: "Use act as the workflow-level action surface. For iOS, canonical triton:ios-simulator runtime ids preserve embedded routing. A pure coordinate tap with sim:<udid>, a raw Simulator UUID, booted, or current bypasses embedded /targets resolution and submits through the ready local Simulator host-HID adapter, so a background or stale runtime cannot be selected by same-UDID fallback. Host acknowledgement remains unverified: require observe, wait, verify, screenshot, or evidence before claiming business completion. Retired root action primitives are exposed here as explicit subcommands.",
            nextCommands: [
                "triton observe current --json",
                "triton verify text-exists <text> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [
                targetResolutionOutputContract(),
                inputResultOutputContract(),
                webViewAwareTapOutputContract(),
                inputSummaryOutputContract(),
                hostIOSTapOutputContract(),
                hostAndroidTapOutputContract(),
                hostHarmonyTapOutputContract(),
                hostAndroidSwipeOutputContract(),
                hostHarmonySwipeOutputContract(),
                hostAndroidTextInputOutputContract(),
                hostHarmonyTextInputOutputContract(),
                hostActionOutputContract(selector: "host.android-key-action", model: "HostActionOutput"),
                hostActionOutputContract(selector: "host.harmony-key-action", model: "HostActionOutput"),
                semanticActionOutputContract(),
            ],
            failureCodes: actFailureCodes,
            subcommands: [
                TKCommandSubcommandSchema(name: "find", summary: "Resolve a target before acting", requiredOptions: ["<query>"], optionalOptions: ["--target", "--device", "--host", "--port", "--all", "--index", "--within", "--at", "--format", "--json"], outputSelectors: ["target.resolution"], failureCodes: ["text_not_found", "validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"]),
            TKCommandSubcommandSchema(name: "tap", summary: "Tap a UI target", optionalOptions: ["--target", "--device", "--host", "--port", "--platform", "--adb", "--hdc", "--text", "--x", "--y", "--at", "--oid", "--ax-oid", "--ax-label", "--strategy", "--allow-host-hid-fallback", "--index", "--within", "--webview-aware", "--selector", "--webview-id", "--page-session-id", "--expect-text", "--timeout", "--lease", "--format", "--json"], outputSelectors: ["input.result", "host.ios-tap", "host.android-tap", "host.harmony-tap", "act.webview-aware-tap"], failureCodes: tapFailureCodes + ["target_lease_conflict"]),
                TKCommandSubcommandSchema(name: "type", summary: "Type text into the focused field", optionalOptions: ["--target", "--device", "--host", "--port", "--platform", "--adb", "--hdc", "--text", "--oid", "--secure", "--exact", "--format", "--json"], outputSelectors: ["input.result", "host.android-text-input", "host.harmony-text-input"], failureCodes: inputCommandFailureCodes),
                TKCommandSubcommandSchema(name: "paste", summary: "Paste exact text", requiredOptions: ["<text>"], optionalOptions: ["--target", "--device", "--host", "--port", "--platform", "--adb", "--hdc", "--secure", "--oid", "--x", "--y", "--at", "--format", "--json"], outputSelectors: ["input.result", "host.android-text-input", "host.harmony-text-input"], failureCodes: inputCommandFailureCodes),
                TKCommandSubcommandSchema(name: "clear", summary: "Clear text input", optionalOptions: ["--target", "--device", "--host", "--port", "--platform", "--adb", "--hdc", "--oid", "--x", "--y", "--at", "--format", "--json"], outputSelectors: ["input.result"], failureCodes: inputCommandFailureCodes),
                TKCommandSubcommandSchema(name: "swipe", summary: "Swipe by coordinates; iOS uses an embedded runtime target from `triton list --json`, while Android/Harmony use host coordinates", requiredOptions: ["--start-x", "--start-y", "--end-x", "--end-y"], optionalOptions: ["--target", "--device", "--host", "--port", "--platform", "--adb", "--hdc", "--width", "--height", "--duration", "--format", "--json"], outputSelectors: ["input.result", "host.android-swipe", "host.harmony-swipe"], failureCodes: inputCommandFailureCodes),
                TKCommandSubcommandSchema(name: "press", summary: "Press a device button", optionalOptions: ["--target", "--device", "--host", "--port", "--platform", "--adb", "--hdc", "--button", "--duration", "--format", "--json"], outputSelectors: ["input.result", "host.android-key-action", "host.harmony-key-action"], failureCodes: inputCommandFailureCodes),
                TKCommandSubcommandSchema(name: "focus", summary: "Focus a text input by selector", requiredOptions: ["<selector>"], optionalOptions: ["--target", "--host", "--port", "--runtime-base-url", "--index", "--within", "--at", "--format", "--json"], outputSelectors: ["semantic.action"], failureCodes: semanticActionFailureCodes),
                TKCommandSubcommandSchema(name: "set-text", summary: "Set exact editable text by selector", requiredOptions: ["<selector>", "<text>"], optionalOptions: ["--target", "--host", "--port", "--runtime-base-url", "--secure", "--index", "--within", "--at", "--format", "--json"], outputSelectors: ["semantic.action"], failureCodes: semanticActionFailureCodes),
                TKCommandSubcommandSchema(name: "select-segment", summary: "Select a segmented-control option by title or index", requiredOptions: ["<selector>", "<value>"], optionalOptions: ["--target", "--host", "--port", "--runtime-base-url", "--index", "--within", "--at", "--format", "--json"], outputSelectors: ["semantic.action"], failureCodes: semanticActionFailureCodes),
                TKCommandSubcommandSchema(name: "set-switch", summary: "Set or toggle a switch by selector", requiredOptions: ["<selector>", "<value>"], optionalOptions: ["--target", "--host", "--port", "--runtime-base-url", "--index", "--within", "--at", "--format", "--json"], outputSelectors: ["semantic.action"], failureCodes: semanticActionFailureCodes),
                TKCommandSubcommandSchema(name: "input", summary: "Run newline-delimited JSON actions", optionalOptions: ["--target", "--device", "--host", "--port", "--format", "--json", "--fail-fast", "--summary", "--strict"], outputSelectors: ["input.result", "input.summary"], failureCodes: inputCommandFailureCodes + ["action_failed"]),
            ],
            inputActions: inputActionSchemas(),
            providedCapabilities: ["act", "tap", "webview-aware-tap", "type", "paste", "clear", "swipe", "press", "focus", "set-text", "select-segment", "set-switch", "semantic-action", "input"]
        ),
        TKCommandSchema(
            name: "action",
            summary: "Parse external GUI-agent action provider output into a Triton primitive preview",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "offline",
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "parse", type: "Subcommand", description: "Parse one UI-TARS or AgentCPM-GUI action without executing it"),
                TKCommandSchemaOption(name: "--provider", type: "ui-tars|agentcpm-gui", required: true, description: "Provider output format"),
                TKCommandSchemaOption(name: "--input", type: "String", required: true, description: "Raw provider action output"),
                formatJSONText,
                jsonAlias,
            ],
            usageForms: [
                TKCommandUsageForm(form: "parse --provider ui-tars --input <text> --json", kind: "Subcommand", description: "Parse UI-TARS Thought/Action text into a primitive preview"),
                TKCommandUsageForm(form: "parse --provider agentcpm-gui --input <json> --json", kind: "Subcommand", description: "Parse AgentCPM-GUI JSON action into a primitive preview"),
            ],
            examples: [
                #"triton action parse --provider ui-tars --input "Action: click(start_box='(500,330)')" --json"#,
                #"triton action parse --provider agentcpm-gui --input '{"action":"POINT","point":[500,330]}' --json"#,
            ],
            successShape: "TKActionProviderParseResponse with primitive, coordinateSystem, point/endPoint/text/key/status, and commandPreview",
            failureShape: "{ ok:false, error:{ code:\"action_provider_parse_failed\", message, hint } }",
            outputSemantics: "Offline parser only. It does not execute device actions, does not call a model, and does not start an autonomous loop.",
            nextCommands: [
                "triton test validate <path.tritontest.yaml> --json",
                "triton status --json",
            ],
            outputContracts: [actionProviderParseOutputContract()],
            failureCodes: ["action_provider_parse_failed"],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "parse",
                    summary: "Parse one external action into a Triton primitive preview",
                    requiredOptions: ["--provider", "--input"],
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["action.provider.parse"],
                    failureCodes: ["action_provider_parse_failed"]
                ),
            ],
            providedCapabilities: ["action-provider-parse"]
        ),
        TKCommandSchema(
            name: "tap",
            summary: "Tap a UI target by text, coordinate, view oid, or AX node",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-ios|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Tap by iOS host AX, Android adb input, or Harmony hdc uitest using host layout text or coordinates"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<query>", type: "String", description: "Visible text, AX label, identifier, value, or option title to tap"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "Product-surface alias for the text query; mutually exclusive with <query>"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Coordinate selector without <query>, or query disambiguation point with <query>"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Target view oid"),
                TKCommandSchemaOption(name: "--ax-oid", type: "UInt", description: "AX target/view oid from `triton ax`; taps by runtime oid"),
                TKCommandSchemaOption(name: "--ax-label", type: "String", description: "Exact AX label from `triton ax`; taps by runtime oid"),
                TKCommandSchemaOption(name: "--strategy", type: "smart|exact|ancestor", description: "Choose query or AX text activation target: query defaults to smart; smart/ancestor can synchronously select UITableViewCell ancestors. UICollectionViewCell fallback returns unsupported_capability unless a nearer public UIControl or accessibility-activatable gesture succeeds"),
                TKCommandSchemaOption(name: "--allow-host-hid-fallback", type: "Bool", defaultValue: "false", description: "Explicit opt-in: after a resolved embedded UICollectionViewCell returns unsupported_capability, submit its validated geometry through the iOS Simulator host-HID adapter; the result remains submission-only and requires postcondition verification"),
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one query candidate by 1-based index from `triton find --all`"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict query matching to window bounds"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                #"triton tap "HTTP""#,
                #"triton tap "HTTP" --device booted --json"#,
                #"triton tap "设置" --platform ios --device booted --json"#,
                #"triton tap "我的" --platform harmony --json"#,
                #"triton tap "hello" --index 2"#,
                #"triton tap "hello" --at 240,580"#,
                #"triton tap "hello" --strategy exact"#,
                #"triton tap "hello" --within 180,0,220,500"#,
                "triton tap --at 270,300",
                "triton tap --x 270 --y 300",
                "triton tap --oid 13",
                "triton tap --ax-label Save",
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName, matchedOID?, matchedClassName?, activationOID?, activationClassName?, strategy?, source?, geometry?, verification? } or HostIOSTapOutput or HostAndroidTapOutput or HostHarmonyTapOutput",
            outputSemantics: "Use tap after find when targets are ambiguous. Embedded iOS smart/ancestor activation synchronously selects UITableViewCell ancestors and invokes didSelectRowAt before returning strategy=ancestor-table-cell-selection. UICollectionViewCell fallback reports ok=false, error.code=unsupported_capability, and strategy=ancestor-collection-cell-unsupported without calling selectItem or didSelectItemAt, unless a nearer public UIControl or accessibility-activatable gesture succeeds. `--allow-host-hid-fallback` is explicit opt-in only: after a resolved iOS Simulator collection-cell rejection with finite matched geometry and runtime screen geometry, Triton submits one coordinate tap through the existing host-HID adapter and returns strategy=host-hid-coordinate-tap, source=host-hid, fallbackFromStrategy=ancestor-collection-cell-unsupported, geometry evidence, and verification.required=true. Host submission never claims business completion; follow it with wait/verify and capture evidence. A matched UIAlertController action is a modal boundary: public accessibility activation reports strategy=alert-action-accessibility-activate, while an unavailable safe path returns unsupported_capability with strategy=alert-action-unsupported and never falls through to content behind the alert. UIButton controls with menu and showsMenuAsPrimaryAction use the public iOS 17.4+ performPrimaryAction path and report strategy=button-primary-menu-action; verify a visible menu title or business postcondition before claiming completion. Follow successful taps with wait/assert and capture evidence on failure.",
            nextCommands: [
                "triton status --json",
                "triton wait --text <text> --json",
                "triton verify text-exists <text> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostIOSTapOutputContract(), hostAndroidTapOutputContract(), hostHarmonyTapOutputContract()],
            failureCodes: tapFailureCodes,
            providedCapabilities: ["tap", "ios-simulator-host-tap", "android-tap-text", "harmony-tap-text"]
        ),
        TKCommandSchema(
            name: "swipe",
            summary: "Swipe inside the app using window-point coordinates",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "android|harmony", description: "Swipe by Android adb input or Harmony hdc uitest using screen coordinates"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--start-x", type: "Double", required: true, description: "Start x coordinate in window points"),
                TKCommandSchemaOption(name: "--start-y", type: "Double", required: true, description: "Start y coordinate in window points"),
                TKCommandSchemaOption(name: "--end-x", type: "Double", required: true, description: "End x coordinate in window points"),
                TKCommandSchemaOption(name: "--end-y", type: "Double", required: true, description: "End y coordinate in window points"),
                TKCommandSchemaOption(name: "--width", type: "Double", description: "Optional screen/window width in points"),
                TKCommandSchemaOption(name: "--height", type: "Double", description: "Optional screen/window height in points"),
                TKCommandSchemaOption(name: "--duration", type: "Double", description: "Gesture duration in seconds"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                "triton act swipe --target <ios-runtime-target-from-triton-list> --start-x 350 --start-y 390 --end-x 100 --end-y 390 --json",
                "triton act swipe --platform harmony --target 127.0.0.1:10100 --start-x 350 --start-y 900 --end-x 350 --end-y 300 --json",
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName } or HostAndroidSwipeOutput or HostHarmonySwipeOutput",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostAndroidSwipeOutputContract(), hostHarmonySwipeOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["swipe", "android-swipe", "harmony-swipe"]
        ),
        TKCommandSchema(
            name: "type",
            summary: "Type text into a focused or oid-targeted UIKeyInput",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "android|harmony", description: "Type into the focused Android or Harmony field through host input tools"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<text>", type: "String", description: "Text to insert"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "Compatibility input; mutually exclusive with <text>"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Optional responder oid from `triton nodes`"),
                TKCommandSchemaOption(name: "--secure", type: "Bool", defaultValue: "false", description: "Redact inserted text details in command output"),
                TKCommandSchemaOption(name: "--exact", type: "Bool", defaultValue: "false", description: "Use direct UIKeyInput insertion without keyboard autocorrect"),
                formatJSONText,
                jsonAlias,
            ],
            examples: ["triton type hello --exact", "triton type --text hello", "triton type --platform harmony hello --json"],
            successShape: "{ ok, action, message, targetOID, targetClassName, secure?, redacted?, insertedLength? } or HostAndroidTextInputOutput or HostHarmonyTextInputOutput",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostAndroidTextInputOutputContract(), hostHarmonyTextInputOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["type", "android-type-text", "harmony-type-text"]
        ),
        TKCommandSchema(
            name: "paste",
            summary: "Paste exact text into a focused, coordinate-targeted, or oid-targeted input",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "android|harmony", description: "Insert text into Android or Harmony focused field or coordinate through host input tools"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<text>", type: "String", required: true, description: "Text to paste"),
                TKCommandSchemaOption(name: "--secure", type: "Bool", defaultValue: "false", description: "Redact inserted text details in command output"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Optional responder oid"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate to focus before paste"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate to focus before paste"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Window point to focus before paste"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                #"triton paste "console""#,
                #"triton paste --secure "aa123654""#,
                #"triton paste "console" --at 180,250"#,
                #"triton paste --x 180 --y 250 "console""#,
                #"triton paste --platform harmony --at 180,250 "console" --json"#,
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName, secure, redacted, insertedLength } or HostAndroidTextInputOutput or HostHarmonyTextInputOutput",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostAndroidTextInputOutputContract(), hostHarmonyTextInputOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["paste", "android-paste-text", "harmony-paste-text"]
        ),
        TKCommandSchema(
            name: "clear",
            summary: "Clear a focused, coordinate-targeted, or oid-targeted input",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "android|harmony", description: "Return explicit unsupported until a stable host clear primitive or provider exists"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Optional responder oid"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate to focus before clear"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate to focus before clear"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Window point to focus before clear"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                "triton clear",
                "triton clear --at 180,250",
                "triton clear --x 180 --y 250",
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName, insertedLength: 0 }",
            failureShape: "Harmony host path returns { ok:false, error:{ code:'unsupported_capability', message, hint } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["clear", "harmony-clear-text"]
        ),
        TKCommandSchema(
            name: "press",
            summary: "Press a device button when supported by the active runtime",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "android|harmony", description: "Press Android keycode or Harmony keyEvent through host tools"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<button>", type: "String", description: "Button name, for example home"),
                TKCommandSchemaOption(name: "--button", type: "String", description: "Compatibility input; mutually exclusive with <button>"),
                TKCommandSchemaOption(name: "--duration", type: "Double", description: "Hold duration in seconds"),
                formatJSONText,
                jsonAlias,
            ],
            examples: ["triton press home", "triton press --button home", "triton press back --platform harmony --json"],
            successShape: "{ ok: false, action, message } in embedded runtime; HostActionOutput for Android or Harmony keyEvent",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton schema --command press --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [
                inputResultOutputContract(),
                hostActionOutputContract(selector: "host.android-key-action", model: "HostActionOutput"),
                hostActionOutputContract(selector: "host.harmony-key-action", model: "HostActionOutput"),
            ],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["press", "android-press-key", "harmony-press-key"]
        ),
        TKCommandSchema(
            name: "input",
            summary: "Run newline-delimited JSON actions from stdin",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                TKCommandSchemaOption(name: "--fail-fast", type: "Bool", defaultValue: "false", description: "Stop on first failed action"),
                TKCommandSchemaOption(name: "--summary", type: "Bool", defaultValue: "false", description: "Print a final JSON batch summary"),
                TKCommandSchemaOption(name: "--strict", type: "Bool", defaultValue: "false", description: "Exit non-zero when any action fails"),
            ],
            examples: [
                #"printf '%s\n' '{"type":"tap","x":270,"y":300}' '{"type":"type","text":"hello"}' | triton input --format json --summary --strict"#,
            ],
            successShape: "One TKInputResult JSON object per input line; with --summary, final { ok, actionCount, failedCount }",
            outputSemantics: "Use input for batched low-level actions. Prefer --summary --strict when an agent needs a single completion gate for a batch.",
            nextCommands: [
                "triton status --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton wait --text <text> --json",
                "triton verify text-exists <text> --json",
            ],
            outputContracts: [inputResultOutputContract(), inputSummaryOutputContract()],
            failureCodes: inputCommandFailureCodes + ["action_failed"],
            inputActions: inputActionSchemas(),
            providedCapabilities: ["input", "tap", "swipe", "type", "paste", "clear"]
        ),
    ]
}
