import Foundation
import TritonKitShared

func xcodeCommandSchemas() -> [TKCommandSchema] {
    let jsonText = schemaTextJSONFormats
    let jsonAlias = schemaJSONAliasOption

    return [
        TKCommandSchema(
            name: "xcode",
            summary: "Discover, configure, build, test, and run Xcode projects without exposing XcodeBuildMCP APIs",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-xcode",
            exitCodeOnFailure: 1,
            outputFormats: jsonText + ["jsonl"],
            options: [
                TKCommandSchemaOption(name: "discover --path <path>", type: "Subcommand", description: "Discover .xcworkspace, .xcodeproj, and Package.swift candidates"),
                TKCommandSchemaOption(name: "use --workspace <path>|--project <path> --scheme <scheme>", type: "Subcommand", description: "Set repo-local Xcode defaults in .triton/host-defaults.json"),
                TKCommandSchemaOption(name: "schemes", type: "Subcommand", description: "List schemes via xcodebuild -list -json"),
                TKCommandSchemaOption(name: "status", type: "Subcommand", description: "Inspect active xcodebuild and build-service processes"),
                TKCommandSchemaOption(name: "wait-idle", type: "Subcommand", description: "Wait until matching Xcode build/test processes are idle"),
                TKCommandSchemaOption(name: "settings", type: "Subcommand", description: "Resolve app product path and bundle id from -showBuildSettings -json"),
                TKCommandSchemaOption(name: "build", type: "Subcommand", description: "Run xcodebuild build"),
                TKCommandSchemaOption(name: "test", type: "Subcommand", description: "Run xcodebuild test"),
                TKCommandSchemaOption(name: "run", type: "Subcommand", description: "Run build, simulator install, and simulator launch"),
                TKCommandSchemaOption(name: "--path", type: "Path", defaultValue: ".", description: "Directory to scan for Xcode workspace, project, or Package.swift candidates"),
                TKCommandSchemaOption(name: "--workspace", type: "Path", description: "Path to .xcworkspace"),
                TKCommandSchemaOption(name: "--project", type: "Path", description: "Path to .xcodeproj"),
                TKCommandSchemaOption(name: "--scheme", type: "String", description: "Xcode scheme"),
                TKCommandSchemaOption(name: "--configuration", type: "String", defaultValue: "Debug", description: "Build configuration"),
                TKCommandSchemaOption(name: "--sdk", type: "String", defaultValue: "iphonesimulator", description: "xcodebuild SDK"),
                TKCommandSchemaOption(name: "--destination", type: "String", description: "xcodebuild destination"),
                TKCommandSchemaOption(name: "--simulator", type: "String", description: "Simulator UDID; also used to synthesize destination"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Real-device selector from `triton device`; real-device builds use sdk=iphoneos and a device destination"),
                TKCommandSchemaOption(name: "--derived-data-path", type: "Path", defaultValue: ".triton/DerivedData", description: "Repo-local DerivedData path used as the Xcode incremental build cache; cleanup should preserve it by default"),
                TKCommandSchemaOption(name: "--allow-provisioning-updates", type: "Bool", defaultValue: "false", description: "Pass -allowProvisioningUpdates to xcodebuild for automatic signing on real devices"),
                TKCommandSchemaOption(name: "--result-bundle", type: "Path", description: "Result bundle path for test"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", description: "Command timeout in seconds for large workspaces"),
                TKCommandSchemaOption(name: "--jsonl", type: "Bool", defaultValue: "false", description: "Emit JSON Lines progress for long commands"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton xcode discover --path . --json",
                "triton xcode use --workspace App.xcworkspace --scheme App --configuration Debug --simulator 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --json",
                "triton xcode schemes --json",
                "triton xcode status --json",
                "triton xcode wait-idle --workspace App.xcworkspace --timeout 120 --json",
                "triton xcode settings --json",
                "triton xcode build --jsonl",
                "triton xcode build --device <ios-real-target> --sdk iphoneos --allow-provisioning-updates --jsonl",
                "triton xcode test --result-bundle /tmp/App.xcresult --jsonl",
                "triton xcode run --jsonl",
                "triton xcode run --device <ios-real-target> --sdk iphoneos --jsonl",
            ],
            successShape: "discover/use/schemes/status/wait-idle/settings JSON envelopes or JSONL progress plus final TKXcodeActionSummary",
            failureShape: "{ ok:false, error:{ code: invalid_workspace_path|ambiguous_workspace|scheme_not_found|simulator_not_found|device_not_ready|device_not_trusted|developer_mode_required|ddi_missing|xcode_signing_failed|provisioning_profile_missing|xcode_not_idle|xcodebuild_failed|app_path_unresolved|bundle_id_unresolved, message, hint, nextAction?{ command,args,category,requiresLongRunningProcess?,readyEvents,finalEvents,terminationSignals } } }",
            inheritsDefaultsFrom: ["triton xcode use", "triton sim use"],
            jsonlEvents: [
                "xcode.<action>.invocation",
                "xcode.<action>.stdout",
                "xcode.<action>.stderr",
                "xcode.<action>.heartbeat",
                "xcode.<action>.summary",
            ],
            finalEventKind: "xcode.<action>.summary",
            artifacts: ["stdout-log", "stderr-log", "result-bundle"],
            retryable: true,
            nextCommands: [
                "triton xcresult summary --path <result.xcresult> --json",
                "triton xcresult failures --path <result.xcresult> --json",
                "triton status --json",
                "triton assert text-exists <text> --json",
            ],
            outputContracts: [
                TKCommandOutputContract(
                    selector: "xcode.progress",
                    format: "jsonl",
                    kind: "progress-event",
                    model: "TKXcodeProgressEvent",
                    fields: schemaFields([
                        ("ok", "Bool", true, "Whether the progress event is valid"),
                        ("event", "String", true, "Progress event kind"),
                        ("message", "String", true, "Human-readable progress message"),
                        ("sourceCommand", "String?", false, "Underlying host command"),
                        ("elapsedMs", "Int?", false, "Elapsed milliseconds"),
                        ("stdoutLogPath", "String?", false, "Stdout artifact path"),
                        ("stderrLogPath", "String?", false, "Stderr artifact path"),
                        ("stdoutBytes", "Int?", false, "Total stdout bytes"),
                        ("stderrBytes", "Int?", false, "Total stderr bytes"),
                    ])
                ),
                TKCommandOutputContract(
                    selector: "xcode.final",
                    format: "jsonl",
                    kind: "final-event",
                    model: "TKXcodeActionSummary",
                    fields: schemaFields([
                        ("ok", "Bool", true, "Whether the action completed"),
                        ("action", "String", true, "xcode.build, xcode.test, or xcode.run"),
                        ("failureCode", "String?", false, "Stable failure code such as xcodebuild_failed when ok=false"),
                        ("workspace", "String?", false, "Workspace path"),
                        ("project", "String?", false, "Project path"),
                        ("scheme", "String", true, "Scheme name"),
                        ("configuration", "String", true, "Build configuration"),
                        ("sdk", "String?", false, "SDK"),
                        ("destination", "String?", false, "xcodebuild destination"),
                        ("device", "String?", false, "Real-device selector when sdk=iphoneos"),
                        ("derivedDataPath", "String?", false, "DerivedData path"),
                        ("derivedDataCache", "TKXcodeDerivedDataCacheInfo?", false, "DerivedData cache metadata for incremental build expectations and cleanup policy"),
                        ("derivedDataCache.path", "String", false, "Resolved DerivedData path used by xcodebuild"),
                        ("derivedDataCache.exists", "Bool", false, "Whether the DerivedData directory exists before the action"),
                        ("derivedDataCache.cacheState", "String", false, "DerivedData cache state, for example empty or warm"),
                        ("derivedDataCache.incrementalExpected", "Bool", false, "Whether incremental Xcode build reuse is expected"),
                        ("derivedDataCache.cleanupPolicy", "String", false, "Cleanup policy; preserve-by-default means Triton should not delete the cache automatically"),
                        ("derivedDataCache.guidance", "String", false, "Human-readable guidance for preserving or intentionally resetting the cache"),
                        ("appPath", "String?", false, "Built app path"),
                        ("bundleID", "String?", false, "Resolved bundle id"),
                        ("resultBundlePath", "String?", false, "Result bundle path"),
                        ("simulatorUDID", "String?", false, "Simulator UDID"),
                        ("durationMs", "Int", true, "Duration in milliseconds"),
                        ("sourceCommand", "String", true, "Underlying host command"),
                        ("exitCode", "Int32", true, "Host process exit code"),
                        ("stdoutTruncated", "Bool", true, "Whether stdout sample was truncated"),
                        ("stderrTruncated", "Bool", true, "Whether stderr sample was truncated"),
                        ("stdoutLogPath", "String?", false, "Stdout artifact path"),
                        ("stderrLogPath", "String?", false, "Stderr artifact path"),
                        ("stdoutBytes", "Int?", false, "Total stdout bytes"),
                        ("stderrBytes", "Int?", false, "Total stderr bytes"),
                        ("testResultSummary", "TKXcresultSummaryMetrics?", false, "Inline parsed xcresult test counts for xcode.test when --result-bundle is available"),
                        ("topFailures", "[TKXcresultFailureRecord]?", false, "Default-redacted top test failures for xcode.test"),
                        ("xcresultNote", "String?", false, "Inline xcresult parsing note"),
                        ("xcodeDiagnostics", "[TKXcodeOutputDiagnostic]?", false, "Structured diagnostics parsed from xcodebuild stdout/stderr, including stale DerivedData outside-root recovery"),
                        ("note", "String?", false, "Boundary or next-step note"),
                    ])
                ),
            ],
            failureCodes: [
                "invalid_workspace_path",
                "ambiguous_workspace",
                "scheme_not_found",
                "simulator_not_found",
                "device_not_ready",
                "device_not_trusted",
                "developer_mode_required",
                "ddi_missing",
                "xcode_signing_failed",
                "provisioning_profile_missing",
                "xcode_not_idle",
                "xcodebuild_failed",
                "app_path_unresolved",
                "bundle_id_unresolved",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "discover",
                    summary: "Discover Xcode workspaces, projects, and packages",
                    optionalOptions: ["--path"],
                    retryable: true,
                    nextCommands: ["triton xcode use --workspace <workspace> --scheme <scheme> --json"],
                    failureCodes: ["invalid_workspace_path"]
                ),
                TKCommandSubcommandSchema(
                    name: "use",
                    summary: "Persist repo-local Xcode defaults",
                    requiredOptions: ["--scheme"],
                    oneOfRequiredOptions: [["--workspace"], ["--project"]],
                    optionalOptions: ["--configuration", "--simulator"],
                    defaultProviders: ["triton sim use"],
                    inheritsDefaultsFrom: ["triton sim use"],
                    retryable: true,
                    nextCommands: ["triton xcode schemes --json", "triton xcode settings --jsonl"],
                    failureCodes: ["invalid_workspace_path", "ambiguous_workspace", "scheme_not_found", "simulator_not_found"]
                ),
                TKCommandSubcommandSchema(
                    name: "schemes",
                    summary: "List shared Xcode schemes",
                    optionalOptions: ["--workspace", "--project"],
                    defaultProviders: ["triton xcode use"],
                    inheritsDefaultsFrom: ["triton xcode use"],
                    retryable: true,
                    nextCommands: ["triton xcode use --workspace <workspace> --scheme <scheme> --json"],
                    failureCodes: ["invalid_workspace_path", "ambiguous_workspace", "xcodebuild_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "status",
                    summary: "Inspect active xcodebuild and build-service processes",
                    optionalOptions: ["--workspace"],
                    retryable: true,
                    nextCommands: ["triton xcode wait-idle --workspace <workspace> --timeout 120 --json"]
                ),
                TKCommandSubcommandSchema(
                    name: "wait-idle",
                    summary: "Wait until matching Xcode build processes are idle",
                    optionalOptions: ["--workspace", "--timeout"],
                    retryable: true,
                    nextCommands: ["triton xcode status --json"],
                    failureCodes: ["xcode_not_idle"]
                ),
                TKCommandSubcommandSchema(
                    name: "settings",
                    summary: "Resolve build settings, app path, and bundle id",
                    optionalOptions: ["--workspace", "--project", "--scheme", "--configuration", "--sdk", "--destination", "--simulator", "--device", "--derived-data-path", "--timeout"],
                    defaultProviders: ["triton xcode use", "triton sim use"],
                    inheritsDefaultsFrom: ["triton xcode use", "triton sim use"],
                    jsonlEvents: [
                        "xcode.settings.invocation",
                        "xcode.settings.stdout",
                        "xcode.settings.stderr",
                        "xcode.settings.heartbeat",
                        "xcode.settings.summary",
                    ],
                    finalEventKind: "xcode.settings.summary",
                    artifacts: ["stdout-log", "stderr-log"],
                    retryable: true,
                    nextCommands: ["triton xcode build --jsonl", "triton xcode run --jsonl"],
                    outputSelectors: ["xcode.progress", "xcode.final"],
                    failureCodes: ["invalid_workspace_path", "ambiguous_workspace", "scheme_not_found", "simulator_not_found", "device_not_ready", "device_not_trusted", "developer_mode_required", "ddi_missing", "xcode_signing_failed", "provisioning_profile_missing", "xcodebuild_failed", "app_path_unresolved", "bundle_id_unresolved"]
                ),
                TKCommandSubcommandSchema(
                    name: "build",
                    summary: "Run xcodebuild build and emit bounded JSONL progress",
                    optionalOptions: ["--workspace", "--project", "--scheme", "--configuration", "--sdk", "--destination", "--simulator", "--device", "--derived-data-path", "--timeout", "--jsonl"],
                    defaultProviders: ["triton xcode use", "triton sim use"],
                    inheritsDefaultsFrom: ["triton xcode use", "triton sim use"],
                    jsonlEvents: [
                        "xcode.build.invocation",
                        "xcode.build.stdout",
                        "xcode.build.stderr",
                        "xcode.build.heartbeat",
                        "xcode.build.summary",
                    ],
                    finalEventKind: "xcode.build.summary",
                    artifacts: ["stdout-log", "stderr-log"],
                    retryable: true,
                    nextCommands: ["triton xcode run --jsonl", "triton status --json"],
                    outputSelectors: ["xcode.progress", "xcode.final"],
                    failureCodes: ["invalid_workspace_path", "ambiguous_workspace", "scheme_not_found", "simulator_not_found", "device_not_ready", "device_not_trusted", "developer_mode_required", "ddi_missing", "xcode_signing_failed", "provisioning_profile_missing", "xcodebuild_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "test",
                    summary: "Run xcodebuild test and optionally write a result bundle",
                    optionalOptions: ["--workspace", "--project", "--scheme", "--configuration", "--sdk", "--destination", "--simulator", "--device", "--derived-data-path", "--result-bundle", "--timeout", "--jsonl"],
                    defaultProviders: ["triton xcode use", "triton sim use"],
                    inheritsDefaultsFrom: ["triton xcode use", "triton sim use"],
                    jsonlEvents: [
                        "xcode.test.invocation",
                        "xcode.test.stdout",
                        "xcode.test.stderr",
                        "xcode.test.heartbeat",
                        "xcode.test.summary",
                    ],
                    finalEventKind: "xcode.test.summary",
                    artifacts: ["stdout-log", "stderr-log", "result-bundle"],
                    retryable: true,
                    nextCommands: [
                        "triton xcresult summary --path <result.xcresult> --json",
                        "triton xcresult failures --path <result.xcresult> --json",
                    ],
                    outputSelectors: ["xcode.progress", "xcode.final"],
                    failureCodes: ["invalid_workspace_path", "ambiguous_workspace", "scheme_not_found", "simulator_not_found", "device_not_ready", "device_not_trusted", "developer_mode_required", "ddi_missing", "xcode_signing_failed", "provisioning_profile_missing", "xcodebuild_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "run",
                    summary: "Build, install, and launch on a selected simulator or real device without claiming business readiness",
                    optionalOptions: ["--workspace", "--project", "--scheme", "--configuration", "--sdk", "--destination", "--simulator", "--device", "--derived-data-path", "--timeout", "--jsonl"],
                    defaultProviders: ["triton xcode use", "triton sim use"],
                    inheritsDefaultsFrom: ["triton xcode use", "triton sim use"],
                    jsonlEvents: [
                        "xcode.run.invocation",
                        "xcode.run.stdout",
                        "xcode.run.stderr",
                        "xcode.run.heartbeat",
                        "xcode.run.summary",
                    ],
                    finalEventKind: "xcode.run.summary",
                    artifacts: ["stdout-log", "stderr-log"],
                    retryable: true,
                    nextCommands: ["triton status --json", "triton wait --json", "triton assert text-exists <text> --json"],
                    outputSelectors: ["xcode.progress", "xcode.final"],
                    failureCodes: ["invalid_workspace_path", "ambiguous_workspace", "scheme_not_found", "simulator_not_found", "device_not_ready", "device_not_trusted", "developer_mode_required", "ddi_missing", "xcode_signing_failed", "provisioning_profile_missing", "xcodebuild_failed", "app_path_unresolved", "bundle_id_unresolved"]
                ),
            ],
            providedCapabilities: ["xcode-discovery", "xcode-defaults", "xcode-diagnostics", "xcodebuild", "xcode-run"]
        ),
        TKCommandSchema(
            name: "xcresult",
            summary: "Inspect Xcode result bundles for summary counts and structured failures",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-xcode",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "summary", type: "Subcommand", description: "Read test counts and environment summary from an .xcresult bundle"),
                TKCommandSchemaOption(name: "failures", type: "Subcommand", description: "Read structured failing test cases from an .xcresult bundle"),
                TKCommandSchemaOption(name: "--path", type: "Path", description: "Input .xcresult bundle path"),
                TKCommandSchemaOption(name: "--include-sensitive", type: "Bool", defaultValue: "false", description: "Include private paths, emails, and token-like values in output"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton xcresult summary --path /tmp/App.xcresult --json",
                "triton xcresult failures --path /tmp/App.xcresult --json",
            ],
            successShape: "{ ok, action, path, summary, sourceCommand, redaction } or { ok, action, path, summary, failures[], sourceCommands[], redaction }",
            failureShape: "{ ok:false, error:{ code: result_bundle_not_found|xcresulttool_failed|xcresult_parse_failed|xcresult_output_too_large|host_command_failed, message, hint } }",
            artifacts: ["none-inline-summary"],
            retryable: true,
            nextCommands: ["triton evidence --output <dir.tritonevidence> --json"],
            outputContracts: [
                TKCommandOutputContract(
                    selector: "xcresult.summary",
                    format: "json",
                    kind: "envelope",
                    model: "HostXcresultSummaryOutput",
                    fields: schemaFields([
                        ("ok", "Bool", true, "Whether parsing succeeded"),
                        ("action", "String", true, "xcresult.summary"),
                        ("path", "String", true, "Result bundle path, redacted by default"),
                        ("summary", "TKXcresultSummaryMetrics", true, "Parsed summary metrics"),
                        ("sourceCommand", "String", true, "Underlying xcresulttool command, redacted by default"),
                        ("redaction", "String", true, "Redaction status"),
                        ("note", "String?", false, "Suggested next command"),
                    ])
                ),
                TKCommandOutputContract(
                    selector: "xcresult.failures",
                    format: "json",
                    kind: "envelope",
                    model: "HostXcresultFailuresOutput",
                    fields: schemaFields([
                        ("ok", "Bool", true, "Whether parsing succeeded"),
                        ("action", "String", true, "xcresult.failures"),
                        ("path", "String", true, "Result bundle path, redacted by default"),
                        ("summary", "TKXcresultSummaryMetrics", true, "Parsed summary metrics"),
                        ("failures", "[TKXcresultFailureRecord]", true, "Structured failure records"),
                        ("sourceCommands", "[String]", true, "Underlying xcresulttool commands, redacted by default"),
                        ("redaction", "String", true, "Redaction status"),
                        ("note", "String?", false, "Empty-failure note"),
                    ])
                ),
            ],
            failureCodes: [
                "result_bundle_not_found",
                "xcresulttool_failed",
                "xcresult_parse_failed",
                "xcresult_output_too_large",
                "host_command_failed",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "summary",
                    summary: "Read test counts and environment summary from an .xcresult bundle",
                    requiredOptions: ["--path"],
                    optionalOptions: ["--include-sensitive"],
                    retryable: true,
                    nextCommands: ["triton xcresult failures --path <result.xcresult> --json"],
                    outputSelectors: ["xcresult.summary"],
                    failureCodes: ["result_bundle_not_found", "xcresulttool_failed", "xcresult_parse_failed", "xcresult_output_too_large", "host_command_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "failures",
                    summary: "Read structured failing test cases from an .xcresult bundle",
                    requiredOptions: ["--path"],
                    optionalOptions: ["--include-sensitive"],
                    retryable: true,
                    nextCommands: ["triton evidence --output <dir.tritonevidence> --json"],
                    outputSelectors: ["xcresult.failures"],
                    failureCodes: ["result_bundle_not_found", "xcresulttool_failed", "xcresult_parse_failed", "xcresult_output_too_large", "host_command_failed"]
                ),
            ],
            providedCapabilities: ["xcresult-summary", "xcresult-failures"]
        ),
        TKCommandSchema(
            name: "xctrace",
            summary: "Record Instruments traces as bounded host artifacts",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-xcode",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "record --template <name> --output <path.trace>", type: "Subcommand", description: "Record an Instruments .trace artifact"),
                TKCommandSchemaOption(name: "--template", type: "String", description: "Instruments template name, for example Time Profiler"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Trace artifact output path"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Simulator/device UDID or name"),
                TKCommandSchemaOption(name: "--time-limit", type: "String", description: "Recording time limit, for example 5s, 500ms, 1m"),
                TKCommandSchemaOption(name: "--all-processes", type: "Bool", defaultValue: "false", description: "Record all processes; default when no attach or launch command is supplied"),
                TKCommandSchemaOption(name: "--attach", type: "String", description: "Attach to process name or pid"),
                TKCommandSchemaOption(name: "--launch", type: "Bool", defaultValue: "false", description: "Launch a command under Instruments"),
                TKCommandSchemaOption(name: "--append-run", type: "Bool", defaultValue: "false", description: "Append a run to an existing trace"),
                TKCommandSchemaOption(name: "--run-name", type: "String", description: "Run label"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", description: "Host command timeout in seconds"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton xctrace record --template 'Time Profiler' --device 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --time-limit 5s --output /tmp/App.trace --json",
            ],
            successShape: "{ ok, action, runtimeScope, target, tool, exitCode, sourceCommand, artifacts[], stdout?, stderr?, note? }",
            failureShape: "{ ok:false, error:{ code: artifact_output_rejected|xctrace_record_failed|host_command_failed, message, hint } }",
            artifacts: ["trace"],
            retryable: true,
            nextCommands: ["triton evidence --output <dir.tritonevidence> --json"],
            outputContracts: [
                TKCommandOutputContract(
                    selector: "xctrace.record",
                    format: "json",
                    kind: "artifact-envelope",
                    model: "HostActionOutput",
                    fields: schemaFields([
                        ("ok", "Bool", true, "Whether recording completed"),
                        ("action", "String", true, "xctrace.record"),
                        ("runtimeScope", "String", true, "host-xcode"),
                        ("target", "String", true, "Recording target"),
                        ("tool", "String", true, "Host executable"),
                        ("exitCode", "Int32", true, "Host process exit code"),
                        ("riskLevel", "String", true, "Host risk level"),
                        ("sourceCommand", "String", true, "Underlying xctrace command"),
                        ("stdoutTruncated", "Bool", true, "Whether stdout was truncated"),
                        ("stderrTruncated", "Bool", true, "Whether stderr was truncated"),
                        ("stdout", "String?", false, "Bounded stdout sample"),
                        ("stderr", "String?", false, "Bounded stderr sample"),
                        ("artifacts", "[String]", true, "Trace artifact paths"),
                        ("note", "String?", false, "Completion note"),
                    ])
                ),
            ],
            failureCodes: ["artifact_output_rejected", "xctrace_record_failed", "host_command_failed"],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "record",
                    summary: "Record an Instruments trace artifact",
                    requiredOptions: ["--template", "--output"],
                    optionalOptions: ["--device", "--time-limit", "--all-processes", "--attach", "--launch", "--append-run", "--run-name", "--timeout"],
                    artifacts: ["trace"],
                    retryable: true,
                    nextCommands: ["triton evidence --output <dir.tritonevidence> --json"],
                    outputSelectors: ["xctrace.record"],
                    failureCodes: ["artifact_output_rejected", "xctrace_record_failed", "host_command_failed"]
                ),
            ],
            providedCapabilities: ["xctrace-record"]
        ),
        TKCommandSchema(
            name: "coverage",
            summary: "Extract Xcode coverage reports from .xcresult bundles into artifacts",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-xcode",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "report --xcresult <path> --output <path.json>", type: "Subcommand", description: "Write xccov report JSON from an .xcresult bundle"),
                TKCommandSchemaOption(name: "--xcresult", type: "Path", description: ".xcresult bundle path"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Coverage JSON artifact output path"),
                TKCommandSchemaOption(name: "--only-targets", type: "Bool", defaultValue: "false", description: "Only list coverage targets"),
                TKCommandSchemaOption(name: "--target", type: "String", description: "List files for a target"),
                TKCommandSchemaOption(name: "--file", type: "String", description: "List functions for a file name or path"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", description: "Host command timeout in seconds"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton coverage report --xcresult /tmp/App.xcresult --output /tmp/coverage.json --json",
                "triton coverage report --xcresult /tmp/App.xcresult --only-targets --output /tmp/coverage-targets.json --json",
            ],
            successShape: "{ ok, action, artifact, stdoutBytes, stderrBytes, stdoutTruncated, stderrTruncated, sourceCommand, note? }",
            failureShape: "{ ok:false, error:{ code: validation_failed|artifact_output_rejected|coverage_report_failed|host_command_failed, message, hint } }",
            artifacts: ["coverage-json"],
            retryable: true,
            nextCommands: ["triton evidence --output <dir.tritonevidence> --json"],
            outputContracts: [
                TKCommandOutputContract(
                    selector: "coverage.report",
                    format: "json",
                    kind: "artifact-envelope",
                    model: "HostArtifactCaptureOutput",
                    fields: schemaFields([
                        ("ok", "Bool", true, "Whether export completed"),
                        ("action", "String", true, "coverage.report"),
                        ("runtimeScope", "String", true, "host-xcode"),
                        ("target", "String", true, "xcresult target"),
                        ("tool", "String", true, "Host executable"),
                        ("exitCode", "Int32", true, "Host process exit code"),
                        ("riskLevel", "String", true, "Host risk level"),
                        ("sourceCommand", "String", true, "Underlying xccov command"),
                        ("artifact", "String", true, "Coverage JSON path"),
                        ("stdoutBytes", "Int", true, "Written stdout bytes"),
                        ("stderrBytes", "Int", true, "Captured stderr bytes"),
                        ("stdoutTruncated", "Bool", true, "Whether stdout was truncated"),
                        ("stderrTruncated", "Bool", true, "Whether stderr was truncated"),
                        ("stderr", "String?", false, "Bounded stderr sample"),
                        ("note", "String?", false, "Completion note"),
                    ])
                ),
            ],
            failureCodes: [
                "validation_failed",
                "artifact_output_rejected",
                "coverage_report_failed",
                "host_command_failed",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "report",
                    summary: "Export xccov report JSON into an artifact",
                    requiredOptions: ["--xcresult", "--output"],
                    optionalOptions: ["--only-targets", "--target", "--file", "--timeout"],
                    artifacts: ["coverage-json"],
                    retryable: true,
                    nextCommands: ["triton evidence --output <dir.tritonevidence> --json"],
                    outputSelectors: ["coverage.report"],
                    failureCodes: ["validation_failed", "artifact_output_rejected", "coverage_report_failed", "host_command_failed"]
                ),
            ],
            providedCapabilities: ["coverage-report"]
        ),
    ]
}
