import Foundation
import TritonKitShared

func hostCommandSchemas() -> [TKCommandSchema] {
    let jsonText = schemaTextJSONFormats
    let jsonAlias = schemaJSONAliasOption

    return [
        TKCommandSchema(
            name: "device",
            summary: "Discover and inspect host-side platform devices",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-device",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "doctor --platform ios|android|harmony", type: "Subcommand", description: "Probe platform host tool availability"),
                TKCommandSchemaOption(name: "list --platform ios|android|harmony", type: "Subcommand", description: "List iOS Simulator, Android Emulator, or Harmony HDC targets with the same envelope"),
                TKCommandSchemaOption(name: "alias list", type: "Subcommand", description: "List stable host target aliases from .triton/host-targets.json"),
                TKCommandSchemaOption(name: "alias set <name> --platform ios|android|harmony --target <id>", type: "Subcommand", description: "Map a stable alias to an iOS UDID, Android adb serial, or Harmony HDC target"),
                TKCommandSchemaOption(name: "alias remove <name>", type: "Subcommand", description: "Remove a stable host target alias"),
                TKCommandSchemaOption(name: "use <selector>", type: "Subcommand", description: "Resolve a target selector and save it as the current agent target"),
                TKCommandSchemaOption(name: "current", type: "Subcommand", description: "Show the current agent target"),
                TKCommandSchemaOption(name: "resolve <selector>", type: "Subcommand", description: "Resolve a target selector without executing an action"),
                TKCommandSchemaOption(name: "wait-ready --device <selector>", type: "Subcommand", description: "Wait for iOS Booted or Harmony bootevent.boot.completed"),
                TKCommandSchemaOption(name: "screenshot --device <selector> --output <path>", type: "Subcommand", description: "Capture a host-side iOS or Harmony screenshot artifact"),
                TKCommandSchemaOption(name: "runtime-url --device <selector>", type: "Subcommand", description: "Prepare HDC fport and print a direct Harmony embedded runtime base URL"),
                TKCommandSchemaOption(name: "runtime-url --platform harmony --target <target>", type: "Subcommand", description: "Compatibility path for preparing a direct Harmony embedded runtime base URL"),
                TKCommandSchemaOption(name: "stop --platform harmony --hvd <name> --path <deployed-path> --confirm", type: "Subcommand", description: "Unload Triton launchd supervision and stop a Harmony HVD"),
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", defaultValue: "harmony", description: "Host device platform adapter"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified target selector: alias, sim:<udid>, android:<serial>, harmony:<target>, raw id, booted, or current"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Device name filter, for example iPhone 15"),
                TKCommandSchemaOption(name: "--runtime", type: "String", description: "Runtime filter, for example iOS 26.5"),
                TKCommandSchemaOption(name: "--state", type: "String", description: "Target state filter, for example booted or connected"),
                TKCommandSchemaOption(name: "--ready", type: "Bool", defaultValue: "false", description: "Only match ready host targets"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path"),
                TKCommandSchemaOption(name: "--target", type: "String", description: "Compatibility target option: simulator UDID or Harmony target, for example 127.0.0.1:10100"),
                TKCommandSchemaOption(name: "--hvd", type: "String", description: "Harmony HVD name for device stop"),
                TKCommandSchemaOption(name: "--path", type: "Path", description: "DevEco deployed emulator path for device stop"),
                TKCommandSchemaOption(name: "--emulator", type: "Path", defaultValue: "/Applications/DevEco-Studio.app/Contents/tools/emulator/Emulator", description: "DevEco Emulator executable for device stop"),
                TKCommandSchemaOption(name: "--launchd-label", type: "String", defaultValue: "triton-harmony-emulator", description: "Triton launchd job label to unload before Harmony stop"),
                TKCommandSchemaOption(name: "--launchd-domain", type: "String", defaultValue: "gui/<uid>", description: "launchd domain for the Triton Harmony emulator job"),
                TKCommandSchemaOption(name: "--skip-launchd", type: "Bool", defaultValue: "false", description: "Only run Emulator -stop without launchd print/bootout"),
                TKCommandSchemaOption(name: "--confirm", type: "Bool", defaultValue: "false", description: "Required for Harmony device stop"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Screenshot output path for device screenshot"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "30", description: "Bounded wait timeout in seconds"),
                TKCommandSchemaOption(name: "--local-port", type: "Int", defaultValue: String(TKHarmonyRuntimeDefaults.hostAccessPort), description: "Local TCP port used in the generated base URL"),
                TKCommandSchemaOption(name: "--remote-port", type: "Int", defaultValue: String(TKHarmonyRuntimeDefaults.hostAccessPort), description: "Remote TCP port where the Harmony embedded runtime host-access server listens"),
                TKCommandSchemaOption(name: "--no-forward", type: "Bool", defaultValue: "false", description: "Skip HDC fport setup and only print the local URL"),
                TKCommandSchemaOption(name: "--probe-manifest", type: "Bool", defaultValue: "false", description: "Probe /v2/runtime/manifest after preparing the URL"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton device doctor --platform ios --json",
                "triton device list --platform ios --json",
                "triton device alias set iphone15 --platform ios --target 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --json",
                "triton device use iphone15 --json",
                "triton device current --json",
                "triton device resolve --platform ios --name 'iPhone 15' --ready --json",
                "triton device wait-ready --device iphone15 --json",
                "triton device screenshot --device iphone15 --output /tmp/sim.png --json",
                "triton device doctor --platform android --json",
                "triton device list --platform android --json",
                "triton device alias set android-a --platform android --target emulator-5554 --json",
                "triton device wait-ready --device android-a --json",
                "triton device screenshot --device android-a --output /tmp/android.png --json",
                "triton device doctor --platform harmony --json",
                "triton device list --platform harmony --json",
                "triton device alias set harmony-a --platform harmony --target 127.0.0.1:10100 --json",
                "triton device wait-ready --device harmony-a --json",
                "triton device screenshot --device harmony-a --output /tmp/smoke.jpeg --json",
                "triton device runtime-url --device harmony-a --probe-manifest --json",
                "triton device runtime-url --platform harmony --target 127.0.0.1:10100 --probe-manifest --json",
                "triton device stop --platform harmony --hvd 'Codex Test Phone' --path ~/.Huawei/Emulator/deployed --confirm --json",
            ],
            successShape: "{ ok, platform, tools[]?, targets[]?, defaultTarget?, target?, defaultsPath?, ready?, artifact?, baseURL?, manifest?, hvd?, launchdLabel?, launchdDomain?, sourceCommand?, sourceCommands?[] }",
            failureShape: "{ ok:false, error:{ code: ambiguous_target|target_offline|device_not_ready|host_action_failed, message, hint } }",
            outputSemantics: "Use device as the host target fact source before simulator, Harmony, app, screenshot, or smoke actions. Prefer aliases and current target to avoid repeated disambiguation.",
            nextCommands: [
                "triton device resolve --device <selector> --json",
                "triton device use <selector> --json",
                "triton device wait-ready --device <selector> --json",
                "triton app launch --device <selector> --json",
            ],
            outputContracts: [
                hostDeviceListOutputContract(),
                hostDeviceSelectionOutputContract(),
                hostDeviceReadyOutputContract(),
                hostArtifactOutputContract(),
                runtimeManifestOutputContract(),
            ],
            failureCodes: [
                "ambiguous_target",
                "target_not_found",
                "target_offline",
                "target_platform_mismatch",
                "parameter_conflict",
                "device_not_ready",
                "host_command_timeout",
                "host_action_failed",
                "android_adb_not_found",
                "android_target_offline",
                "android_target_unauthorized",
                "android_screenshot_failed",
                "harmony_screenshot_failed",
                "validation_failed",
            ],
            providedCapabilities: ["host-device", "host-device-selector", "device-alias", "device-list", "device-use", "device-current", "device-resolve", "device-wait-ready", "device-screenshot", "ios-device", "android-device", "android-device-doctor", "android-device-list", "android-device-wait-ready", "android-device-screenshot", "harmony-device", "harmony-runtime-url", "harmony-device-stop"]
        ),
        TKCommandSchema(
            name: "sim",
            summary: "Control simulators through host-side Apple tools",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-simulator",
            exitCodeOnFailure: 1,
            outputFormats: jsonText + ["jsonl"],
            options: [
                TKCommandSchemaOption(name: "list", type: "Subcommand", description: "List available simulators"),
                TKCommandSchemaOption(name: "use <udid>", type: "Subcommand", description: "Set workspace default simulator in .triton/host-defaults.json"),
                TKCommandSchemaOption(name: "boot <udid>", type: "Subcommand", description: "Boot a simulator"),
                TKCommandSchemaOption(name: "--wait", type: "Bool", defaultValue: "false", description: "Wait until booted"),
                TKCommandSchemaOption(name: "--jsonl", type: "Bool", defaultValue: "false", description: "Emit JSON Lines progress with --wait"),
                TKCommandSchemaOption(name: "shutdown <udid|booted>", type: "Subcommand", description: "Shutdown a simulator"),
                TKCommandSchemaOption(name: "screenshot --output <path>", type: "Subcommand", description: "Capture simulator framebuffer screenshot"),
                TKCommandSchemaOption(name: "record --output <path.mov> --duration <seconds>", type: "Subcommand", description: "Record a simulator video"),
                TKCommandSchemaOption(name: "logs --output <path.log> --duration <seconds>", type: "Subcommand", description: "Capture bounded simulator OSLog stream output"),
                TKCommandSchemaOption(name: "diagnose [--output <path>]", type: "Subcommand", description: "Collect simulator diagnostics and logs"),
                TKCommandSchemaOption(name: "logverbose [--simulator <udid>] enable|disable", type: "Subcommand", description: "Enable or disable verbose simulator logging"),
                TKCommandSchemaOption(name: "pair <watch-device> <phone-device>", type: "Subcommand", description: "Create a watch and phone simulator pair"),
                TKCommandSchemaOption(name: "unpair <pair-uuid>", type: "Subcommand", description: "Unpair a watch and phone simulator pair"),
                TKCommandSchemaOption(name: "clone <device> <new-name> [destination-device-set]", type: "Subcommand", description: "Clone an existing simulator device"),
                TKCommandSchemaOption(name: "erase <device> --confirm", type: "Subcommand", description: "Erase simulator contents and settings with an explicit break-glass acknowledgement"),
                TKCommandSchemaOption(name: "upgrade <device> <runtime-id>", type: "Subcommand", description: "Upgrade a simulator to a newer runtime"),
                TKCommandSchemaOption(name: "runtime list|verify|add|delete|unmount|scan-and-mount", type: "Subcommand", description: "Inspect and maintain installed simulator runtimes"),
                TKCommandSchemaOption(name: "runtime match list|set", type: "Subcommand", description: "Read or override SDK-to-runtime build matching"),
                TKCommandSchemaOption(name: "runtime dyld-cache update|remove", type: "Subcommand", description: "Update or remove runtime dyld shared caches"),
                TKCommandSchemaOption(name: "personalization personalize|remove-manifest|remove-all-manifests|remove-personalization|revoke-manifests|scan-and-personalize", type: "Subcommand", description: "Manage simulator runtime personalization manifests"),
                TKCommandSchemaOption(name: "status-bar list", type: "Subcommand", description: "List simulator status bar overrides"),
                TKCommandSchemaOption(name: "status-bar clear", type: "Subcommand", description: "Clear simulator status bar overrides"),
                TKCommandSchemaOption(name: "status-bar override --time <value>", type: "Subcommand", description: "Set simulator status bar override values"),
                TKCommandSchemaOption(name: "privacy grant <service> <bundle-id>", type: "Subcommand", description: "Grant a simulator privacy permission"),
                TKCommandSchemaOption(name: "privacy revoke <service> <bundle-id>", type: "Subcommand", description: "Revoke a simulator privacy permission"),
                TKCommandSchemaOption(name: "privacy reset <service> [bundle-id]", type: "Subcommand", description: "Reset simulator privacy permissions"),
                TKCommandSchemaOption(name: "location list", type: "Subcommand", description: "List available simulated location scenarios"),
                TKCommandSchemaOption(name: "location clear", type: "Subcommand", description: "Clear simulated location"),
                TKCommandSchemaOption(name: "location set <lat>,<lon>", type: "Subcommand", description: "Set a simulated location coordinate"),
                TKCommandSchemaOption(name: "location run <scenario>", type: "Subcommand", description: "Run a simulated location scenario"),
                TKCommandSchemaOption(name: "location start <waypoints...>", type: "Subcommand", description: "Run a waypoint-based simulated route"),
                TKCommandSchemaOption(name: "ui appearance [light|dark]", type: "Subcommand", description: "Get or set the simulator appearance style"),
                TKCommandSchemaOption(name: "ui increase-contrast [enabled|disabled]", type: "Subcommand", description: "Get or set Increase Contrast"),
                TKCommandSchemaOption(name: "ui content-size [value]", type: "Subcommand", description: "Get or set the preferred content size category"),
                TKCommandSchemaOption(name: "pasteboard set <text>", type: "Subcommand", description: "Copy text onto the simulator pasteboard"),
                TKCommandSchemaOption(name: "pasteboard get", type: "Subcommand", description: "Read simulator pasteboard content"),
                TKCommandSchemaOption(name: "pasteboard sync <source> <destination>", type: "Subcommand", description: "Sync pasteboard content between host and simulator"),
                TKCommandSchemaOption(name: "push --bundle-id <id> --payload <path|->", type: "Subcommand", description: "Send a simulated push notification"),
                TKCommandSchemaOption(name: "--simulator", type: "String", defaultValue: "booted", description: "Simulator UDID or booted target selector"),
                TKCommandSchemaOption(name: "--display", type: "String", description: "CoreSimulator display selector for screenshot or video, for example internal, external, screen id, or display UUID"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Artifact output path for screenshot, record, logs, or diagnose"),
                TKCommandSchemaOption(name: "--duration", type: "Double", description: "Bounded record or log capture duration in seconds"),
                TKCommandSchemaOption(name: "--style", type: "String", description: "Log output style, for example compact or ndjson"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "Bundle identifier for push payload delivery"),
                TKCommandSchemaOption(name: "--payload", type: "Path|-", description: "Push payload JSON file path or stdin"),
                TKCommandSchemaOption(name: "--confirm", type: "Bool", defaultValue: "false", description: "Required for destructive simulator operations such as erase"),
                TKCommandSchemaOption(name: "--dry-run", type: "Bool", defaultValue: "false", description: "Plan destructive runtime maintenance without executing it"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton sim list --json",
                "triton sim use 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --json",
                "triton sim boot 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --json",
                "triton sim boot 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --wait --jsonl",
                "triton sim screenshot --simulator booted --output /tmp/sim.png --json",
                "triton sim record --simulator booted --output /tmp/sim.mov --duration 10 --json",
                "triton sim logs --simulator booted --output /tmp/sim.ndjson --duration 5 --style ndjson --json",
                "triton sim diagnose --output /tmp/sim-diagnostics --json",
                "triton sim logverbose booted enable --json",
                "triton sim runtime list --json",
                "triton sim pair <watch-udid> <phone-udid> --json",
                "triton sim clone <udid> 'Clone for Smoke' --json",
                "triton sim erase <udid> --confirm --json",
                "triton sim runtime delete <runtime-id> --dry-run --json",
                "triton sim personalization scan-and-personalize --json",
            ],
            successShape: "{ ok, simulators[] } or { ok, runtimes[], count, verbose, sourceCommand } or { ok, action, simulator?, defaultsPath? } or { ok, action:sim.screenshot, artifact, pixelWidth?, pixelHeight?, display, orientationPolicy, orientationNote } or { ok, action, runtimeScope, target, tool, exitCode, sourceCommand, stdout?, stderr?, stdoutTruncated?, stderrTruncated?, artifacts[], note? } or { ok, action, artifact, stdoutBytes, stderrBytes, stdoutTruncated, stderrTruncated } or JSONL { ok, action, state, ready, attempt, elapsedMs }",
            failureShape: "{ ok:false, error:{ code, message, hint, nextAction? } }",
            outputSemantics: "Use sim for Apple Simulator host control and maintenance. Destructive operations require explicit confirm flags; agents should resolve/use a simulator before app or smoke flows. sim screenshot preserves simctl raw framebuffer orientation and returns screenshot metadata so agents do not assume display-normalized orientation.",
            artifacts: ["simulator-screenshot", "simulator-video", "simulator-logs", "simulator-diagnostics"],
            nextCommands: [
                "triton sim use <udid> --json",
                "triton device use <sim-target-id> --json",
                "triton evidence --output <dir.tritonevidence> --json",
                "triton app launch --device <selector> --bundle-id <id> --json",
                "triton smoke ios --device <selector> --bundle-id <id> --open-url <url> --wait-text <text> --json",
            ],
            outputContracts: [
                hostSimulatorListOutputContract(),
                hostSimulatorScreenshotOutputContract(),
                hostActionOutputContract(selector: "host.simulator-action", model: "HostActionOutput|HostArtifactCaptureOutput|HostSimulatorUseOutput|HostSimulatorReadyEvent"),
                hostSimulatorScreenshotMetadataOutputContract(),
            ],
            failureCodes: [
                "simulator_not_found",
                "host_command_failed",
                "host_command_timeout",
                "artifact_output_rejected",
                "sim_device_maintenance_failed",
                "status_bar_operation_failed",
                "privacy_operation_failed",
                "location_operation_failed",
                "ui_operation_failed",
                "pasteboard_operation_failed",
                "push_payload_invalid",
                "sim_pair_failed",
                "sim_unpair_failed",
                "sim_clone_failed",
                "sim_erase_failed",
                "sim_upgrade_failed",
                "sim_record_failed",
                "sim_logs_failed",
                "sim_diagnose_failed",
                "sim_logverbose_failed",
                "sim_runtime_failed",
                "sim_personalization_failed",
                "runtime_list_failed",
                "runtime_verify_failed",
                "runtime_add_failed",
                "runtime_delete_failed",
                "runtime_unmount_failed",
                "runtime_scan_and_mount_failed",
                "runtime_match_failed",
                "runtime_dyld_cache_failed",
                "confirmation_required",
                "invalid_duration",
                "invalid_location_value",
                "runtime_delete_selector_required",
                "runtime_dyld_cache_selector_required",
                "runtime_match_selector_required",
                "validation_failed",
            ],
            providedCapabilities: ["host-simulator", "sim-video", "sim-logs", "sim-diagnostics", "sim-runtime", "sim-runtime-maintenance", "sim-device-maintenance", "sim-personalization", "sim-status-bar", "sim-privacy", "sim-location", "sim-ui", "sim-pasteboard", "sim-push"]
        ),
        TKCommandSchema(
            name: "app",
            summary: "Control local simulator and emulator apps through host-side tools",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-simulator|host-android|host-harmony",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "list", type: "Subcommand", description: "List installed simulator apps"),
                TKCommandSchemaOption(name: "info --bundle-id <id>", type: "Subcommand", description: "Show installed app metadata"),
                TKCommandSchemaOption(name: "inspect --platform harmony --bundle <bundle>", type: "Subcommand", description: "Inspect a Harmony app with bm dump"),
                TKCommandSchemaOption(name: "install --app <path.app>", type: "Subcommand", description: "Install an .app bundle into the simulator"),
                TKCommandSchemaOption(name: "install --platform android --apk <path.apk>", type: "Subcommand", description: "Install an Android APK through adb install -r"),
                TKCommandSchemaOption(name: "install --platform harmony --hap <path.hap>", type: "Subcommand", description: "Install a Harmony HAP through hdc install -r"),
                TKCommandSchemaOption(name: "uninstall --bundle-id <id> --confirm", type: "Subcommand", description: "Uninstall an app from the simulator"),
                TKCommandSchemaOption(name: "uninstall --platform android --package-name <package> --confirm", type: "Subcommand", description: "Uninstall an Android package through adb uninstall"),
                TKCommandSchemaOption(name: "launch --bundle-id <id>", type: "Subcommand", description: "Launch an installed simulator app"),
                TKCommandSchemaOption(name: "launch --platform android --package-name <package>", type: "Subcommand", description: "Launch an Android package; when --activity is omitted Triton resolves the default activity before adb am start"),
                TKCommandSchemaOption(name: "launch --platform harmony --bundle <bundle> --ability <ability>", type: "Subcommand", description: "Launch a Harmony app ability"),
                TKCommandSchemaOption(name: "terminate --bundle-id <id>", type: "Subcommand", description: "Terminate a running simulator app"),
                TKCommandSchemaOption(name: "terminate --platform android --package-name <package>", type: "Subcommand", description: "Force-stop an Android package through adb shell am force-stop"),
                TKCommandSchemaOption(name: "terminate --platform harmony --bundle <bundle>", type: "Subcommand", description: "Force-stop a Harmony app"),
                TKCommandSchemaOption(name: "go <url>", type: "Subcommand", description: "Open an iOS URL, wait for embedded runtime readiness, and return a snapshot summary"),
                TKCommandSchemaOption(name: "open-url <url>", type: "Subcommand", description: "Submit a URL to the simulator"),
                TKCommandSchemaOption(name: "open-url --platform android <url>", type: "Subcommand", description: "Submit an Android VIEW intent through adb shell am start"),
                TKCommandSchemaOption(name: "open-url <url> --wait-ready --snapshot", type: "Subcommand", description: "Open a URL, wait for embedded runtime readiness, and return an app/route/AX snapshot summary"),
                TKCommandSchemaOption(name: "open-url --platform harmony --bundle <bundle> --ability <ability> <url>", type: "Subcommand", description: "Open a Harmony deep link through aa start -U"),
                TKCommandSchemaOption(name: "container --bundle-id <id>", type: "Subcommand", description: "Print app container path"),
                TKCommandSchemaOption(name: "prefs dump --bundle-id <id>", type: "Subcommand", description: "Dump app preferences plist as JSON"),
                TKCommandSchemaOption(name: "prefs get <key> --bundle-id <id>", type: "Subcommand", description: "Read one app preference"),
                TKCommandSchemaOption(name: "prefs set <key> <json-value> --bundle-id <id>", type: "Subcommand", description: "Set one simulator app preference from a property-list compatible JSON value"),
                TKCommandSchemaOption(name: "prefs set <key> --type data --base64 <base64> --bundle-id <id>", type: "Subcommand", description: "Set one simulator app preference as plist Data from base64"),
                TKCommandSchemaOption(name: "prefs set <key> --type data --hex <hex> --bundle-id <id>", type: "Subcommand", description: "Set one simulator app preference as plist Data from defaults-style hex bytes"),
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Host app platform filter; when omitted, install/launch/terminate/open-url infer the platform from the provided app identifiers"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector: alias, sim:<udid>, android:<serial>, harmony:<target>, raw id, booted, or current"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "iOS app bundle identifier for info, uninstall, launch, terminate, container, and preferences"),
                TKCommandSchemaOption(name: "--package-name", type: "String", description: "Android package name for install, launch, terminate, and open-url"),
                TKCommandSchemaOption(name: "--activity", type: "String", description: "Android activity name for explicit component launch"),
                TKCommandSchemaOption(name: "--bundle", type: "String", description: "Harmony bundle name for inspect, launch, terminate, and open-url"),
                TKCommandSchemaOption(name: "--ability", type: "String", description: "Harmony ability name for launch and open-url"),
                TKCommandSchemaOption(name: "--app", type: "Path", description: "Path to iOS .app bundle for install"),
                TKCommandSchemaOption(name: "--apk", type: "Path", description: "Path to Android .apk package for install"),
                TKCommandSchemaOption(name: "--hap", type: "Path", description: "Path to Harmony .hap package for install"),
                TKCommandSchemaOption(name: "--user-only", type: "Bool", defaultValue: "false", description: "List only user-installed simulator apps"),
                TKCommandSchemaOption(name: "--confirm", type: "Bool", defaultValue: "false", description: "Required for destructive app operations such as uninstall"),
                TKCommandSchemaOption(name: "--kind", type: "String", defaultValue: "data", description: "Container kind to resolve, for example app, data, groups, or all"),
                TKCommandSchemaOption(name: "--type", type: "json|data", defaultValue: "json", description: "Preference set value type; data requires exactly one of --base64 or --hex"),
                TKCommandSchemaOption(name: "--base64", type: "String", description: "Base64 payload for prefs set --type data"),
                TKCommandSchemaOption(name: "--hex", type: "String", description: "Hex payload for prefs set --type data; optional 0x prefix and whitespace are accepted"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Device name filter, for example iPhone 15"),
                TKCommandSchemaOption(name: "--runtime", type: "String", description: "Runtime filter, for example iOS 26.5"),
                TKCommandSchemaOption(name: "--state", type: "String", description: "Target state filter, for example booted or connected"),
                TKCommandSchemaOption(name: "--ready", type: "Bool", defaultValue: "false", description: "Only match ready host targets"),
                TKCommandSchemaOption(name: "--simulator", type: "String", description: "Explicit iOS simulator selector; cannot be combined with --device"),
                TKCommandSchemaOption(name: "--runtime-target", type: "String", defaultValue: TKLocalTargetID, description: "iOS embedded runtime target for open-url readiness/snapshot verification"),
                TKCommandSchemaOption(name: "--wait-ready", type: "Bool", defaultValue: "false", description: "After open-url, wait until embedded runtime is connected with active hierarchy"),
                TKCommandSchemaOption(name: "--snapshot", type: "Bool", defaultValue: "false", description: "After open-url, return embedded runtime app/scene/route/AX/geometry snapshot summary"),
                TKCommandSchemaOption(name: "--snapshot-include", type: "String", defaultValue: "app,scene,route,ax,geometry", description: "Comma-separated snapshot sections"),
                TKCommandSchemaOption(name: "--max-ax-nodes", type: "Int", description: "Maximum AX nodes in the runtime snapshot"),
                TKCommandSchemaOption(name: "--host", type: "String", defaultValue: "127.0.0.1", description: "Triton server host for readiness/snapshot verification"),
                TKCommandSchemaOption(name: "--port", type: "Int", defaultValue: "19421", description: "Triton server port for readiness/snapshot verification"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "20", description: "Runtime readiness timeout in seconds"),
                TKCommandSchemaOption(name: "--interval", type: "Double", defaultValue: "0.5", description: "Runtime readiness polling interval in seconds"),
                TKCommandSchemaOption(name: "--target", type: "String", description: "Compatibility Harmony target selector, for example 127.0.0.1:10100; cannot be combined with --device"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton app list --device iphone15 --user-only --json",
                "triton app info --device iphone15 --bundle-id com.example.app --json",
                "triton app inspect --platform harmony --bundle com.example.app --json",
                "triton app install --device iphone15 --app /tmp/Demo.app --json",
                "triton app install --device android-a --platform android --apk /tmp/Demo.apk --json",
                "triton app install --device harmony-a --hap /tmp/Demo.hap --json",
                "triton app uninstall --device iphone15 --bundle-id com.example.app --confirm --json",
                "triton app uninstall --device android-a --platform android --package-name com.example.app --confirm --json",
                "triton app launch --device iphone15 --bundle-id com.example.app --json",
                "triton app launch --platform ios --name 'iPhone 15' --bundle-id com.example.app --json",
                "triton app launch --bundle-id com.example.app --json",
                "triton app launch --device android-a --platform android --package-name com.example.app --json",
                "triton app launch --device harmony-a --bundle com.example.app --ability EntryAbility --json",
                "triton app launch --platform harmony --bundle com.example.app --ability EntryAbility --json",
                "triton app open-url example://debug --device android-a --platform android --package-name com.example.app --json",
                "triton app open-url --device harmony-a --bundle com.example.app --ability EntryAbility example://debug --json",
                "triton app terminate --device iphone15 --bundle-id com.example.app --json",
                "triton app terminate --device android-a --platform android --package-name com.example.app --json",
                #"triton app go "example://debug""#,
                #"triton app go "example://debug" --device iphone15"#,
                #"triton app open-url "example://debug" --device iphone15 --json"#,
                #"triton app open-url "example://debug" --device iphone15 --wait-ready --snapshot --json"#,
                "triton app container --device iphone15 --bundle-id com.example.app --kind data --json",
                "triton app prefs get DEBUG-mock --device iphone15 --bundle-id com.example.app --json",
                #"triton app prefs set DEBUG-mock true --device iphone15 --bundle-id com.example.app --json"#,
                #"triton app prefs set SeedState --type data --base64 W3t9XQ== --device iphone15 --bundle-id com.example.app --json"#,
            ],
            successShape: "{ ok, action, simulatorUDID?, apps[]?, app?, bundleID?, path?, target?, sourceCommand? } or { ok, action, plistPath, value?, valuePlistType?, preferences?, preferencesPlistTypes? } or { ok, action:app.prefs.set, plistPath, key, previousValue?, previousPlistType?, newValue, newPlistType, restartAdvice } or enhanced open-url { ok, status, hostAction, ready?, snapshot? }",
            failureShape: "{ ok:false, error:{ code, message, hint, nextAction? } }",
            outputSemantics: "Use app for host-side install, launch, terminate, open-url, container, and preferences across iOS Simulator, Android Emulator, and Harmony Emulator. For iOS runtime readiness, prefer open-url with --wait-ready --snapshot; for Android host flows, verify business completion with wait/observe/screenshot or smoke evidence.",
            artifacts: ["app-container", "app-preferences", "runtime-snapshot"],
            nextCommands: [
                "triton app go <url>",
                "triton status --json",
                "triton assert text-exists <text> --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [
                hostActionOutputContract(selector: "host.app-action", model: "HostActionOutput|HostAppContainerOutput|HostAppPreferenceOutput"),
                hostAppOpenURLOutputContract(),
            ],
            failureCodes: [
                "ambiguous_target",
                "target_not_found",
                "target_offline",
                "target_platform_mismatch",
                "parameter_conflict",
                "simulator_not_found",
                "app_info_not_available",
                "app_container_not_found",
                "app_install_failed",
                "app_launch_failed",
                "app_terminate_failed",
                "host_open_url_failed",
                "host_command_timeout",
                "host_action_failed",
                "missing_preferences",
                "plist_not_found",
                "preference_key_not_found",
                "destructive_action_requires_policy",
                "validation_failed",
            ],
            providedCapabilities: ["host-app", "host-app-open-url-ready", "host-app-open-url-snapshot", "host-preferences", "android-app", "android-app-install", "android-app-launch", "android-app-terminate", "android-app-open-url", "harmony-app", "harmony-app-install", "harmony-app-open-url"]
        ),
    ]
}
