import Foundation
import TritonKitShared

func testCommandSchemas() -> [TKCommandSchema] {
    [
        TKCommandSchema(
            name: "test",
            summary: "Import, validate, normalize, and execute deterministic .tritontest.yaml contracts",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "offline for import/validate/normalize/report/create; runtime target required for run",
            exitCodeOnFailure: 1,
            outputFormats: ["json", "text"],
            options: [
                TKCommandSchemaOption(name: "validate <path.tritontest.yaml>", type: "Subcommand", description: "Validate a .tritontest.yaml file"),
                TKCommandSchemaOption(name: "normalize <path.tritontest.yaml>", type: "Subcommand", description: "Validate and emit only the normalized plan"),
                TKCommandSchemaOption(name: "run <path.tritontest.yaml>", type: "Subcommand", description: "Run deterministic executor primitives after validate/normalize and capture screen workspace readiness observations"),
                TKCommandSchemaOption(name: "report <dir.tritonevidence>", type: "Subcommand", description: "Project an existing .tritonevidence test run into a JSON report"),
                TKCommandSchemaOption(name: "create --from-session <dir.tritonevidence> --output <path.tritontest.yaml>", type: "Subcommand", description: "Project existing evidence into an editable .tritontest.yaml draft"),
                TKCommandSchemaOption(name: "import <case.tritontestcase> --output <path.tritontest.yaml> --bundle-id <bundle-id> --device-platform ios-simulator", type: "Subcommand", description: "Read an existing compiled testrec contract, fail closed on unmappable semantics, and write a validated iOS Simulator test plan"),
                TKCommandSchemaOption(name: "--evidence-dir", type: "Path", description: "Required for run; output .tritonevidence directory"),
                TKCommandSchemaOption(name: "--target", type: "String", defaultValue: TKLocalTargetID, description: "Runtime target id for run"),
                TKCommandSchemaOption(name: "--host", type: "String", defaultValue: "127.0.0.1", description: "Triton HTTP host for run"),
                TKCommandSchemaOption(name: "--port", type: "Int", defaultValue: "19421", description: "Triton HTTP port for run"),
                TKCommandSchemaOption(name: "--allow-vlm", type: "Bool", defaultValue: "false", description: "Allow experimental VLM-assisted tap(target) steps"),
                TKCommandSchemaOption(name: "--allow-remote-vlm", type: "Bool", defaultValue: "false", description: "Allow remote VLM provider calls for VLM-assisted steps"),
                TKCommandSchemaOption(name: "--vlm-base-url", type: "String", description: "OpenAI-compatible VLM base URL for VLM-assisted steps"),
                TKCommandSchemaOption(name: "--vlm-model", type: "String", description: "OpenAI-compatible VLM model for VLM-assisted steps"),
                TKCommandSchemaOption(name: "--vlm-api-key-env", type: "String", description: "Environment variable containing VLM API key"),
                TKCommandSchemaOption(name: "--from-session", type: "Path", description: "Required for create; input .tritonevidence directory or manifest.json path"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Required for create/import; output .tritontest.yaml file and import refuses overwrite"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Optional create name override"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "Required for import because .tritontestcase v1 stores no app bundle identity"),
                TKCommandSchemaOption(name: "--device-platform", type: "String", description: "Required for import; P0 only accepts ios-simulator so source ios is not silently relabeled"),
                TKCommandSchemaOption(name: "--expect-compiled-digest", type: "String", description: "Optional expected fnv1a64 digest for import source compiled-contract.json"),
                TKCommandSchemaOption(name: "--emit-normalized-plan", type: "Bool", defaultValue: "false", description: "Emit only normalizedPlan for validate when validation succeeds"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                schemaJSONAliasOption,
            ],
            usageForms: [
                TKCommandUsageForm(form: "validate <path.tritontest.yaml> --json", kind: "Subcommand", description: "Validate and emit { ok, normalizedPlan }"),
                TKCommandUsageForm(form: "validate <path.tritontest.yaml> --emit-normalized-plan --json", kind: "Subcommand", description: "Validate and emit only triton.test.normalized-plan JSON"),
                TKCommandUsageForm(form: "normalize <path.tritontest.yaml> --json", kind: "Subcommand", description: "Alias for validate --emit-normalized-plan"),
                TKCommandUsageForm(form: "run <path.tritontest.yaml> --json --evidence-dir <dir>", kind: "Subcommand", description: "Validate, execute deterministic primitives and optional VLM-assisted tap(target), and write .tritonevidence/run/events.jsonl plus observation.captured/vlm.grounding events"),
                TKCommandUsageForm(form: "report <dir.tritonevidence> --json", kind: "Subcommand", description: "Read manifest.json and run/events.jsonl, then aggregate steps, screenshots, overlays, observations, and failure type"),
                TKCommandUsageForm(form: "create --from-session <dir.tritonevidence> --output <path.tritontest.yaml> --json", kind: "Subcommand", description: "Read normalized-plan.json from an evidence bundle, write an editable .tritontest.yaml draft, and validate it offline"),
                TKCommandUsageForm(form: "import <case.tritontestcase> --output <path.tritontest.yaml> --bundle-id <bundle-id> --device-platform ios-simulator --json", kind: "Subcommand", description: "Read only manifest/capabilities/compiled-contract, map the proven safe action subset, validate in memory, then atomically write a plan"),
            ],
            argumentForms: [
                TKCommandArgumentForm(name: "<path.tritontest.yaml>", type: "Path", required: true, description: "Input .tritontest.yaml contract file"),
                TKCommandArgumentForm(name: "<dir.tritonevidence>", type: "Path", required: true, description: "Existing .tritonevidence bundle directory or manifest.json path"),
                TKCommandArgumentForm(name: "<case.tritontestcase>", type: "Path", required: true, description: "Existing compiled testrec package used by import"),
            ],
            examples: [
                "triton test validate login.tritontest.yaml --json",
                "triton test validate login.tritontest.yaml --emit-normalized-plan --json",
                "triton test normalize login.tritontest.yaml --json",
                "triton test run login.tritontest.yaml --json --evidence-dir ./login.tritonevidence",
                "triton test run vlm-login.tritontest.yaml --json --evidence-dir ./vlm-login.tritonevidence --allow-vlm",
                "triton test report ./login.tritonevidence --json",
                "triton test create --from-session ./login.tritonevidence --output ./generated-login.tritontest.yaml --json",
                "triton test import ./login.tritontestcase --output ./imported-login.tritontest.yaml --bundle-id com.example.app --device-platform ios-simulator --json",
            ],
            successShape: "import emits TKTestImportResponse after reading an existing compiled testrec contract, validating the generated plan in memory, and atomically writing it; validate emits TKTestValidationResponse; normalize emits TKTestNormalizedPlan; run emits TKTestRunExecutionResponse with normalizedPlan, run metadata, event summary, observationCount, and evidenceDir; report emits TKTestReportResponse from existing .tritonevidence; create emits TKTestCreateResponse after writing and validating an editable .tritontest.yaml draft.",
            failureShape: "{ ok:false, error:{ type:\"validation_error\", message, path, code, allowed? } }",
            outputSemantics: "Import is offline-only: it reads manifest.json, contract-capabilities.json, and an already-existing compiled-contract.json; it never recompiles raw streams, resolves a target, starts a server/app, executes an action, or creates evidence. P0 import requires an explicit bundle id and ios-simulator device platform; it accepts only ios/ios-simulator source contracts, rejects truncation, unresolved quality findings, source identity drift, unsupported capabilities, overwrite, and every action outside tap(text), assert(text), or screenshot. It adds a synthetic launch bootstrap, preserves package-relative compiled-contract FNV-1a provenance in the normalized plan, validates YAML in memory, then atomically writes it. Run first reuses validate/normalize. Deterministic execution supports launch, takeScreenshot, tap(point/runtime-point), tap(text/source=ax/match=exact), input(text), press(button), swipe(from/to runtime-point), assertVisible(text/source=ax/match=exact), assertNotVisible(text/source=ax/match=exact), and scrollUntilVisible(text/source=ax/match=exact). P14 mock AI evidence supports assertWithAI, assertNoDefectsWithAI, extractTextWithAI, and strict-hash assertScreenshot; AI steps default optional except assertScreenshot and provider is limited to mock. Experimental VLM-assisted tap(target) is available only with --allow-vlm; remote VLM still requires --allow-remote-vlm. The runner writes observation.captured events with screenshot, AX, hierarchy, screenCandidate fingerprints, coordinate-contract.json, and vlm.grounding events when VLM is enabled. Report and create are offline-only and read existing .tritonevidence without device operations; create uses normalized-plan.json and validates the generated YAML before returning ok=true. Unsupported steps remain validation_error and do not trigger device operations. This surface does not implement App Map execution, replay, selector healing, JUnit, or autonomous loops. stop is validate-recognized but live embedded-runtime execution returns stop_not_supported until host app terminate target selection is wired.",
            nextCommands: [
                "triton schema --command test --json",
            ],
            outputContracts: [
                testValidationOutputContract(),
                testNormalizedPlanOutputContract(),
                testRunOutputContract(),
                testReportOutputContract(),
                testCreateOutputContract(),
                testImportOutputContract(),
            ],
            failureCodes: [
                "unknown_step",
                "missing_required_field",
                "invalid_point",
                "unsupported_step",
                "unsupported_selector",
                "unsupported_coordinate_space",
                "invalid_optional_type",
                "invalid_timeout",
                "unsupported_direction",
                "unsupported_grounding",
                "ai_unsupported_provider",
                "invalid_threshold",
                "vlm_unsupported_provider",
                "duplicate_step_id",
                "invalid_app_bundle_id",
                "invalid_yaml",
                "unsupported_schema_version",
                "validation_error",
                "launch_failed",
                "tap_failed",
                "input_failed",
                "press_failed",
                "swipe_failed",
                "assert_visible_failed",
                "assert_not_visible_failed",
                "scroll_until_visible_failed",
                "stop_not_supported",
                "vlm_step_not_allowed",
                "vlm_image_not_found",
                "vlm_coordinate_contract_not_found",
                "vlm_coordinate_contract_invalid",
                "vlm_coordinate_space_unsupported",
                "vlm_image_metadata_unavailable",
                "vlm_artifact_write_failed",
                "vlm_openai_base_url_required",
                "vlm_openai_base_url_invalid",
                "vlm_remote_provider_requires_approval",
                "vlm_api_key_missing",
                "vlm_provider_request_invalid",
                "vlm_provider_request_failed",
                "vlm_provider_response_invalid",
                "vlm_provider_point_parse_failed",
                "vlm_point_out_of_bounds",
                "primitive_failed",
                "test_report_failed",
                "test_create_failed",
                "test_import_failed",
                "invalid_case_directory",
                "missing_required_file",
                "invalid_json",
                "invalid_capabilities_ref",
                "invalid_output_path",
                "output_already_exists",
                "output_write_failed",
                "invalid_source_contract",
                "unsupported_import_platform",
                "truncated_source_contract",
                "missing_compiled_contract",
                "source_identity_mismatch",
                "unsupported_compiled_contract",
                "contract_quality_review_required",
                "redaction_review_required",
                "missing_page_evidence",
                "missing_actions",
                "unmapped_contract_feature",
                "invalid_expected_compiled_digest",
                "compiled_digest_mismatch",
                "unsupported_capability",
                "unsupported_provenance",
                "invalid_provenance",
                "ai_assertion_failed",
                "assert_screenshot_baseline_missing",
                "assert_screenshot_failed",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "validate",
                    summary: "Validate a .tritontest.yaml file and emit a normalized offline plan",
                    requiredOptions: ["<path.tritontest.yaml>"],
                    optionalOptions: ["--format", "--json", "--emit-normalized-plan"],
                    nextCommands: [
                        "triton schema --command test --json",
                    ],
                    outputSelectors: ["test.validation", "test.normalized-plan"],
                    failureCodes: [
                        "unknown_step",
                        "missing_required_field",
                        "invalid_point",
                        "unsupported_step",
                        "unsupported_selector",
                        "unsupported_coordinate_space",
                        "invalid_optional_type",
                        "invalid_timeout",
                        "unsupported_direction",
                        "unsupported_grounding",
                        "ai_unsupported_provider",
                        "invalid_threshold",
                        "vlm_unsupported_provider",
                        "duplicate_step_id",
                        "invalid_app_bundle_id",
                        "invalid_yaml",
                        "unsupported_schema_version",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "normalize",
                    summary: "Validate a .tritontest.yaml file and emit only the normalized plan",
                    requiredOptions: ["<path.tritontest.yaml>"],
                    optionalOptions: ["--format", "--json"],
                    nextCommands: [
                        "triton schema --command test --json",
                    ],
                    outputSelectors: ["test.normalized-plan"],
                    failureCodes: [
                        "unknown_step",
                        "missing_required_field",
                        "invalid_point",
                        "unsupported_step",
                        "unsupported_selector",
                        "unsupported_coordinate_space",
                        "invalid_optional_type",
                        "invalid_timeout",
                        "unsupported_direction",
                        "unsupported_grounding",
                        "ai_unsupported_provider",
                        "invalid_threshold",
                        "vlm_unsupported_provider",
                        "duplicate_step_id",
                        "invalid_app_bundle_id",
                        "invalid_yaml",
                        "unsupported_schema_version",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "run",
                    summary: "Validate, normalize, execute deterministic test steps, and write .tritonevidence observations",
                    requiredOptions: ["<path.tritontest.yaml>", "--evidence-dir"],
                    optionalOptions: ["--target", "--host", "--port", "--allow-vlm", "--allow-remote-vlm", "--vlm-base-url", "--vlm-model", "--vlm-api-key-env", "--format", "--json"],
                    nextCommands: [
                        "triton evidence summary <dir> --json",
                    ],
                    outputSelectors: ["test.run-result", "test.validation", "test.normalized-plan"],
                    failureCodes: [
                        "validation_error",
                        "unsupported_step",
                        "unsupported_coordinate_space",
                        "unsupported_selector",
                        "launch_failed",
                        "tap_failed",
                        "input_failed",
                        "press_failed",
                        "swipe_failed",
                        "assert_visible_failed",
                        "assert_not_visible_failed",
                        "scroll_until_visible_failed",
                        "stop_not_supported",
                        "vlm_step_not_allowed",
                        "vlm_image_not_found",
                        "vlm_coordinate_contract_not_found",
                        "vlm_coordinate_contract_invalid",
                        "vlm_coordinate_space_unsupported",
                        "vlm_image_metadata_unavailable",
                        "vlm_artifact_write_failed",
                        "vlm_openai_base_url_required",
                        "vlm_openai_base_url_invalid",
                        "vlm_remote_provider_requires_approval",
                        "vlm_api_key_missing",
                        "vlm_provider_request_invalid",
                        "vlm_provider_request_failed",
                        "vlm_provider_response_invalid",
                        "vlm_provider_point_parse_failed",
                        "vlm_point_out_of_bounds",
                        "primitive_failed",
                        "ai_assertion_failed",
                        "assert_screenshot_baseline_missing",
                        "assert_screenshot_failed",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "report",
                    summary: "Build an offline JSON report from an existing .tritonevidence run",
                    requiredOptions: ["<dir.tritonevidence>"],
                    optionalOptions: ["--format", "--json"],
                    nextCommands: [
                        "triton evidence summary <dir> --json",
                        "triton evidence project-workspace <dir> --json",
                    ],
                    outputSelectors: ["test.report"],
                    failureCodes: [
                        "test_report_failed",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "create",
                    summary: "Create an editable .tritontest.yaml draft from existing evidence",
                    requiredOptions: ["--from-session", "--output"],
                    optionalOptions: ["--name", "--format", "--json"],
                    nextCommands: [
                        "triton test validate <path.tritontest.yaml> --json",
                    ],
                    outputSelectors: ["test.create", "test.validation"],
                    failureCodes: [
                        "test_create_failed",
                        "validation_error",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "import",
                    summary: "Import an existing compiled testrec contract into a validated iOS Simulator test plan",
                    requiredOptions: ["<case.tritontestcase>", "--output", "--bundle-id", "--device-platform"],
                    optionalOptions: ["--expect-compiled-digest", "--format", "--json"],
                    nextCommands: [
                        "triton test validate <path.tritontest.yaml> --json",
                        "triton testrec inspect <case.tritontestcase> --json",
                    ],
                    outputSelectors: ["test.import", "test.validation", "test.normalized-plan"],
                    failureCodes: [
                        "test_import_failed",
                        "invalid_case_directory",
                        "missing_required_file",
                        "invalid_json",
                        "invalid_capabilities_ref",
                        "unsupported_schema_version",
                        "invalid_app_bundle_id",
                        "missing_required_field",
                        "invalid_output_path",
                        "output_already_exists",
                        "output_write_failed",
                        "invalid_source_contract",
                        "unsupported_import_platform",
                        "truncated_source_contract",
                        "missing_compiled_contract",
                        "source_identity_mismatch",
                        "unsupported_compiled_contract",
                        "contract_quality_review_required",
                        "redaction_review_required",
                        "missing_page_evidence",
                        "missing_actions",
                        "unmapped_contract_feature",
                        "invalid_expected_compiled_digest",
                        "compiled_digest_mismatch",
                        "unsupported_capability",
                        "unsupported_provenance",
                        "invalid_provenance",
                    ]
                ),
            ],
            providedCapabilities: ["test-import-compiled-contract", "test-validate", "test-normalized-plan", "test-run-minimal", "test-run-deterministic", "test-run-vlm-assisted", "test-run-ai-mock", "test-report", "test-create-from-session"]
        ),
    ]
}
