import Foundation
import TritonKitShared

func workspaceCommandSchemas() -> [TKCommandSchema] {
    [
        TKCommandSchema(
            name: "workspace",
            summary: "Create and inspect local agent workspace runs",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "local workspace",
            outputFormats: ["json", "jsonl", "text"],
            options: [
                TKCommandSchemaOption(name: "run", type: "Subcommand", description: "Create .triton/runs/<run-id> with the first workspace facts"),
                TKCommandSchemaOption(name: "inspect <run-id>", type: "Subcommand", description: "Read run.json and events.jsonl"),
                TKCommandSchemaOption(name: "stop <run-id>", type: "Subcommand", description: "Append run.stopped if the run is not already stopped"),
                TKCommandSchemaOption(name: "export-flow <run-id>", type: "Subcommand", description: "Write a .tritonflow.yaml seed from run facts"),
                TKCommandSchemaOption(name: "merge-map <run-id>", type: "Subcommand", description: "Merge a run-local atlas/app-map into a long-lived app map"),
                TKCommandSchemaOption(name: "--target", type: "String", defaultValue: "current", description: "Target selector recorded in the run"),
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony|unknown", defaultValue: "unknown", description: "Target platform fact recorded in run target metadata"),
                TKCommandSchemaOption(name: "--scope", type: "simulator|emulator|real|current", defaultValue: "current", description: "Target scope fact recorded in run target metadata"),
                TKCommandSchemaOption(name: "--app", type: "String", description: "App artifact, bundle id, package name, or app id"),
                TKCommandSchemaOption(name: "--goal", type: "String", description: "Natural-language run goal"),
                TKCommandSchemaOption(name: "--runs-dir", type: "Path", defaultValue: ".triton/runs", description: "Workspace run root"),
                TKCommandSchemaOption(name: "--run-id", type: "String", description: "Optional stable run id"),
                TKCommandSchemaOption(name: "--action-policy", type: "explore|planFirst", defaultValue: "explore", description: "Runner action policy recorded in config.yaml"),
                TKCommandSchemaOption(name: "--app-mode", type: "dry|attach|launch", defaultValue: "dry", description: "App lifecycle mode. launch submits triton app launch through the host app adapter before initial observation"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "iOS bundle identifier for --app-mode launch; defaults to --app for iOS targets"),
                TKCommandSchemaOption(name: "--package-name", type: "String", description: "Android package name for --app-mode launch; defaults to --app for Android targets"),
                TKCommandSchemaOption(name: "--activity", type: "String", description: "Android activity for explicit component launch"),
                TKCommandSchemaOption(name: "--bundle", type: "String", description: "Harmony bundle name for --app-mode launch; defaults to --app for Harmony targets"),
                TKCommandSchemaOption(name: "--ability", type: "String", description: "Harmony ability name for --app-mode launch"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "Path to adb executable for Android app launch"),
                TKCommandSchemaOption(name: "--max-steps", type: "Int", defaultValue: "20", description: "Maximum bounded runner steps before max_steps_reached"),
                TKCommandSchemaOption(name: "--allowed-action", type: "String[]", defaultValue: "tap,swipe,type,wait,verify,stop", description: "Allowed runner action; repeat to override the default action allowlist"),
                TKCommandSchemaOption(name: "--stop-condition", type: "String[]", defaultValue: "max_steps_reached,provider_missing,unsupported_capability,policy_rejected,model_unparseable", description: "Runner stop condition; repeat to override the default stop set"),
                TKCommandSchemaOption(name: "--observation-fixture", type: "Path", description: "Optional workspace observation fixture or triton observe JSON used to seed observation.captured and Atlas screen evidence"),
                TKCommandSchemaOption(name: "--observe-live", type: "Bool", defaultValue: "false", description: "Capture initial observation through triton observe instead of placeholder evidence"),
                TKCommandSchemaOption(name: "--observe-kind", type: "current|tree", defaultValue: "tree", description: "Live observation command kind used with --observe-live"),
                TKCommandSchemaOption(name: "--observe-max-nodes", type: "Int", description: "Maximum nodes to request from live observation"),
                TKCommandSchemaOption(name: "--observe-output", type: "Path", description: "Optional host layout artifact path for live observation"),
                TKCommandSchemaOption(name: "--runtime-base-url", type: "URL", description: "Direct embedded runtime base URL for live observation"),
                TKCommandSchemaOption(name: "--observe-host", type: "String", defaultValue: "127.0.0.1", description: "Embedded runtime host for live observation"),
                TKCommandSchemaOption(name: "--observe-port", type: "Int", defaultValue: "19421", description: "Embedded runtime port for live observation"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "Path to hdc executable for Harmony live observation"),
                TKCommandSchemaOption(name: "--business-ready-text", type: "String", description: "Exact visible text or runtime wait target that proves the business checkpoint ready"),
                TKCommandSchemaOption(name: "--business-ready-live-wait", type: "Bool", defaultValue: "false", description: "Use runtime wait text matching instead of initial-observation-only matching for the business checkpoint"),
                TKCommandSchemaOption(name: "--business-ready-timeout", type: "Double", defaultValue: "10", description: "Timeout in seconds for --business-ready-live-wait"),
                TKCommandSchemaOption(name: "--business-ready-interval", type: "Double", defaultValue: "0.5", description: "Polling interval in seconds for --business-ready-live-wait"),
                TKCommandSchemaOption(name: "--execute-actions", type: "Bool", defaultValue: "false", description: "Execute model-selected candidate actions through the runtime action provider instead of writing synthetic action evidence"),
                TKCommandSchemaOption(name: "--llm-provider", type: "String", description: "Optional LLM provider id to preflight for workspace bootstrap"),
                TKCommandSchemaOption(name: "--llm-base-url", type: "URL", description: "OpenAI-compatible LLM /v1 base URL for workspace model decisions"),
                TKCommandSchemaOption(name: "--llm-model", type: "String", description: "OpenAI-compatible LLM model for workspace model decisions"),
                TKCommandSchemaOption(name: "--llm-api-key-env", type: "String", description: "Environment variable containing the workspace LLM provider API key"),
                TKCommandSchemaOption(name: "--allow-remote-llm", type: "Bool", defaultValue: "false", description: "Allow non-localhost workspace LLM provider requests"),
                TKCommandSchemaOption(name: "--vlm-provider", type: "String", description: "Optional VLM provider id to preflight for workspace bootstrap"),
                TKCommandSchemaOption(name: "--vlm-base-url", type: "URL", description: "OpenAI-compatible VLM /v1 base URL for workspace visual decisions"),
                TKCommandSchemaOption(name: "--vlm-model", type: "String", description: "OpenAI-compatible VLM model for workspace visual decisions"),
                TKCommandSchemaOption(name: "--vlm-model-path", type: "Path", description: "Local mlx-swift-lm model path for workspace visual grounding"),
                TKCommandSchemaOption(name: "--vlm-helper", type: "Path", description: "External mlx-swift-lm helper path for workspace visual grounding"),
                TKCommandSchemaOption(name: "--vlm-allow-model-download", type: "Bool", defaultValue: "false", description: "Allow mlx-swift-lm helper to materialize the configured local model"),
                TKCommandSchemaOption(name: "--vlm-api-key-env", type: "String", description: "Environment variable containing the workspace VLM provider API key"),
                TKCommandSchemaOption(name: "--allow-remote-vlm", type: "Bool", defaultValue: "false", description: "Allow non-localhost workspace VLM provider requests"),
                TKCommandSchemaOption(name: "--dry-model-fixture", type: "Bool", defaultValue: "false", description: "Append dry model/policy/action/recovery events without calling a model or device"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Output .tritonflow.yaml path for export-flow"),
                TKCommandSchemaOption(name: "--map-dir", type: "Path", description: "Output app-map directory for merge-map"),
                TKCommandSchemaOption(name: "--confirm", type: "Bool", defaultValue: "false", description: "Mark merged workspace candidate paths as confirmed"),
                schemaFormatJSONTextOption,
                schemaJSONAliasOption,
            ],
            usageForms: [
                TKCommandUsageForm(form: "run --target current --app <app> --goal <goal> --json", kind: "Subcommand", description: "Create a local workspace run facts directory"),
                TKCommandUsageForm(form: "inspect <run-id> --json", kind: "Subcommand", description: "Read run status and event summary"),
                TKCommandUsageForm(form: "stop <run-id> --json", kind: "Subcommand", description: "Stop a run idempotently"),
                TKCommandUsageForm(form: "export-flow <run-id> --output <file.tritonflow.yaml> --json", kind: "Subcommand", description: "Export a flow seed from run facts"),
                TKCommandUsageForm(form: "merge-map <run-id> --map-dir <dir.tritonmap> --json", kind: "Subcommand", description: "Accumulate a run-local app-map into a long-lived map"),
            ],
            argumentForms: [
                TKCommandArgumentForm(name: "<run-id>", type: "String", required: true, description: "Workspace run id under --runs-dir"),
            ],
            examples: [
                #"triton workspace run --target current --app com.example.demo --goal "Explore login" --json"#,
                #"triton workspace run --target booted --platform ios --scope simulator --app com.example.demo --app-mode launch --bundle-id com.example.demo --observe-live --json"#,
                #"triton workspace run --target booted --platform ios --scope simulator --app com.example.demo --goal "Open login" --observe-live --business-ready-text Continue --json"#,
                #"triton workspace run --target booted --platform ios --scope simulator --app com.example.demo --goal "Open dashboard" --business-ready-text Dashboard --business-ready-live-wait --json"#,
                #"triton workspace run --target current --app com.example.demo --goal "Open next screen" --llm-provider mock --vlm-provider mock --execute-actions --json"#,
                #"triton workspace run --target current --app com.example.demo --goal "Open next screen" --llm-provider openai-compatible --llm-base-url http://127.0.0.1:8000/v1 --llm-model local-workspace-model --vlm-provider mock --execute-actions --json"#,
                #"triton workspace run --target current --app com.example.demo --goal "Open next screen" --llm-provider mock --vlm-provider openai-compatible --vlm-base-url http://127.0.0.1:8000/v1 --vlm-model local-vlm-model --json"#,
                #"triton workspace run --target current --app com.example.demo --goal "Open next screen" --llm-provider mock --vlm-provider mlx-swift-lm --vlm-model-path ~/.cache/triton/mlx-models/qwen-vl --vlm-helper /path/to/triton-mlx-provider --vlm-allow-model-download --execute-actions --json"#,
                "triton workspace inspect run_123 --json",
                "triton workspace stop run_123 --json",
                "triton workspace export-flow run_123 --output flow.tritonflow.yaml --json",
                "triton workspace merge-map run_123 --map-dir .triton/maps/com.example.demo.tritonmap --confirm --json",
            ],
            successShape: "run emits triton.workspace.run; inspect/stop emit triton.workspace.inspect; export-flow emits triton.workspace.export-flow; merge-map emits triton.workspace.merge-map",
            outputSemantics: "workspace run is the local Run entry. It writes .triton/runs/<run-id>/run.json, config.yaml, events.jsonl, report.json, evidence placeholders, workspace observation fixture evidence, or live/fixture triton observe output evidence, atlas/atlas.json, runner bounds, default llm/vlm enabled state, provider preflight nextActions, policy rejection nextActions, flow.bootstrap.checked, and model loop events when mock providers are ready, openai-compatible LLM/VLM are configured, mlx-swift-lm VLM has a local model name or model path, or dry-model fixture is enabled. With --app-mode launch, workspace run submits triton app launch through the host app adapter first and writes evidence/actions/app-ready.json with launch_submitted and businessReady=false. When --observe-live succeeds in the same run after launch, app.ready phase upgrades to launch_observed, ready=true, observedAfterLifecycle=true, and observationRef=events.jsonl#observation.captured while businessReady remains false. The run still requires wait/verify/action evidence before claiming the business flow is ready. With --business-ready-text, workspace run verifies exact visible text from the initial observation, writes evidence/business/ready.json, emits business.ready plus verify.checked, and returns run.status=passed only when that checkpoint is matched. With --business-ready-live-wait, workspace run requires --business-ready-text, calls runtime wait(text), writes evidence/business/ready.json with check=runtime_wait, source=runtime.wait, phase=wait_matched|wait_timeout|wait_unmatched and nested wait evidence, emits business.ready plus verify.checked, and returns run.status=passed only when the wait result is ok. With --llm-provider openai-compatible plus --llm-base-url and --llm-model, workspace run calls the local or explicitly approved OpenAI-compatible Chat Completions endpoint for bounded JSON action candidates, records llmBaseURL redacted in model artifacts, and rejects remote endpoints unless --allow-remote-llm is explicit. With --vlm-provider openai-compatible plus --vlm-base-url and --vlm-model, workspace run preflights the local or explicitly approved OpenAI-compatible visual provider, records vlmBaseURL redacted in provider/model artifacts, and rejects remote endpoints unless --allow-remote-vlm is explicit; with --vlm-provider mlx-swift-lm plus --vlm-model or --vlm-model-path, workspace run uses the local mlx-swift-lm helper selected by --vlm-helper or environment fallback and records vlmModelPath/vlmHelper/vlmAllowModelDownload in provider/model artifacts without remote screenshot upload. Screenshot grounding runs before bounded tap actions when the selected observation has a readable local screenshot artifact and remains policy/evidence gated. If VLM grounding fails before the runtime action, workspace run writes evidence/actions/vlm-<step>/vlm-failure.json, records evidence/actions/action-<step>.json with proofSource=vlm.grounding and failureKind=vlm_grounding_failed, writes an evidence-backed workspace recovery proposal, and pauses with inspect_vlm_grounding_failure. With --execute-actions, workspace run records a model decision request containing goal, runner bounds, provider status, current observation visibleTexts, and configured LLM/VLM metadata. If a model decision provider returns action/query/confidence/candidateSource, that output drives the runtime action, events, model artifacts, Atlas transition, and exported flow; the default mock provider derives a tap candidate for each bounded step from visibleTexts, preferring Continue, Start, Get Started, Next, Login, Log In, and Sign In, then the first visible text, falling back to Continue when no visible text exists. It calls the runtime action provider for that candidate, writes evidence/actions/action-000.json with proofSource=runtime.input and source=workspace.action-provider, emits action.executed with that evidence ref, and records the Atlas transition as executed_unverified until a later wait/verify proves business readiness. If --observe-live is also enabled and the action succeeds, workspace run calls live observe again after the action, saves raw ObserveOutput to evidence/observations/0001.json, emits observation.captured phase=post_action, adds screen_0001/state_0001, and records the Atlas transition as screen_0000 -> screen_0001. When --execute-actions and --business-ready-live-wait are combined, the runtime wait runs after a successful action; a matched wait writes business evidence with stage=post_action and phase=post_action_wait_matched, emits action.executed before post_action observation, business.ready, and verify.checked, returns run.status=passed, and records the Atlas transition as verified. When --execute-actions, --observe-live, --business-ready-live-wait, and maxSteps > 1 are combined, workspace run continues a bounded recovery loop after a failed post-action business checkpoint: the next model request uses the latest post-action observation visibleTexts, writes step-indexed decision/action/verify artifacts such as decision-001.json and action-001.json, appends Atlas transitions such as transition_0001, and stops when the business checkpoint passes, policy rejects, an action fails, observation is unavailable, or maxSteps is reached. With --observe-live, workspace run calls triton observe current/tree, saves initial raw ObserveOutput to evidence/observations/0000.json, and derives observation.captured plus Atlas seed from that evidence. Workspace also projects the run-local Atlas into atlas/app-map/app-map.json with app-map screens, stateVariants, transitions, candidate paths, run record, coverage summary, and inspectable path ids. workspace merge-map reads that run-local atlas/app-map projection and accumulates it into a long-lived map directory, preserving screen stateVariants, sourceRuns, path health, and coverage across runs. workspace inspect returns run status, event summary, latest bootstrap, latest bootstrap proposal, latest pause, Atlas coverage summary, and optional appMap summary.",
            jsonlEvents: [
                "run.started",
                "target.resolved",
                "provider.checked",
                "app.ready",
                "observation.captured",
                "flow.bootstrap.checked",
                "model.decided",
                "policy.checked",
                "action.executed",
                "verify.checked",
                "business.ready",
                "flow.recovery.detected",
                "flow.recovery.proposed",
                "flow.recovery.rejected",
                "atlas.updated",
                "flow.updated",
                "run.paused",
                "run.stopped",
                "run.finished",
            ],
            artifacts: [
                "manifest",
                "host-artifacts",
                "runtime-snapshot",
                "runtime-ledger",
                "ax",
                "screenshot",
                "screen-workspace",
                "coordinate-contract",
                "vlm-grounding",
                "vlm-grounding-failure",
                "workspace-recovery-proposal",
                "triton-plan",
            ],
            nextCommands: [
                "triton doctor --json",
                "triton status --json",
                "triton observe tree --json",
                "triton verify text-exists <text> --json",
            ],
            outputContracts: [
                TKCommandOutputContract(
                    selector: "workspace.run",
                    format: "json",
                    kind: "envelope",
                    model: "TKWorkspaceRunResponse",
                    fields: schemaFields([
                        ("kind", "String", true, "triton.workspace.run"),
                        ("runId", "String", true, "Workspace run id"),
                        ("status", "String", true, "passed, paused, stopped, or running state"),
                        ("target", "TKWorkspaceRunTarget", true, "Target selector, platform, scope, and capabilities"),
                        ("app", "String", true, "App identifier recorded for the run"),
                        ("ai", "TKWorkspaceRunAI", true, "LLM/VLM provider status and policy state"),
                        ("runner", "TKWorkspaceRunRunner?", false, "Bounded runner config"),
                        ("business", "TKWorkspaceBusinessReadiness?", false, "Business checkpoint status when configured"),
                        ("paths", "TKWorkspaceRunPaths", true, "Run artifact paths"),
                        ("nextActions", "[TKWorkspaceNextAction]", true, "Machine-readable follow-up actions"),
                    ])
                ),
                TKCommandOutputContract(
                    selector: "workspace.inspect",
                    format: "json",
                    kind: "envelope",
                    model: "TKWorkspaceInspectResponse",
                    fields: schemaFields([
                        ("kind", "String", true, "triton.workspace.inspect"),
                        ("run", "TKWorkspaceRunResponse", true, "Current run response"),
                        ("summary", "TKTestRunEventSummary", true, "Parsed events summary"),
                        ("atlas", "TKWorkspaceAtlasSummary", true, "Atlas coverage summary"),
                        ("appMap", "TKWorkspaceAppMapSummary?", false, "Run-local app-map projection summary from atlas/app-map/app-map.json"),
                        ("latestBootstrap", "TKTestRunEvent?", false, "Latest bootstrap check event"),
                        ("latestBootstrapProposal", "TKTestRunEvent?", false, "Latest model bootstrap proposal event"),
                        ("latestPause", "TKTestRunEvent?", false, "Latest pause event"),
                    ])
                ),
                TKCommandOutputContract(
                    selector: "workspace.export-flow",
                    format: "json",
                    kind: "envelope",
                    model: "TKWorkspaceExportFlowResponse",
                    fields: schemaFields([
                        ("kind", "String", true, "triton.workspace.export-flow"),
                        ("runId", "String", true, "Workspace run id"),
                        ("output", "String", true, "Written .tritonflow.yaml path"),
                        ("stepCount", "Int", true, "Exported flow step count"),
                    ])
                ),
                TKCommandOutputContract(
                    selector: "workspace.merge-map",
                    format: "json",
                    kind: "envelope",
                    model: "TKWorkspaceMergeMapResponse",
                    fields: schemaFields([
                        ("kind", "String", true, "triton.workspace.merge-map"),
                        ("runId", "String", true, "Merged workspace run id"),
                        ("sourceMapRef", "String", true, "Run-local atlas/app-map source"),
                        ("mapDir", "String", true, "Long-lived app-map directory"),
                        ("screenCount", "Int", true, "Merged screen count"),
                        ("transitionCount", "Int", true, "Merged transition count"),
                        ("pathCount", "Int", true, "Merged path count"),
                        ("suiteCount", "Int", true, "Merged suite count"),
                        ("coverage", "TKAppMapCoverage", true, "Long-lived app-map coverage summary after merge"),
                        ("pathIds", "[String]", true, "Merged path ids"),
                    ])
                ),
            ],
            failureCodes: ["workspace_failed"],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "run",
                    summary: "Create a local workspace run facts directory",
                    requiredOptions: ["--app", "--goal"],
                    optionalOptions: ["--target", "--platform", "--scope", "--runs-dir", "--run-id", "--action-policy", "--app-mode", "--bundle-id", "--package-name", "--activity", "--bundle", "--ability", "--adb", "--max-steps", "--allowed-action", "--stop-condition", "--observation-fixture", "--observe-live", "--observe-kind", "--observe-max-nodes", "--observe-output", "--runtime-base-url", "--observe-host", "--observe-port", "--hdc", "--business-ready-text", "--business-ready-live-wait", "--business-ready-timeout", "--business-ready-interval", "--execute-actions", "--llm-provider", "--llm-base-url", "--llm-model", "--llm-api-key-env", "--allow-remote-llm", "--vlm-provider", "--vlm-base-url", "--vlm-model", "--vlm-model-path", "--vlm-helper", "--vlm-allow-model-download", "--vlm-api-key-env", "--allow-remote-vlm", "--dry-model-fixture", "--format", "--json"],
                    jsonlEvents: ["run.started", "target.resolved", "provider.checked", "app.ready", "observation.captured", "flow.bootstrap.checked", "business.ready", "model.decided", "policy.checked", "action.executed", "verify.checked", "flow.recovery.detected", "flow.recovery.proposed", "flow.recovery.rejected", "atlas.updated", "flow.updated", "run.paused", "run.stopped", "run.finished"],
                    artifacts: ["manifest", "host-artifacts", "runtime-snapshot", "runtime-ledger", "ax", "screenshot", "screen-workspace", "coordinate-contract", "vlm-grounding", "vlm-grounding-failure", "workspace-recovery-proposal", "triton-plan"],
                    outputSelectors: ["workspace.run"],
                    failureCodes: ["workspace_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "inspect",
                    summary: "Read a local workspace run",
                    requiredOptions: ["<run-id>"],
                    optionalOptions: ["--runs-dir", "--format", "--json"],
                    outputSelectors: ["workspace.inspect"],
                    failureCodes: ["workspace_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "stop",
                    summary: "Stop a local workspace run idempotently",
                    requiredOptions: ["<run-id>"],
                    optionalOptions: ["--runs-dir", "--format", "--json"],
                    outputSelectors: ["workspace.inspect"],
                    failureCodes: ["workspace_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "export-flow",
                    summary: "Export a .tritonflow.yaml seed from a local workspace run",
                    requiredOptions: ["<run-id>", "--output"],
                    optionalOptions: ["--runs-dir", "--format", "--json"],
                    outputSelectors: ["workspace.export-flow"],
                    failureCodes: ["workspace_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "merge-map",
                    summary: "Merge a run-local app-map into a long-lived map",
                    requiredOptions: ["<run-id>", "--map-dir"],
                    optionalOptions: ["--runs-dir", "--confirm", "--format", "--json"],
                    outputSelectors: ["workspace.merge-map"],
                    failureCodes: ["workspace_failed"]
                ),
            ]
        ),
    ]
}
