import Foundation
import TritonKitShared

func observationCommandSchemas() -> [TKCommandSchema] {
    let hostPort = schemaHostPortOptions
    let target = schemaTargetOption
    let targetDeviceAlias = schemaTargetDeviceAliasOption
    let jsonText = schemaTextJSONFormats
    let formatTextJSON = schemaFormatTextJSONOption
    let formatJSONText = schemaFormatJSONTextOption
    let jsonAlias = schemaJSONAliasOption
    let languageOption = schemaLanguageOption
    let runtimeBaseURLOption = schemaRuntimeBaseURLOption
    let metadataJSONAlias = schemaMetadataJSONAliasOption
    let refreshOption = schemaRefreshOption
    let runtimeTargetFailureCodes = schemaRuntimeTargetFailureCodes
    let hierarchyFailureCodes = schemaHierarchyFailureCodes
    let nodeFailureCodes = schemaNodeFailureCodes

    return [
        TKCommandSchema(
            name: "list",
            summary: "List connected embedded runtime targets",
            requiresServer: true,
            requiresTarget: false,
            runtimeScope: "cli",
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "text", description: "Output format"),
                jsonAlias,
                languageOption,
                TKCommandSchemaOption(name: "--ids-only", type: "Bool", defaultValue: "false", description: "Print only target ids"),
            ],
            examples: ["triton list --format json", "triton list --ids-only"],
            successShape: "{ targets: [{ id, transport, connected, latestHierarchyAvailable, activeHierarchyAvailable, cachedHierarchyAvailable, hierarchyCacheState, identityState, appName, bundleIdentifier, deviceDescription, osDescription }] }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|request_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "`triton list` is embedded-runtime discovery only. For host-side iOS Simulator, Android Emulator, or Harmony HDC device workflows, use `triton target list --platform <platform> --json` or `triton device list --platform <platform> --json` before falling back to raw platform tools.",
            nextCommands: [
                "triton inspect --target <id> --json",
                "triton target list --platform <ios|android|harmony> --json",
                "triton device list --platform <ios|android|harmony> --json",
                "triton status --json",
                "triton doctor --format json",
            ],
            outputContracts: [targetsListOutputContract()],
            failureCodes: ["server_unavailable", "request_failed"]
        ),
        TKCommandSchema(
            name: "inspect",
            summary: "Inspect one Triton target summary",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "cli",
            outputFormats: jsonText,
            options: hostPort + [target, formatTextJSON, jsonAlias],
            examples: ["triton inspect --target triton:local --format json"],
            successShape: "{ id, transport, connected, latestHierarchyAvailable, appName, bundleIdentifier, deviceDescription, osDescription }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use inspect after list to read target identity and hierarchy freshness for one selected target.",
            nextCommands: [
                "triton status --json",
                "triton debug hierarchy --target <id> --json",
                "triton debug snapshot --target <id> --json",
                "triton evidence capture --case <case> --target <id> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [targetSummaryOutputContract()],
            failureCodes: ["server_unavailable", "target_not_found", "ambiguous_target", "request_failed"]
        ),
        TKCommandSchema(
            name: "observe",
            summary: "Read the current app surface using iOS runtime, iOS Simulator host AX, or Android/Harmony host layout sources",
            requiresServer: false,
            requiresTarget: true,
            runtimeScope: "embedded|host-ios|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "current", type: "Subcommand", description: "Read current visible app snapshot"),
                TKCommandSchemaOption(name: "tree", type: "Subcommand", description: "Read current visible node tree"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Observation platform or host device platform filter"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector: alias, sim:<udid>, android:<serial>, harmony:<target>, raw id, booted, or current"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable for --platform harmony"),
                TKCommandSchemaOption(name: "--max-nodes", type: "Int", description: "Maximum nodes to return"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Android or Harmony host layout artifact path"),
                TKCommandSchemaOption(name: "--outline", type: "Bool", defaultValue: "false", description: "Emit deterministic @N node aliases and cache them in .triton/node-aliases.json for `node resolve @N`"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton observe current --platform ios --json",
                "triton observe tree --platform ios --device <selector> --json",
                "triton observe tree --platform ios --device <selector> --outline --json",
                "triton debug snapshot --include media,ax,screenshot-metadata --json",
                "triton observe tree --platform android --device android-a --json",
                "triton observe tree --device harmony-a --json",
                "triton observe tree --platform harmony --target 127.0.0.1:10100 --json",
            ],
            successShape: "{ ok, action, platform, capturedAt, partial, target, sources[], nodes[], outline?[], aliasCache?, artifacts[], sourceCommands[], note }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|simulator_not_found|ambiguous_target|host_command_failed|validation_failed|ios_host_ax_unavailable, message, hint, nextAction? }, candidates?[] }",
            outputSemantics: "Use observe to read native visible surface state across iOS embedded runtime, iOS Simulator host AX, Android layout, and Harmony host layout before choosing tap, WebView, route, screenshot, or evidence commands. Add --outline to create stable @N aliases for immediate follow-up `node resolve @N` or action planning in the same workspace.",
            artifacts: ["harmony-layout"],
            nextCommands: [
                "triton status --json",
                "triton webview current --json",
                "triton act find <text> --all --json",
                "triton screenshot --output <path> --metadata",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [observeSurfaceOutputContract()],
            failureCodes: [
                "server_unavailable",
                "target_unavailable",
                "target_not_found",
                "ambiguous_target",
                "host_command_failed",
                "harmony_layout_path_not_found",
                "harmony_layout_text_not_found",
                "harmony_layout_failed",
                "harmony_artifact_recv_failed",
                "validation_failed",
            ] + schemaIOSHostAXFailureCodes,
            providedCapabilities: ["observe", "observe-ios", "observe-ios-host-ax", "observe-android", "observe-harmony", "observe-outline"]
        ),
        TKCommandSchema(
            name: "webview",
            summary: "List or resolve current WebView candidates while preserving provider boundaries",
            requiresServer: false,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "list", type: "Subcommand", description: "List visible WebView candidates"),
                TKCommandSchemaOption(name: "current", type: "Subcommand", description: "Resolve current visible WebView candidate"),
                TKCommandSchemaOption(name: "current-url", type: "Subcommand", description: "Resolve current WebView provider URL without DOM or JS access"),
                TKCommandSchemaOption(name: "snapshot", type: "Subcommand", description: "Read bounded WebView metadata, text, DOM, forms, and links from a provider"),
                TKCommandSchemaOption(name: "call <method>", type: "Subcommand", description: "Call a page opt-in bridge method; arbitrary JavaScript eval remains unsupported"),
                TKCommandSchemaOption(name: "events", type: "Subcommand", description: "Read buffered opt-in WebView page events"),
                TKCommandSchemaOption(name: "wait", type: "Subcommand", description: "Wait for exact WebView text, simple #id selector, or exact page event name"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--platform", type: "ios|harmony", defaultValue: "ios", description: "Observation platform"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable for --platform harmony"),
                TKCommandSchemaOption(name: "--webview-id", type: "String", description: "Select a candidate from `triton webview list`"),
                TKCommandSchemaOption(name: "--page-session-id", type: "String", description: "Expected page session id from `triton webview current`"),
                TKCommandSchemaOption(name: "--include", type: "String", defaultValue: "metadata,dom,text,forms,links", description: "Comma-separated WebView snapshot sections"),
                TKCommandSchemaOption(name: "--max-dom-nodes", type: "Int", description: "Maximum DOM node summaries for `webview snapshot`"),
                TKCommandSchemaOption(name: "--max-text-bytes", type: "Int", description: "Maximum text bytes for `webview snapshot`"),
                TKCommandSchemaOption(name: "--arg", type: "key=value", description: "Bridge call argument; repeat for multiple values"),
                TKCommandSchemaOption(name: "--timeout-ms", type: "Int", description: "Bridge call timeout in milliseconds"),
                TKCommandSchemaOption(name: "--limit", type: "Int", defaultValue: "50", description: "Maximum events to return"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "Exact visible text line for `webview wait`; no contains matching"),
                TKCommandSchemaOption(name: "--selector", type: "String", description: "Simple #id selector for `webview wait`; complex CSS selectors return webview_wait_unsupported"),
                TKCommandSchemaOption(name: "--event", type: "String", description: "Exact event name for `webview wait`"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "10", description: "Wait timeout in seconds"),
                TKCommandSchemaOption(name: "--interval", type: "Double", defaultValue: "0.5", description: "Wait polling interval in seconds"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Harmony host layout artifact path"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton webview list --platform ios --json",
                "triton webview current --platform harmony --target 127.0.0.1:10100 --json",
                "triton webview current-url --platform ios --json",
                "triton webview snapshot --platform ios --include metadata,text,forms --json",
                "triton webview call getRouteState --platform ios --json",
                "triton webview events --platform ios --limit 50 --json",
                "triton webview wait --text Ready --json",
                "triton webview wait --selector '#submit' --json",
                "triton webview wait --event checkout.ready --json",
            ],
            successShape: "{ ok, action, platform, capturedAt, target, primarySource?, current?, candidates[], sources[], sourceCommands[], note } or { ok, action, platform, capturedAt, target, primarySource?, webView{providerCapabilities?}, sources[], sourceCommands[], note } or { ok, action:webview.current-url, platform, capturedAt, target, webViewID, url, title?, pageSessionID?, providerStatus, bridgeStatus, providerCapabilities? } or { ok, action:webview.snapshot, capturedAt, platform, target, webView{providerCapabilities?}, include[], text[], dom[], forms[], links[], skipped[], truncation, redaction } or { ok, action, capturedAt, platform, target, webViewID, pageSessionID?, method, result?, elapsedMs, redaction } or { ok, action, capturedAt, platform, target, events[], limit } or { ok, action:webview.wait, capturedAt, platform, target, webView?, candidates?[], condition, query, matched, timedOut, elapsedMs, pollCount, timeoutSeconds, intervalSeconds, pageSessionID?, lastObservedTextSample[], lastObservedNodeIDs[], lastObservedEventNames[], match?, error?, redaction }",
            failureShape: "{ ok:false, action, platform, target, error:{ code: webview_not_found|ambiguous_webview|webview_id_not_found|webview_provider_unavailable|webview_bridge_unavailable|webview_method_not_allowed|webview_navigation_changed|webview_wait_timeout|webview_wait_unsupported|javascript_error, message, hint, nextAction? }, candidates?[] } or webview.wait response with ok:false,error",
            outputSemantics: "Use WebView commands only through opt-in providers. Start with list/current/current-url, then snapshot/wait/call; arbitrary JavaScript remains outside the default contract.",
            artifacts: ["harmony-layout"],
            nextCommands: [
                "triton status --json",
                "triton route assert-current-url <url> --json",
                "triton webview snapshot --include metadata,text,forms --json",
                "triton webview wait --text <text> --json",
                "triton observe current --json",
            ],
            outputContracts: [
                webViewListOutputContract(),
                webViewCurrentOutputContract(),
                webViewCurrentURLOutputContract(),
                webViewSnapshotOutputContract(),
                webViewBridgeCallOutputContract(),
                webViewEventsOutputContract(),
                webViewWaitOutputContract(),
            ],
            failureCodes: [
                "server_unavailable",
                "target_unavailable",
                "target_not_found",
                "ambiguous_target",
                "host_command_failed",
                "webview_not_found",
                "ambiguous_webview",
                "webview_id_not_found",
                "webview_provider_unavailable",
                "webview_bridge_unavailable",
                "webview_method_not_allowed",
                "webview_navigation_changed",
                "webview_wait_timeout",
                "webview_wait_unsupported",
                "javascript_error",
                "validation_failed",
            ],
            providedCapabilities: ["webview-list", "webview-current", "webview-current-url", "webview-snapshot", "webview-bridge-call", "webview-events", "webview-wait"]
        ),
        TKCommandSchema(
            name: "route",
            summary: "Assert current route and WebView navigation state",
            requiresServer: false,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "assert-current-url <expected-url>", type: "Subcommand", description: "Assert the current WebView provider URL"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--ignore-query", type: "Bool", defaultValue: "false", description: "Ignore query items when comparing URLs"),
                TKCommandSchemaOption(name: "--platform", type: "ios|harmony", defaultValue: "ios", description: "Observation platform"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable for --platform harmony"),
                TKCommandSchemaOption(name: "--webview-id", type: "String", description: "Select a candidate from `triton webview list`"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Harmony host layout artifact path"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                #"triton route assert-current-url "https://example.invalid/path" --json"#,
                #"triton route assert-current-url "https://example.invalid/path" --ignore-query --json"#,
            ],
            successShape: "{ ok, action:route.assert-current-url, status, expectedURL, actualURL, matched, ignoreQuery, platform, target, webViewID, title?, pageSessionID?, hint? }",
            failureShape: "For URL mismatch returns same shape with ok=false,status=fail and exit 1; provider/selection failures return WebView error envelope",
            outputSemantics: "Use route assertions after WebView current-url or native route state to produce a machine-readable pass/fail gate.",
            nextCommands: [
                "triton status --json",
                "triton route assert-current-url <expected-url> --json",
                "triton webview current-url --json",
                "triton webview snapshot --include metadata,text --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [routeCurrentURLAssertionOutputContract()],
            failureCodes: [
                "route_mismatch",
                "server_unavailable",
                "target_unavailable",
                "target_not_found",
                "ambiguous_target",
                "request_failed",
                "webview_not_found",
                "ambiguous_webview",
                "webview_id_not_found",
                "webview_provider_unavailable",
                "host_command_failed",
                "validation_failed",
            ],
            providedCapabilities: ["route-current-url-assert"]
        ),
        TKCommandSchema(
            name: "hierarchy",
            summary: "Read latest hierarchy snapshot or platform-neutral hierarchy scene",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: ["tree", "json"],
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Return a platform-neutral hierarchy scene using iOS Lookin-style displayItems, Android UIAutomator, or Harmony dumpLayout sources"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector for --platform mode"),
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--max-nodes", type: "Int", description: "Maximum nodes to include in --platform scene mode"),
                TKCommandSchemaOption(name: "--format", type: "tree|json", defaultValue: "tree", description: "Output format"),
                jsonAlias,
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Optional output file"),
                TKCommandSchemaOption(name: "--artifact-output", type: "Path", description: "Optional Android or Harmony host layout artifact path in --platform mode"),
                TKCommandSchemaOption(name: "--refresh/--no-refresh", type: "Bool", defaultValue: "true", description: "Request fresh hierarchy before reading"),
                TKCommandSchemaOption(name: "--hide-noise/--no-hide-noise", type: "Bool", defaultValue: "true", description: "Hide low-signal UIKit wrapper views in tree output"),
            ],
            examples: [
                "triton hierarchy --target triton:local --format json --output /tmp/hierarchy.json",
                "triton hierarchy --platform ios --target triton:local --json",
                "triton hierarchy --platform android --device emulator-5554 --json",
                "triton hierarchy --platform harmony --device 127.0.0.1:10100 --json",
            ],
            successShape: "Legacy mode: TKHierarchyInfo JSON or rendered tree. --platform mode: TKHostHierarchyResponse { ok, capturedAt, source, scene:{ platform, rootId, viewport, nodes[] } }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|hierarchy_unavailable|request_failed|host_command_failed|artifact_write_failed, message, endpoint?, hint, nextAction? } }",
            outputSemantics: "Use hierarchy --platform for Lookin-style cross-platform scene data consumed by Web and agents. Legacy mode keeps full raw iOS runtime hierarchy inspection. Prefer snapshot/observe for bounded decisions.",
            artifacts: ["hierarchy-json"],
            nextCommands: [
                "triton status --json",
                "triton observe tree --platform <platform> --json",
                "triton nodes --json",
                "triton node --oid <oid> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [hierarchyInfoOutputContract(), hierarchySceneOutputContract()],
            failureCodes: hierarchyFailureCodes + ["host_command_failed", "artifact_write_failed"],
            providedCapabilities: ["hierarchy", "hierarchy-scene", "android-hierarchy", "harmony-hierarchy"]
        ),
        TKCommandSchema(
            name: "nodes",
            summary: "List node summaries from the latest hierarchy snapshot",
            requiresServer: true,
            requiresTarget: true,
            requiresHierarchy: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [target, formatTextJSON, jsonAlias, refreshOption],
            examples: ["triton nodes --target triton:local --format json"],
            successShape: "{ nodes: [{ oid, viewOid, layerOid, className, depth, frame, hidden, alpha }] }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|hierarchy_unavailable|request_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use nodes to turn a full hierarchy into a flat oid index for node, attrs, object, hit, and action debugging.",
            nextCommands: [
                "triton status --json",
                "triton node --oid <oid> --json",
                "triton attrs --oid <layerOid> --json",
                "triton hit --at <x,y> --json",
            ],
            outputContracts: [hierarchyNodesOutputContract()],
            failureCodes: hierarchyFailureCodes
        ),
        TKCommandSchema(
            name: "node",
            summary: "Resolve a current visible UI node",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-ios|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "resolve <query>|--text <text>", type: "Subcommand", description: "Resolve current visible node by text/id or @N alias"),
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", defaultValue: "ios", description: "Platform for `node resolve`"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector: alias, sim:<udid>, android:<serial>, harmony:<target>, raw id, booted, or current"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable for `node resolve --platform harmony`"),
                target,
                TKCommandSchemaOption(name: "<query>", type: "String", description: "Text/id/key/accessibility id or @N alias for `node resolve`"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "Backward-compatible text/id/key/accessibility id for `node resolve`"),
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one current-node candidate by 1-based index"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict current-node candidates to bounds"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Restrict current-node candidates to a point"),
                TKCommandSchemaOption(name: "--all", type: "Bool", defaultValue: "false", description: "Include all current-node candidates"),
                formatTextJSON,
                jsonAlias,
                refreshOption,
            ],
            examples: [
                #"triton node resolve --platform ios --text "登录" --json"#,
                #"triton node resolve --platform ios --device booted --text "Settings" --json"#,
                "triton node resolve @1 --platform ios --device booted --json",
                #"triton node resolve --platform android --device android-a --text "Login" --all --json"#,
                #"triton node resolve --platform harmony --target 127.0.0.1:10100 --text "登录" --all --json"#,
            ],
            successShape: "{ ok, action, platform, query, matchIndex, matchCount, node, candidates?, sourceCommands[] }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|ambiguous_target|node_not_found|node_alias_not_found|stale_node_alias|hierarchy_unavailable|host_command_failed|validation_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use node resolve for current visible UI resolution across iOS runtime, iOS Simulator host AX, Android bridge/layout, or Harmony host layout. `node resolve @N` reads the repo-local alias cache written by `observe tree --outline`; stale aliases return stale_node_alias with a refresh command. Use debug node --oid for low-level hierarchy inspection.",
            nextCommands: [
                "triton status --json",
                "triton observe tree --outline --json",
                "triton act tap <query> --json",
            ],
            outputContracts: [nodeResolveOutputContract()],
            failureCodes: nodeFailureCodes,
            providedCapabilities: ["node", "node-resolve", "node-alias-resolve"]
        ),
        TKCommandSchema(
            name: "attrs",
            summary: "Fetch live attribute groups for a node layer oid",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                targetDeviceAlias,
                TKCommandSchemaOption(name: "--oid", type: "UInt", required: true, description: "Layer oid from `triton nodes`"),
                formatTextJSON,
                jsonAlias,
            ],
            examples: ["triton attrs --target triton:local --oid 2 --format json"],
            successShape: "[TKAttributesGroup]",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|node_not_found|request_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use attrs after nodes/node to inspect live attribute groups for a layer oid.",
            nextCommands: [
                "triton status --json",
                "triton object --oid <oid> --json",
                "triton node --oid <oid> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [nodeAttributesOutputContract()],
            failureCodes: nodeFailureCodes
        ),
        TKCommandSchema(
            name: "object",
            summary: "Fetch live object metadata for a view or layer oid",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--oid", type: "UInt", required: true, description: "View or layer oid from `triton nodes`"),
                formatTextJSON,
                jsonAlias,
            ],
            examples: ["triton object --target triton:local --oid 1 --format json"],
            successShape: "{ oid, memoryAddress, rawClassName, classChainList }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|node_not_found|request_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use object for live object metadata when hierarchy/node class information is insufficient.",
            nextCommands: [
                "triton status --json",
                "triton attrs --oid <oid> --json",
                "triton node --oid <oid> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [nodeObjectOutputContract()],
            failureCodes: nodeFailureCodes
        ),
        TKCommandSchema(
            name: "export",
            summary: "Export hierarchy JSON or self-contained archive",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: ["auto", "json", "archive"],
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--output", type: "Path", required: true, description: "Output file path"),
                TKCommandSchemaOption(name: "--format", type: "auto|json|archive", defaultValue: "auto", description: "Export format"),
                jsonAlias,
                TKCommandSchemaOption(name: "--refresh/--no-refresh", type: "Bool", defaultValue: "true", description: "Request fresh hierarchy before exporting"),
            ],
            examples: [
                "triton export --output /tmp/triton-hierarchy.json",
                "triton export --format archive --output /tmp/triton-smoke.triton",
            ],
            successShape: "File path on stdout; output file contains hierarchy JSON or TKExportArchive JSON",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|hierarchy_unavailable|artifact_write_failed|request_failed|validation_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use export for standalone hierarchy JSON or self-contained archive artifacts. Use evidence for full regression bundles.",
            artifacts: ["hierarchy-json", "export-archive"],
            nextCommands: [
                "triton status --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton evidence summary <dir.tritonevidence> --json",
                "triton replay --dry-run <path.tritonplan> --json",
            ],
            outputContracts: [hierarchyInfoOutputContract(), exportArchiveOutputContract()],
            failureCodes: hierarchyFailureCodes + ["artifact_write_failed"]
        ),
        TKCommandSchema(
            name: "evidence",
            summary: "Capture, inspect, summarize, redact, or project an agent-friendly regression evidence bundle",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "cli+embedded",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "inspect <path>", type: "Subcommand", description: "Read an existing bundle manifest without connecting to runtime"),
                TKCommandSchemaOption(name: "capture --case <case> --output <path>", type: "Subcommand", description: "Capture a runtime-backed evidence bundle under the product evidence surface"),
                TKCommandSchemaOption(name: "summary <path>", type: "Subcommand", description: "Print a safe high-level evidence summary without binary artifacts"),
                TKCommandSchemaOption(name: "redact <path> --output <path>", type: "Subcommand", description: "Write a redacted evidence bundle for safe handoff"),
                TKCommandSchemaOption(name: "project-workspace <path>", type: "Subcommand", description: "Offline project P0E observation.captured events into screens.json and transitions.json"),
                TKCommandSchemaOption(name: "project-screens <path>", type: "Subcommand", description: "Backward-compatible alias for project-workspace"),
                TKCommandSchemaOption(name: "ingest --file <path> --kind <artifact-kind>", type: "Subcommand", description: "Import a structured JSON artifact into an offline evidence bundle"),
                TKCommandSchemaOption(name: "<path>", type: "Path", description: "Evidence bundle path for inspect, summary, redact, project-workspace, or project-screens"),
                TKCommandSchemaOption(name: "--case", type: "String", description: "Regression case name stored in manifest for capture mode"),
                TKCommandSchemaOption(name: "--file", type: "Path", description: "Input JSON artifact path for evidence ingest"),
                TKCommandSchemaOption(name: "--kind", type: "String", description: "Artifact kind for evidence ingest, for example app.structured-evidence"),
                TKCommandSchemaOption(name: "--schema", type: "Path", description: "Optional JSON schema path hashed into artifact metadata"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Evidence bundle directory path; capture mode requires it"),
                TKCommandSchemaOption(name: "--include", type: "String", defaultValue: "status,list,version,hierarchy,ax,screenshot", description: "Comma-separated artifact kinds: status,list,version,hierarchy,ax,screenshot,geometry,archive,logs,host,xcode,real-device.diagnostics,host.app-action,runtime.snapshot,host.layout,build.summary,network.proxy-session"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Scenario name stored in manifest for ingest mode"),
                TKCommandSchemaOption(name: "--note", type: "String", description: "Human note stored in manifest"),
                TKCommandSchemaOption(name: "--xcode-summary", type: "Path", description: "Explicit TKXcodeActionSummary JSON to import when --include contains xcode"),
                TKCommandSchemaOption(name: "--proxy-session", type: "Path", description: "Explicit device proxy session directory to import when --include contains network.proxy-session"),
                TKCommandSchemaOption(name: "--profile", type: "String", defaultValue: "ios-private", description: "Redaction profile for summary/redact"),
                TKCommandSchemaOption(name: "--refresh/--no-refresh", type: "Bool", defaultValue: "true", description: "Request fresh hierarchy before hierarchy/archive capture"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton evidence capture --case login-home --output /tmp/login-home.tritonevidence --json",
                "triton evidence capture --case login-success --output /tmp/login-success.tritonevidence --json",
                "triton evidence capture --case <case> --include status,list,version,logs --output /tmp/partial.tritonevidence --json",
                "triton evidence capture --case <case> --include host,xcode --output /tmp/host-xcode.tritonevidence --json",
                "triton evidence capture --case <case> --include real-device.diagnostics,host.app-action,runtime.snapshot,host.layout,logs,build.summary --output /tmp/real-device.tritonevidence --json",
                "triton evidence capture --case <case> --include xcode --xcode-summary /tmp/xcode-summary.json --output /tmp/xcode.tritonevidence --json",
                "triton evidence capture --case <case> --include network.proxy-session --proxy-session /tmp/ios-network --output /tmp/network.tritonevidence --json",
                "triton evidence ingest --file /tmp/app-evidence.json --kind app.structured-evidence --schema /tmp/app-evidence.schema.json --output /tmp/app.tritonevidence --json",
                "triton evidence inspect /tmp/login-success.tritonevidence --json",
                "triton evidence summary /tmp/login-success.tritonevidence --json",
                "triton evidence project-workspace /tmp/login-success.tritonevidence --json",
                "triton evidence project-screens /tmp/login-success.tritonevidence --json",
                "triton evidence redact /tmp/login-success.tritonevidence --profile ios-private --output /tmp/login-redacted.tritonevidence --json",
            ],
            successShape: "TKEvidenceManifest, TKEvidenceSummaryResponse, TKEvidenceRedactionResponse, or TKScreenWorkspaceProjectionResponse",
            failureShape: "Validation failures use { ok:false, error:{ code, message, endpoint, hint, nextAction? } }; partial capture writes one TKEvidenceManifest with ok:false, partial:true, aggregate error, and skipped[].error before exiting non-zero",
            outputSemantics: "Use evidence after a failed or completed run to capture auditable artifacts. JSON mode emits exactly one document. Expected unsupported artifacts produce ok:true, partial:true; request/write failures produce ok:false, partial:true and a non-zero exit. Summaries, redaction, and screen projection are offline and do not require a runtime connection.",
            artifacts: ["evidence-bundle", "manifest", "screenshots", "logs", "host-artifacts", "xcode-artifacts", "real-device.diagnostics", "host.app-action", "runtime.snapshot", "host.layout", "build.summary", "network-capture", "proxy-restore", "app.structured-evidence", "screen-workspace", "screen-workspace.screens", "screen-workspace.transitions"],
            nextCommands: [
                "triton status --json",
                "triton verify text-exists <text> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton evidence summary <dir.tritonevidence> --json",
                "triton evidence project-workspace <dir.tritonevidence> --json",
                "triton evidence project-screens <dir.tritonevidence> --json",
                "triton map merge <dir.tritonevidence> --into <dir.tritonmap> --json",
                "triton evidence redact <dir.tritonevidence> --output <safe.tritonevidence> --json",
                "triton replay <path.tritonplan> --dry-run --json",
            ],
            outputContracts: [
                evidenceManifestOutputContract(),
                evidenceSummaryOutputContract(),
                evidenceRedactionOutputContract(),
                evidenceScreenWorkspaceProjectionOutputContract(),
            ],
            failureCodes: ["validation_failed", "missing_observation_events", "missing_run_events", "invalid_run_events", "evidence_capture_partial", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"],
            subcommands: [
                TKCommandSubcommandSchema(name: "capture", summary: "Capture a runtime-backed evidence bundle", requiredOptions: ["--output"], optionalOptions: ["--case", "--target", "--host", "--port", "--include", "--note", "--xcode-summary", "--proxy-session", "--refresh", "--no-refresh", "--format", "--json"], outputSelectors: ["evidence.manifest"], failureCodes: ["validation_failed", "evidence_capture_partial", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"]),
                TKCommandSubcommandSchema(name: "inspect", summary: "Read an existing bundle manifest", requiredOptions: ["<path>"], optionalOptions: ["--format", "--json"], outputSelectors: ["evidence.manifest"], failureCodes: ["validation_failed"]),
                TKCommandSubcommandSchema(name: "summary", summary: "Print a safe high-level evidence summary", requiredOptions: ["<path>"], optionalOptions: ["--profile", "--format", "--json"], outputSelectors: ["evidence.summary"], failureCodes: ["validation_failed"]),
                TKCommandSubcommandSchema(name: "redact", summary: "Write a redacted evidence bundle", requiredOptions: ["<path>", "--output"], optionalOptions: ["--profile", "--format", "--json"], outputSelectors: ["evidence.redact"], failureCodes: ["validation_failed"]),
                TKCommandSubcommandSchema(name: "project-workspace", summary: "Project evidence run observations into a screen workspace", requiredOptions: ["<path>"], optionalOptions: ["--format", "--json"], outputSelectors: ["evidence.screen-workspace-projection"], failureCodes: ["validation_failed", "missing_observation_events", "missing_run_events", "invalid_run_events"]),
                TKCommandSubcommandSchema(name: "project-screens", summary: "Backward-compatible alias for project-workspace", requiredOptions: ["<path>"], optionalOptions: ["--format", "--json"], outputSelectors: ["evidence.screen-workspace-projection"], failureCodes: ["validation_failed", "missing_observation_events", "missing_run_events", "invalid_run_events"]),
                TKCommandSubcommandSchema(name: "ingest", summary: "Import a structured JSON artifact into an offline evidence bundle", requiredOptions: ["--file", "--kind", "--output"], optionalOptions: ["--schema", "--name", "--note", "--format", "--json"], outputSelectors: ["evidence.manifest"], failureCodes: ["validation_failed"]),
            ],
            providedCapabilities: ["evidence", "evidence-summary", "evidence-redact", "evidence-project-screens", "evidence-ingest"]
        ),
        TKCommandSchema(
            name: "capture",
            summary: "Capture an agent-friendly regression evidence bundle",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "cli+embedded",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--case", type: "String", description: "Regression case name stored in manifest"),
                TKCommandSchemaOption(name: "--output", type: "Path", required: true, description: "Evidence bundle directory path"),
                TKCommandSchemaOption(name: "--include", type: "String", defaultValue: "status,list,version,hierarchy,ax,screenshot,geometry,archive", description: "Comma-separated artifact kinds: status,list,version,hierarchy,ax,screenshot,geometry,archive,logs,host,xcode,network.proxy-session"),
                TKCommandSchemaOption(name: "--note", type: "String", description: "Human note stored in manifest"),
                TKCommandSchemaOption(name: "--xcode-summary", type: "Path", description: "Explicit TKXcodeActionSummary JSON to import when --include contains xcode"),
                TKCommandSchemaOption(name: "--proxy-session", type: "Path", description: "Explicit device proxy session directory to import when --include contains network.proxy-session"),
                TKCommandSchemaOption(name: "--refresh/--no-refresh", type: "Bool", defaultValue: "true", description: "Request fresh hierarchy before hierarchy/archive capture"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton evidence capture --case job-search-area-filter --output /tmp/job-search-area-filter.tritonevidence --json",
                "triton capture --case job-search-area-filter --output /tmp/job-search-area-filter.tritonevidence --json",
                "triton capture --include network.proxy-session --proxy-session /tmp/android-network --output /tmp/network.tritonevidence --json",
            ],
            successShape: "TKEvidenceManifest with freshness metadata for captured artifacts",
            failureShape: "Validation failures use { ok:false, error:{ code, message, endpoint, hint, nextAction? } }; partial capture writes one TKEvidenceManifest with ok:false, partial:true, aggregate error, and skipped[].error before exiting non-zero",
            outputSemantics: "Use capture as the short evidence entrypoint for runtime-backed regression evidence bundles. JSON mode emits exactly one document; inspect ok, partial, error, and skipped[].error together.",
            artifacts: ["evidence-bundle", "manifest", "screenshots", "hierarchy", "ax", "geometry", "logs", "host-artifacts", "xcode-artifacts", "network-capture", "proxy-restore"],
            nextCommands: [
                "triton status --json",
                "triton evidence summary <dir.tritonevidence> --json",
                "triton evidence redact <dir.tritonevidence> --output <safe.tritonevidence> --json",
                "triton verify text-exists <text> --json",
            ],
            outputContracts: [evidenceManifestOutputContract()],
            failureCodes: ["validation_failed", "evidence_capture_partial", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"],
            providedCapabilities: ["capture", "evidence"]
        ),
        TKCommandSchema(
            name: "smoke",
            summary: "Run one-command smoke flows for real-project regression",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "cli",
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "ios", type: "Subcommand", description: "Run one-command iOS smoke evidence flow"),
                TKCommandSchemaOption(name: "android", type: "Subcommand", description: "Run one-command Android host-side smoke evidence flow"),
                TKCommandSchemaOption(name: "harmony", type: "Subcommand", description: "Run one-command Harmony host-side smoke evidence flow"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector: alias, sim:<udid>, harmony:<target>, raw id, booted, or current"),
                TKCommandSchemaOption(name: "--scope", type: "simulator|emulator|real|all", description: "Device scope filter; use real for host-visible physical devices"),
                TKCommandSchemaOption(name: "--simulator", type: "String", defaultValue: "booted", description: "Compatibility iOS simulator selector; cannot be combined with --device"),
                TKCommandSchemaOption(name: "--target", type: "String", description: "Runtime target id for iOS or raw HDC target id for Harmony; Harmony --target cannot be combined with --device"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Host target name filter"),
                TKCommandSchemaOption(name: "--runtime", type: "String", description: "Host target runtime filter"),
                TKCommandSchemaOption(name: "--state", type: "String", description: "Host target state filter"),
                TKCommandSchemaOption(name: "--ready", type: "Bool", defaultValue: "false", description: "Only match ready host targets"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for Android smoke"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for Harmony smoke"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "iOS bundle identifier"),
                TKCommandSchemaOption(name: "--package", type: "String", description: "Android package name"),
                TKCommandSchemaOption(name: "--activity", type: "String", description: "Optional Android activity name"),
                TKCommandSchemaOption(name: "--bundle", type: "String", description: "Harmony bundle name"),
                TKCommandSchemaOption(name: "--ability", type: "String", description: "Harmony ability name"),
                TKCommandSchemaOption(name: "--open-url", type: "URL", description: "Deep link URL to open"),
                TKCommandSchemaOption(name: "--wait-text", type: "String", description: "Visible text to wait for"),
                TKCommandSchemaOption(name: "--assert-text", type: "String", description: "Visible text to assert after iOS wait succeeds; defaults to --wait-text"),
                TKCommandSchemaOption(name: "--tap-text", type: "String", description: "Android or Harmony text to tap after first wait passes"),
                TKCommandSchemaOption(name: "--post-tap-wait-text", type: "String", description: "Android or Harmony text to wait for after tap"),
                TKCommandSchemaOption(name: "--screenshot", type: "Path", description: "Host screenshot output path"),
                TKCommandSchemaOption(name: "--evidence", type: "Path", description: "Evidence bundle output directory"),
                TKCommandSchemaOption(name: "--evidence-name", type: "String", description: "Name stored in evidence manifest"),
                TKCommandSchemaOption(name: "--evidence-note", type: "String", description: "Note stored in evidence manifest"),
                TKCommandSchemaOption(name: "--host", type: "String", defaultValue: "127.0.0.1", description: "Triton server host for iOS runtime checks"),
                TKCommandSchemaOption(name: "--port", type: "Int", defaultValue: "19421", description: "Triton server port for iOS runtime checks"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "20", description: "Wait timeout in seconds"),
                TKCommandSchemaOption(name: "--interval", type: "Double", defaultValue: "0.5", description: "Wait polling interval in seconds"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton smoke ios --device iphone15 --bundle-id com.example.app --open-url myapp://home --wait-text Ready --json",
                "triton smoke ios --device <ios-real-target> --scope real --bundle-id com.example.app --open-url myapp://home --wait-text Ready --json",
                "triton smoke ios --simulator booted --bundle-id com.example.app --open-url myapp://home --wait-text Ready --json",
                "triton smoke android --device android:emulator-5554 --package com.example.app --activity .MainActivity --wait-text Ready --screenshot /tmp/smoke.png --evidence /tmp/android.tritonevidence --json",
                "triton smoke android --device <android-real-target> --scope real --package com.example.app --activity .MainActivity --open-url example://home --wait-text Ready --evidence /tmp/android-real.tritonevidence --json",
                "triton smoke harmony --device <harmony-real-target> --scope real --bundle com.example.app --ability EntryAbility --open-url example://home --wait-text Ready --evidence /tmp/harmony-real.tritonevidence --json",
                "triton smoke harmony --device harmony-a --bundle com.example.app --ability EntryAbility --open-url example://home --wait-text Ready --screenshot /tmp/smoke.jpeg --evidence /tmp/harmony.tritonevidence --json",
                "triton smoke harmony --target 127.0.0.1:10100 --bundle com.example.app --ability EntryAbility --open-url example://home --wait-text Ready --screenshot /tmp/smoke.jpeg --evidence /tmp/harmony.tritonevidence --json",
            ],
            successShape: "SmokeRunSummary with { ok, action, platform, status, target, steps[], assertions[], artifacts[], evidence?, failure?, startedAt, endedAt, elapsedMs }",
            failureShape: "SmokeRunSummary with ok=false and failure.step/code/message/hint populated",
            outputSemantics: "Use smoke for one-command real-project regression only after target, app, and runtime assumptions are known. Host install/launch/open-url steps only prove action submission; business readiness must come from proofSource=runtime, host-layout, wait/assert, or evidence.",
            artifacts: ["evidence-bundle", "screenshot", "harmony-layout", "real-device.diagnostics", "host.app-action", "runtime.snapshot", "host.layout"],
            nextCommands: [
                "triton verify text-exists <text> --json",
                "triton evidence summary <dir.tritonevidence> --json",
                "triton evidence redact <dir.tritonevidence> --output <safe.tritonevidence> --json",
                "triton replay <path.tritonplan> --dry-run --json",
                "triton schema --command smoke --json",
            ],
            outputContracts: [smokeResultOutputContract()],
            failureCodes: [
                "smoke_failed",
                "runtime_not_connected",
                "smoke_step_failed",
                "target_not_found",
                "ambiguous_target",
                "target_offline",
                "device_not_ready",
                "debug_runtime_disabled",
                "android_target_unauthorized",
                "android_target_offline",
                "android_debugging_disabled",
                "harmony_target_unauthorized",
                "harmony_target_offline",
                "harmony_debugging_disabled",
                "app_info_not_available",
                "host_open_url_failed",
                "app_launch_failed",
                "text_not_found",
                "assertion_failed",
                "artifact_write_failed",
                "evidence_capture_failed",
                "validation_failed",
            ],
            providedCapabilities: ["smoke-ios", "smoke-android", "smoke-harmony"]
        ),
        TKCommandSchema(
            name: "assert",
            summary: "Assert visible UI text state for agent-driven regression",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                targetDeviceAlias,
                TKCommandSchemaOption(name: "<condition>", type: "text-exists|text-not-exists", required: true, description: "Assertion condition"),
                TKCommandSchemaOption(name: "<text>", type: "String", required: true, description: "Visible text, label, identifier, title, or value"),
                TKCommandSchemaOption(name: "--role", type: "String", description: "Optional AX role filter"),
                TKCommandSchemaOption(name: "--count", type: "Int", description: "Require exact match count"),
                TKCommandSchemaOption(name: "--min-count", type: "Int", description: "Require at least this many matches"),
                TKCommandSchemaOption(name: "--max-count", type: "Int", description: "Require at most this many matches"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict assertion to window bounds"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                #"triton assert text-exists "Macau" --json"#,
                #"triton assert text-not-exists "Qinghai" --within 180,120,190,500 --json"#,
                #"triton assert text-exists "Macau" --role text --count 1 --json"#,
            ],
            successShape: "{ ok, condition, query, role?, count, expectedCount?, minCount?, maxCount?, within?, matches[], sample[], targetConnectionState?, hierarchyCacheState?, message? }",
            failureShape: "Failed assertions return the same result with ok=false and exit non-zero; validation/request failures use { ok:false, error:{ code, message, endpoint?, hint } }",
            outputSemantics: "Use assert as the agent completion gate. Assertion failures return structured evidence hints and should normally be followed by evidence capture.",
            nextCommands: [
                "triton status --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton wait --text <text> --json",
                "triton act find <text> --all --json",
                "triton screenshot --output <path> --metadata",
            ],
            outputContracts: [assertResultOutputContract()],
            failureCodes: ["assertion_failed", "validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"],
            providedCapabilities: ["assert"]
        ),
        TKCommandSchema(
            name: "verify",
            summary: "Workflow-level verification surface for visible UI text conditions",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                targetDeviceAlias,
                TKCommandSchemaOption(name: "text-exists", type: "Subcommand", description: "Verify visible UI text exists"),
                TKCommandSchemaOption(name: "text-not-exists", type: "Subcommand", description: "Verify visible UI text does not exist"),
                TKCommandSchemaOption(name: "<text>", type: "String", required: true, description: "Visible text, label, identifier, title, or value"),
                TKCommandSchemaOption(name: "--role", type: "String", description: "Optional AX role filter"),
                TKCommandSchemaOption(name: "--count", type: "Int", description: "Require exact match count"),
                TKCommandSchemaOption(name: "--min-count", type: "Int", description: "Require at least this many matches"),
                TKCommandSchemaOption(name: "--max-count", type: "Int", description: "Require at most this many matches"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict verification to window bounds"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            usageForms: [
                TKCommandUsageForm(form: "text-exists <text> --json", kind: "Subcommand", description: "Pass when visible UI text exists"),
                TKCommandUsageForm(form: "text-not-exists <text> --json", kind: "Subcommand", description: "Pass when visible UI text is absent"),
            ],
            examples: [
                "triton verify text-exists 首页 --json",
                "triton verify text-not-exists 错误 --json",
                "triton verify text-exists 首页 --role text --count 1 --json",
            ],
            successShape: "{ ok, condition, query, role?, count, expectedCount?, minCount?, maxCount?, within?, matches[], sample[], targetConnectionState?, hierarchyCacheState?, message? }",
            failureShape: "Failed verifications return the same result with ok=false and exit non-zero; validation/request failures use { ok:false, error:{ code, message, endpoint?, hint } }",
            outputSemantics: "Use verify as the workflow completion gate. The old assert root remains as the implementation-compatible entry during P23 migration.",
            nextCommands: [
                "triton observe current --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton wait --text <text> --json",
                "triton act find <text> --all --json",
            ],
            outputContracts: [assertResultOutputContract()],
            failureCodes: ["assertion_failed", "validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "text-exists",
                    summary: "Verify visible UI text exists",
                    requiredOptions: ["<text>"],
                    optionalOptions: ["--target", "--device", "--host", "--port", "--role", "--count", "--min-count", "--max-count", "--within", "--format", "--json"],
                    outputSelectors: ["assert.result"],
                    failureCodes: ["assertion_failed", "validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "text-not-exists",
                    summary: "Verify visible UI text does not exist",
                    requiredOptions: ["<text>"],
                    optionalOptions: ["--target", "--device", "--host", "--port", "--role", "--count", "--min-count", "--max-count", "--within", "--format", "--json"],
                    outputSelectors: ["assert.result"],
                    failureCodes: ["assertion_failed", "validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"]
                ),
            ],
            providedCapabilities: ["verify", "verify-text-exists", "verify-text-not-exists"]
        ),
        TKCommandSchema(
            name: "record",
            summary: "Create an editable .tritonplan template. This is not interactive recording yet.",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "cli",
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "--output", type: "Path", required: true, description: "Output .tritonplan path"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Plan name; defaults to output basename"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton record --output login-flow.tritonplan --json",
            ],
            successShape: "{ ok, output, templateOnly, message, plan }",
            failureShape: "Validation/file failures use { ok:false, error:{ code, message, hint } }",
            outputSemantics: "Use record to create an editable .tritonplan template; it does not observe live user input yet.",
            artifacts: ["triton-plan"],
            nextCommands: [
                "triton plan inspect <path.tritonplan> --json",
                "triton replay <path.tritonplan> --dry-run --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton schema --command replay --json",
            ],
            outputContracts: [recordPlanOutputContract()],
            failureCodes: ["validation_failed", "file_write_failed"],
            providedCapabilities: ["record"]
        ),
        TKCommandSchema(
            name: "replay",
            summary: "Replay a .tritonplan smoke-test flow",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "cli+embedded",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "<path>", type: "Path", required: true, description: ".tritonplan file path"),
                TKCommandSchemaOption(name: "--dry-run", type: "Bool", defaultValue: "false", description: "Validate and print commands without connecting to runtime"),
                TKCommandSchemaOption(name: "--var", type: "String", description: "Variable assignment: key=value or key-env=ENV_NAME; repeatable"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton replay login-flow.tritonplan --dry-run --json",
                "triton replay login-flow.tritonplan --var username=alice --var password-env=TRITON_PASSWORD --json",
            ],
            successShape: "{ ok, dryRun, planName, stepCount, executedCount, failedStepIndex?, failureCode?, failureError?, failureWorkflowCategories[], failureRecoveryCategories[], failurePrimaryArtifacts[], recoveryCommands[]:{ command, category }, elapsedMs, steps[]:{ index, action, command, argv, category, requires, expectedArtifacts, stopConditions, failureCode?, error?, ... }, suggestedCommands[] }",
            failureShape: "Validation/request failures use { ok:false, error:{ code, message, hint } }; step failures return ok=false with failedStepIndex",
            outputSemantics: "Use replay --dry-run before executing. Real replay stops at the first failed step and returns failure workflow lanes, primary diagnostic artifacts, and suggested follow-up commands before broader re-planning.",
            nextCommands: [
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton plan inspect <path.tritonplan> --json",
                "triton schema --command replay --json",
            ],
            outputContracts: [replayResultOutputContract()],
            failureCodes: ["validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed", "step_failed", "action_failed", "timeout", "artifact_write_failed"],
            providedCapabilities: ["replay", "replay-dry-run"]
        ),
        TKCommandSchema(
            name: "find",
            summary: "Resolve a UI target by visible text, label, identifier, or option title",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                targetDeviceAlias,
                TKCommandSchemaOption(name: "<query>", type: "String", required: true, description: "Visible text, AX label, identifier, value, or option title to resolve"),
                TKCommandSchemaOption(name: "--all", type: "Bool", defaultValue: "false", description: "Include all candidates with stable 1-based indexes"),
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one candidate by 1-based index"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict matching to window bounds"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Restrict matching to candidate containing this window point"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                #"triton find "HTTP""#,
                #"triton find "HTTP" --device booted --json"#,
                #"triton find "hello" --all"#,
                #"triton find "hello" --at 240,580"#,
            ],
            successShape: "TapTargetResolution describing selected target; with --all includes candidates[]",
            outputSemantics: "Use find before tap when text may match multiple controls; pass --all for disambiguation candidates.",
            nextCommands: [
                "triton status --json",
                "triton wait --text <query> --json",
                "triton tap <query> --json",
                "triton tap <query> --index <n> --json",
                "triton screenshot --output <path> --metadata",
            ],
            outputContracts: [targetResolutionOutputContract()],
            failureCodes: ["text_not_found", "validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"]
        ),
        TKCommandSchema(
            name: "wait",
            summary: "Wait for text, disappearance, idle state, hierarchy change, or a safe predicate",
            requiresServer: false,
            requiresTarget: true,
            runtimeScope: "embedded|host-ios|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                targetDeviceAlias,
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Use iOS Simulator AX, Android UIAutomator, or Harmony layout polling instead of embedded runtime"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "Wait for visible text, AX label, identifier, title, or value"),
                TKCommandSchemaOption(name: "--gone", type: "String", description: "Wait for visible text, AX label, identifier, title, or value to disappear"),
                TKCommandSchemaOption(name: "--exists", type: "String", description: "Alias for --text; can be combined with --role"),
                TKCommandSchemaOption(name: "--role", type: "String", description: "Optional AX role filter for --text or --exists"),
                TKCommandSchemaOption(name: "--idle", type: "Bool", defaultValue: "false", description: "Wait until target is connected and hierarchy is stable across two polls"),
                TKCommandSchemaOption(name: "--hierarchy-change", type: "Bool", defaultValue: "false", description: "Wait until hierarchy snapshot changes"),
                TKCommandSchemaOption(name: "--since", type: "latest", defaultValue: "latest", description: "Hierarchy change baseline"),
                TKCommandSchemaOption(name: "--predicate", type: "String", description: #"Safe predicate, e.g. text.exists("console") && !text.exists("登录")"#),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "10", description: "Timeout in seconds"),
                TKCommandSchemaOption(name: "--interval", type: "Double", defaultValue: "0.5", description: "Polling interval in seconds"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                #"triton wait --text "console" --timeout 15 --interval 0.5 --json"#,
                #"triton wait --platform ios --device booted --text "Settings" --timeout 15 --json"#,
                #"triton wait --platform harmony --text "目标页" --timeout 15 --json"#,
                #"triton wait --gone "登录" --timeout 15 --json"#,
                #"triton wait --exists "我的" --role button --timeout 10 --json"#,
                "triton wait --idle --timeout 10 --json",
                "triton wait --hierarchy-change --since latest --timeout 10 --json",
                #"triton wait --predicate "text.exists(\"console\") && !text.exists(\"点我登录\")" --timeout 15 --json"#,
            ],
            successShape: "{ ok, matched, condition, query?, predicate?, elapsedMs, pollCount, timedOut, targetConnectionState, hierarchyCacheState, lastObservedNodeCount?, lastObservedTextSample, match? } or HostIOSWaitOutput or HostAndroidWaitOutput or HostHarmonyWaitOutput",
            failureShape: "Timeout: { ok:false, matched:false, timedOut:true, condition, elapsedMs, pollCount, match?, sourceCommands? }; Harmony host timeout may also include transientFailureCount and lastTransientError; validation/request failures use { ok:false, error:{ code, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use wait before assert or after action commands. Timeout returns a structured wait result instead of an untyped error. With --platform ios, wait polls the same Simulator host AX source as observe tree and does not require an embedded runtime. Harmony layout dump/recv timeouts are bounded by the remaining wait budget, retried as transient polls, and retained in lastTransientError.",
            nextCommands: [
                "triton status --json",
                "triton verify text-exists <text> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton act find <text> --all --json",
            ],
            outputContracts: [waitResultOutputContract(), hostIOSWaitOutputContract(), hostAndroidWaitOutputContract(), hostHarmonyWaitOutputContract()],
            failureCodes: ["timeout", "validation_failed", "unsupported_capability", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"] + schemaIOSHostAXFailureCodes,
            providedCapabilities: ["wait", "ios-simulator-host-wait", "android-wait-text", "harmony-wait-text"]
        ),
        TKCommandSchema(
            name: "ax",
            summary: "Read safe actionable control index",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-android|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "android|harmony", description: "Dump Android UIAutomator XML or Harmony host-side layout"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector: alias, android:<serial>, harmony:<target>, raw id, or current"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path for --platform android"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "text", description: "Output format"),
                jsonAlias,
                TKCommandSchemaOption(name: "--with-hierarchy", type: "Bool", defaultValue: "false", description: "Join AX nodes to hierarchy viewObject.oid and expose layer oid/path/frame"),
                TKCommandSchemaOption(name: "--refresh/--no-refresh", type: "Bool", defaultValue: "true", description: "Request fresh hierarchy before joining with --with-hierarchy"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Optional output file"),
            ],
            examples: [
                "triton ax --format json --output /tmp/ax.json",
                "triton ax --platform android --device android-a --output /tmp/android-window.xml --json",
                "triton ax --platform harmony --output /tmp/harmony-layout.json --json",
                "triton ax --with-hierarchy --json",
            ],
            successShape: "[TKAXNode] by default; TKAXHierarchyMapResponse when --with-hierarchy is used; HostAndroidArtifactOutput for --platform android; HostHarmonyArtifactOutput for --platform harmony",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|ambiguous_target|runtime_unavailable|request_failed|host_command_failed|artifact_write_failed|validation_failed, message, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton observe current --json",
                "triton screenshot --output <path> --metadata",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [axOutputContract(), hostAndroidArtifactOutputContract(selector: "host.android-ax"), hostHarmonyArtifactOutputContract()],
            failureCodes: [
                "server_unavailable",
                "target_unavailable",
                "target_not_found",
                "ambiguous_target",
                "runtime_unavailable",
                "request_failed",
                "host_command_failed",
                "artifact_write_failed",
                "validation_failed",
            ],
            providedCapabilities: ["ax", "android-ax", "harmony-ax"]
        ),
        TKCommandSchema(
            name: "geometry",
            summary: "Read current window geometry",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [targetDeviceAlias, formatTextJSON, jsonAlias],
            examples: ["triton geometry --format json"],
            successShape: "{ bounds, safeArea, scale, orientation }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|runtime_unavailable|request_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use geometry to understand coordinate systems before hit testing, point taps, or screenshot interpretation.",
            nextCommands: [
                "triton status --json",
                "triton hit --at <x,y> --json",
                "triton tap <query> --at <x,y> --json",
                "triton screenshot --output <path> --metadata",
            ],
            outputContracts: [geometryCurrentOutputContract()],
            failureCodes: runtimeTargetFailureCodes
        ),
        TKCommandSchema(
            name: "hit",
            summary: "Hit-test one window coordinate",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                targetDeviceAlias,
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Window point in points"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate in points; provide together with --y"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate in points; provide together with --x"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "text", description: "Output format"),
                jsonAlias,
            ],
            examples: ["triton hit --at 270,300 --format json", "triton hit --x 270 --y 300 --format json"],
            successShape: "{ x, y, centerX?, centerY?, node? }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|target_not_found|runtime_unavailable|validation_failed|request_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use hit to map a coordinate to an actionable node before point-based tap or failure diagnosis.",
            nextCommands: [
                "triton status --json",
                "triton tap <query> --at <x,y> --json",
                "triton node --oid <oid> --json",
                "triton geometry --json",
            ],
            outputContracts: [hitResultOutputContract()],
            failureCodes: runtimeTargetFailureCodes
        ),
        TKCommandSchema(
            name: "screenshot",
            summary: "Capture current app screenshot",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-device",
            outputFormats: ["file", "json-metadata"],
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Capture through iOS Simulator simctl, Android adb, or Harmony hdc; iOS real-device screenshot is unsupported"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector: alias, sim:<udid>, ios-real:<id>, android:<serial>, harmony:<target>, raw id, booted, or current; an iOS real-device selector returns unsupported_scope before any host tool runs"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Device name filter, for example iPhone 15"),
                TKCommandSchemaOption(name: "--runtime", type: "String", description: "Runtime filter, for example iOS 26.5"),
                TKCommandSchemaOption(name: "--state", type: "String", description: "Target state filter, for example booted or connected"),
                TKCommandSchemaOption(name: "--ready", type: "Bool", defaultValue: "false", description: "Only match ready host targets"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--output", type: "Path", required: true, description: "Output PNG path; embedded runtime metadata and PNG magic bytes are validated before atomic write"),
                TKCommandSchemaOption(name: "--metadata", type: "Bool", defaultValue: "false", description: "Print JSON metadata after writing"),
                metadataJSONAlias,
            ],
            examples: ["triton screenshot --output /tmp/triton.png --metadata", "triton screenshot --device iphone15 --output /tmp/sim.png --json", "triton screenshot --device harmony-a --output /tmp/smoke.jpeg --json"],
            successShape: "{ format, width, height, scale, output, bytes } when embedded runtime --metadata is used; HostDeviceArtifactOutput with bytes/width/height/sha256/capturedAt for --device/--platform",
            failureShape: "{ ok:false, error:{ code: unsupported_scope|server_unavailable|target_unavailable|target_not_found|ambiguous_target|artifact_write_failed|host_command_failed|validation_failed, message, hint, nextAction? }, candidates?[] }",
            outputSemantics: "Use screenshot as a visual artifact capture. Embedded runtime capture requires a .png output and validates metadata plus PNG magic bytes before atomic write; mismatches return artifact_write_failed without publishing a disguised artifact. Host-side iOS capture supports Simulator scope only; an explicit ios-real selector is resolved and then rejected as unsupported_scope before simctl. Prefer --metadata/--json and pair failures with evidence for audit.",
            artifacts: ["screenshot"],
            nextCommands: [
                "triton status --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton observe current --json",
                "triton verify text-exists <text> --json",
            ],
            outputContracts: [screenshotMetadataOutputContract(), hostArtifactOutputContract(), hostAndroidArtifactOutputContract(selector: "host.android-screenshot"), hostHarmonyArtifactOutputContract()],
            failureCodes: ["unsupported_scope", "server_unavailable", "target_unavailable", "target_not_found", "ambiguous_target", "artifact_write_failed", "host_command_failed", "validation_failed"],
            providedCapabilities: ["screenshot", "host-device-screenshot", "ios-screenshot", "ios-simulator-screenshot", "android-device-screenshot", "harmony-screenshot"]
        ),
    ]
}
