import Foundation
import TritonKitShared

func hostCommandSchemas() -> [TKCommandSchema] {
    let jsonText = schemaTextJSONFormats
    let jsonAlias = schemaJSONAliasOption

    return [
        TKCommandSchema(
            name: "device",
            summary: "Discover and inspect host-side platform devices",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-device",
            exitCodeOnFailure: 1,
            outputFormats: jsonText + ["jsonl"],
            options: [
                TKCommandSchemaOption(name: "doctor --platform ios|android|harmony", type: "Subcommand", description: "Probe platform host tool availability"),
                TKCommandSchemaOption(name: "bridge status --platform android --device <selector>", type: "Subcommand", description: "Return the Android strong-control bridge status probe ledger without mutating adb state"),
                TKCommandSchemaOption(name: "bridge probe --platform android --device <selector>", type: "Subcommand", description: "Return the Android bridge local HTTP /ping probe ledger"),
                TKCommandSchemaOption(name: "bridge install --platform android --device <selector> --apk <path.apk> --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Install the reviewed Android bridge APK once the bridge runner is implemented"),
                TKCommandSchemaOption(name: "bridge forward --platform android --device <selector> --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Forward the Android bridge local HTTP port once the bridge runner is implemented"),
                TKCommandSchemaOption(name: "proxy doctor --platform ios|android|harmony", type: "Subcommand", description: "Probe host-side proxy takeover prerequisites without touching app code"),
                TKCommandSchemaOption(name: "proxy cert doctor --platform ios|android|harmony", type: "Subcommand", description: "Inspect certificate trust boundaries for host-side proxy HTTPS visibility without changing trust settings"),
                TKCommandSchemaOption(name: "proxy cert plan --platform ios|android|harmony --device <selector> --certificate <path.cer>", type: "Subcommand", description: "Return a platform certificate trust setup ledger without installing or trusting the certificate"),
                TKCommandSchemaOption(name: "proxy cert install --platform ios|android|harmony --device <selector> --certificate <path.cer> --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Execute the reviewed iOS or Android certificate trust setup after break-glass confirmation; Harmony returns probe-only until a trust command is verified"),
                TKCommandSchemaOption(name: "proxy probe --platform ios|android|harmony --device <selector>", type: "Subcommand", description: "Run readonly platform proxy capability probes and return per-command probeResults plus structured probeFindings"),
                TKCommandSchemaOption(name: "proxy probe --platform ios|android|harmony --device <selector> --plan-only", type: "Subcommand", description: "Return readonly proxy capability probe ledger without running host tools"),
                TKCommandSchemaOption(name: "proxy serve --listen <host:port> --output <dir> --mode record|mock|block|throttle --jsonl", type: "Subcommand", description: "Run a local host-side capture, mock, block, or throttle proxy shared by iOS Simulator, Android Emulator, and Harmony emulator proxy plans"),
                TKCommandSchemaOption(name: "proxy serve --listen <host:port> --output <dir> --mode mock --mock-rules <path.json> --jsonl", type: "Subcommand", description: "Run a local host-side mock proxy with metadata-only request capture and file-backed response rules"),
                TKCommandSchemaOption(name: "proxy serve --listen <host:port> --output <dir> --mode record --policy-rules <path.json> --jsonl", type: "Subcommand", description: "Run a local host-side proxy with per-request forward, mock, block, or throttle policy rules"),
                TKCommandSchemaOption(name: "proxy serve --listen <host:port> --output <dir> --mode throttle --throttle-ms <ms> --jsonl", type: "Subcommand", description: "Run a local host-side throttle proxy with metadata-only capture and synthetic response delay evidence"),
                TKCommandSchemaOption(name: "proxy start --platform ios|android|harmony --device <selector> --mode record|mock|block|throttle --output <dir>", type: "Subcommand", description: "Declare a host-side proxy capture or policy session for a local simulator/emulator target"),
                TKCommandSchemaOption(name: "proxy start --platform ios|android|harmony --device <selector> --mode record|mock|block|throttle --output <dir> --plan-only", type: "Subcommand", description: "Return a platform host-command proxy takeover plan without changing host or emulator settings"),
                TKCommandSchemaOption(name: "proxy start --platform ios|android --device <selector> --mode record|mock|block|throttle --output <dir> --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Execute the break-glass iOS or Android proxy runner after plan review, confirmation, and audit metadata"),
                TKCommandSchemaOption(name: "proxy status --platform ios|android|harmony --device <selector>", type: "Subcommand", description: "Inspect the current host-side proxy takeover state with readonly platform probes for a local target"),
                TKCommandSchemaOption(name: "proxy status --platform ios|android|harmony --device <selector> --session <dir>", type: "Subcommand", description: "Inspect persisted host-side proxy takeover state produced by proxy start --output"),
                TKCommandSchemaOption(name: "proxy export --platform ios|android|harmony --device <selector> --output <path.har|path.ndjson>", type: "Subcommand", description: "Export captured network traffic from a host-side proxy session"),
                TKCommandSchemaOption(name: "proxy export --platform ios|android|harmony --device <selector> --session <dir> --output <path.har|path.ndjson>", type: "Subcommand", description: "Export captured network traffic from a persisted proxy session directory"),
                TKCommandSchemaOption(name: "proxy export --platform ios|android|harmony --device <selector> --output <path.har|path.ndjson> --plan-only", type: "Subcommand", description: "Return a network capture artifact plan without reading or writing capture files"),
                TKCommandSchemaOption(name: "proxy stop --platform ios|android|harmony --device <selector> --restore", type: "Subcommand", description: "Stop a host-side proxy session and restore simulator/emulator network settings"),
                TKCommandSchemaOption(name: "proxy stop --platform ios|android|harmony --device <selector> --restore --plan-only", type: "Subcommand", description: "Return a platform host-command restore plan without changing host or emulator settings"),
                TKCommandSchemaOption(name: "proxy stop --platform ios|android --device <selector> --restore-snapshot <path> --plan-only", type: "Subcommand", description: "Return the restore command ledger from a proxy start restore snapshot without changing host or emulator settings"),
                TKCommandSchemaOption(name: "proxy stop --platform ios|android --device <selector> --restore --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Execute the break-glass iOS or Android proxy restore runner after plan review, confirmation, and audit metadata"),
                TKCommandSchemaOption(name: "proxy stop --platform ios|android --device <selector> --restore-snapshot <path> --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Execute restore commands from a proxy start restore snapshot"),
                TKCommandSchemaOption(name: "list --platform ios|android|harmony", type: "Subcommand", description: "List iOS Simulator, Android Emulator/real devices, or Harmony HDC targets with the same envelope"),
                TKCommandSchemaOption(name: "list --platform ios|android|harmony --scope real", type: "Subcommand", description: "List only local real devices and return HostDeviceTarget.kind=real-device where supported"),
                TKCommandSchemaOption(name: "alias list", type: "Subcommand", description: "List stable host target aliases from .triton/host-targets.json"),
                TKCommandSchemaOption(name: "alias set <name> --platform ios|android|harmony --target <id>", type: "Subcommand", description: "Map a stable alias to an iOS UDID, Android adb serial, or Harmony HDC target"),
                TKCommandSchemaOption(name: "alias remove <name>", type: "Subcommand", description: "Remove a stable host target alias"),
                TKCommandSchemaOption(name: "use <selector>", type: "Subcommand", description: "Resolve a target selector and save it as the current agent target"),
                TKCommandSchemaOption(name: "current", type: "Subcommand", description: "Show the current agent target"),
                TKCommandSchemaOption(name: "resolve <selector>", type: "Subcommand", description: "Resolve a target selector without executing an action"),
                TKCommandSchemaOption(name: "resolve --platform ios|android|harmony --device <selector>", type: "Subcommand", description: "Resolve a unified target selector without executing an action"),
                TKCommandSchemaOption(name: "wait-ready --device <selector>", type: "Subcommand", description: "Wait for iOS Booted, Android adb state/package manager, or Harmony bootevent.boot.completed"),
                TKCommandSchemaOption(name: "screenshot --device <selector> --output <path>", type: "Subcommand", description: "Capture a host-side iOS, Android, or Harmony screenshot artifact"),
                TKCommandSchemaOption(name: "runtime-url --device <selector>", type: "Subcommand", description: "Prepare HDC fport and print a direct Harmony embedded runtime base URL"),
                TKCommandSchemaOption(name: "runtime-url --platform harmony --target <target>", type: "Subcommand", description: "Compatibility path for preparing a direct Harmony embedded runtime base URL"),
                TKCommandSchemaOption(name: "start --platform android --avd <name> --plan-only", type: "Subcommand", description: "Return an Android Emulator launch ledger without starting the emulator"),
                TKCommandSchemaOption(name: "start --platform harmony --hvd <name> --path <deployed-path> --plan-only", type: "Subcommand", description: "Return a DevEco Harmony Emulator launch ledger and HDC connection follow-up without starting the emulator"),
                TKCommandSchemaOption(name: "stop --platform android --device <selector> --confirm", type: "Subcommand", description: "Stop a selected Android Emulator through adb emu kill"),
                TKCommandSchemaOption(name: "stop --platform harmony --hvd <name> --path <deployed-path> --confirm", type: "Subcommand", description: "Unload Triton launchd supervision and stop a Harmony HVD"),
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", defaultValue: "harmony", description: "Host device platform adapter"),
                TKCommandSchemaOption(name: "--scope", type: "simulator|emulator|real|all", defaultValue: "all", description: "Device scope filter; Android real excludes emulator-* adb serials"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified target selector: alias, sim:<udid>, android:<serial>, harmony:<target>, raw id, booted, or current"),
                TKCommandSchemaOption(name: "--apk", type: "Path", description: "Android bridge APK path for device bridge install"),
                TKCommandSchemaOption(name: "--mode", type: "record|mock|block|throttle", description: "Host-side proxy takeover mode for network capture or policy enforcement; proxy serve currently supports record|mock|block|throttle"),
                TKCommandSchemaOption(name: "--mock-rules", type: "Path", description: "Optional JSON response rules for proxy serve --mode mock only; other modes reject this flag instead of ignoring it"),
                TKCommandSchemaOption(name: "--policy-rules", type: "Path", description: "Optional JSON per-request policy rules for proxy serve; matching emits policyRuleId and can forward, mock, block, or throttle without app integration"),
                TKCommandSchemaOption(name: "--throttle-ms", type: "Int", description: "Optional synthetic response delay in milliseconds for proxy serve --mode throttle; must be between 0 and 60000"),
                TKCommandSchemaOption(name: "--plan-only", type: "Bool", defaultValue: "false", description: "Return host command ledger for proxy takeover without changing host or emulator settings"),
                TKCommandSchemaOption(name: "--proxy", type: "host:port", defaultValue: "127.0.0.1:19431", description: "Host-side proxy endpoint; Android Emulator loopback hosts are rewritten to the emulator host gateway in sourceCommands"),
                TKCommandSchemaOption(name: "--listen", type: "host:port", defaultValue: "127.0.0.1:19431", description: "Host-side capture proxy listen endpoint for proxy serve"),
                TKCommandSchemaOption(name: "--certificate", type: "Path", description: "Root certificate path for proxy cert plan or explicitly confirmed proxy cert install"),
                TKCommandSchemaOption(name: "--audit-record", type: "String", description: "Audit record id required with --confirm before break-glass proxy mutation can proceed"),
                TKCommandSchemaOption(name: "--execute-runner", type: "Bool", defaultValue: "false", description: "Required with --confirm and --audit-record before iOS or Android break-glass proxy mutation can call host tools"),
                TKCommandSchemaOption(name: "--session", type: "Path", description: "Proxy session directory produced by proxy start --output"),
                TKCommandSchemaOption(name: "--restore-snapshot", type: "Path", description: "Restore snapshot path produced by proxy start"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Device name filter, for example iPhone 15"),
                TKCommandSchemaOption(name: "--runtime", type: "String", description: "Runtime filter, for example iOS 26.5"),
                TKCommandSchemaOption(name: "--state", type: "String", description: "Target state filter, for example booted or connected"),
                TKCommandSchemaOption(name: "--ready", type: "Bool", defaultValue: "false", description: "Only match ready host targets"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "ADB executable path"),
                TKCommandSchemaOption(name: "--target", type: "String", description: "Compatibility target option: simulator UDID or Harmony target, for example 127.0.0.1:10100"),
                TKCommandSchemaOption(name: "--avd", type: "String", description: "Android AVD name for device start"),
                TKCommandSchemaOption(name: "--hvd", type: "String", description: "Harmony HVD name for device stop"),
                TKCommandSchemaOption(name: "--path", type: "Path", description: "DevEco deployed emulator path for device stop"),
                TKCommandSchemaOption(name: "--emulator", type: "Path", defaultValue: "emulator|/Applications/DevEco-Studio.app/Contents/tools/emulator/Emulator", description: "Android emulator or DevEco Emulator executable for device start/stop"),
                TKCommandSchemaOption(name: "--adb-serial", type: "String", defaultValue: "emulator-5554", description: "Expected Android adb serial after first emulator launch"),
                TKCommandSchemaOption(name: "--headless", type: "Bool", defaultValue: "false", description: "Start Android emulator with -no-window"),
                TKCommandSchemaOption(name: "--gpu", type: "String", description: "Android emulator GPU mode such as swiftshader_indirect"),
                TKCommandSchemaOption(name: "--memory", type: "Int", description: "Android emulator memory in MB"),
                TKCommandSchemaOption(name: "--no-snapshot-load", type: "Bool", defaultValue: "false", description: "Start Android emulator without loading a snapshot"),
                TKCommandSchemaOption(name: "--no-audio", type: "Bool", defaultValue: "false", description: "Start Android emulator without audio"),
                TKCommandSchemaOption(name: "--no-boot-anim", type: "Bool", defaultValue: "false", description: "Start Android emulator without boot animation"),
                TKCommandSchemaOption(name: "--hdc-port", type: "Int", defaultValue: "10100", description: "Harmony HDC bridge port for DevEco Emulator start"),
                TKCommandSchemaOption(name: "--bootmode", type: "String", defaultValue: "coldboot", description: "Harmony DevEco Emulator boot mode"),
                TKCommandSchemaOption(name: "--connect-after-launch", type: "Bool", defaultValue: "true", description: "Include Harmony hdc tconn follow-up command in sourceCommands"),
                TKCommandSchemaOption(name: "--stdout-log", type: "Path", description: "Optional stdout log file for detached device start"),
                TKCommandSchemaOption(name: "--stderr-log", type: "Path", description: "Optional stderr log file for detached device start"),
                TKCommandSchemaOption(name: "--launchd-label", type: "String", defaultValue: "triton-harmony-emulator", description: "Triton launchd job label to unload before Harmony stop"),
                TKCommandSchemaOption(name: "--launchd-domain", type: "String", defaultValue: "gui/<uid>", description: "launchd domain for the Triton Harmony emulator job"),
                TKCommandSchemaOption(name: "--skip-launchd", type: "Bool", defaultValue: "false", description: "Only run Emulator -stop without launchd print/bootout"),
                TKCommandSchemaOption(name: "--confirm", type: "Bool", defaultValue: "false", description: "Required for Harmony device stop and break-glass proxy runner execution"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Screenshot output path for device screenshot"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "30", description: "Bounded wait or host command timeout in seconds"),
                TKCommandSchemaOption(name: "--local-port", type: "Int", description: "Local TCP port used by bridge or runtime-url commands"),
                TKCommandSchemaOption(name: "--remote-port", type: "Int", description: "Remote TCP port used by bridge or runtime-url commands"),
                TKCommandSchemaOption(name: "--no-forward", type: "Bool", defaultValue: "false", description: "Skip HDC fport setup and only print the local URL"),
                TKCommandSchemaOption(name: "--probe-manifest", type: "Bool", defaultValue: "false", description: "Probe /v2/runtime/manifest after preparing the URL"),
                TKCommandSchemaOption(name: "--restore", type: "Bool", defaultValue: "false", description: "Restore platform proxy settings when stopping a host-side proxy session"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                TKCommandSchemaOption(name: "--jsonl", type: "Bool", defaultValue: "false", description: "Emit JSON Lines ready/request/final events for long-running proxy serve"),
                jsonAlias,
            ],
            examples: [
                "triton device doctor --platform ios --json",
                "triton device list --platform ios --json",
                "triton device alias set iphone15 --platform ios --target 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --json",
                "triton device bridge status --platform android --device emulator-5554 --json",
                "triton device bridge probe --platform android --device emulator-5554 --json",
                "triton device bridge install --platform android --device emulator-5554 --apk /tmp/triton-bridge.apk --confirm --audit-record ticket-123 --execute-runner --json",
                "triton device bridge forward --platform android --device emulator-5554 --confirm --audit-record ticket-123 --execute-runner --json",
                "triton device proxy doctor --platform ios --json",
                "triton device proxy cert doctor --platform ios --json",
                "triton device proxy cert plan --platform android --device emulator-5554 --certificate /tmp/triton-proxy-ca.cer --json",
                "triton device proxy cert install --platform ios --device booted --certificate /tmp/triton-proxy-ca.cer --confirm --audit-record ticket-123 --execute-runner --json",
                "triton device proxy cert install --platform harmony --device harmony-a --certificate /tmp/triton-proxy-ca.cer --confirm --audit-record ticket-123 --execute-runner --json",
                "triton device proxy probe --platform harmony --device harmony-a --json",
                "triton device proxy probe --platform harmony --device harmony-a --plan-only --json",
                "triton device proxy serve --listen 127.0.0.1:19431 --output /tmp/triton-network --mode record --jsonl",
                "triton device proxy serve --listen 127.0.0.1:19431 --output /tmp/triton-network-mock --mode mock --jsonl",
                "triton device proxy serve --listen 127.0.0.1:19431 --output /tmp/triton-network-mock --mode mock --mock-rules /tmp/triton-mock-rules.json --jsonl",
                "triton device proxy serve --listen 127.0.0.1:19431 --output /tmp/triton-network-policy --mode record --policy-rules /tmp/triton-policy-rules.json --jsonl",
                "triton device proxy serve --listen 127.0.0.1:19431 --output /tmp/triton-network-block --mode block --jsonl",
                "triton device proxy serve --listen 127.0.0.1:19431 --output /tmp/triton-network-throttle --mode throttle --jsonl",
                "triton device proxy serve --listen 127.0.0.1:19431 --output /tmp/triton-network-throttle --mode throttle --throttle-ms 250 --jsonl",
                "triton device proxy export --platform ios --device iphone15 --output /tmp/network.har --json",
                "triton device proxy export --platform android --device emulator-5554 --session /tmp/android-network --output /tmp/network.ndjson --json",
                "triton device proxy export --platform ios --device booted --output /tmp/network.ndjson --plan-only --json",
                "triton device proxy stop --platform ios --device iphone15 --restore --json",
                "triton device proxy stop --platform ios --device booted --restore --plan-only --json",
                "triton device proxy stop --platform android --device emulator-5554 --restore-snapshot /tmp/android-network/restore-state.json --confirm --audit-record ticket-123 --execute-runner --json",
                "triton device proxy start --platform ios --device booted --mode record --output /tmp/ios-network --confirm --audit-record ticket-123 --execute-runner --json",
                "triton device use iphone15 --json",
                "triton device current --json",
                "triton device resolve --platform ios --name 'iPhone 15' --ready --json",
                "triton device wait-ready --device iphone15 --json",
                "triton device screenshot --device iphone15 --output /tmp/sim.png --timeout 180 --json",
                "triton device doctor --platform android --json",
                "triton device list --platform android --json",
                "triton device list --platform android --scope real --json",
                "triton device start --platform android --avd Dxyer_API_34 --headless --gpu swiftshader_indirect --plan-only --json",
                "triton device stop --platform android --device emulator-5554 --confirm --json",
                "triton device resolve --platform android --device android-a --ready --json",
                "triton device alias set android-a --platform android --target emulator-5554 --json",
                "triton device proxy start --platform android --device android-a --mode record --output /tmp/android-network --json",
                "triton device proxy start --platform android --device emulator-5554 --mode record --output /tmp/android-network --plan-only --json",
                "triton device wait-ready --platform android --scope real --device <android-real-target> --json",
                "triton device wait-ready --device android-a --json",
                "triton device screenshot --device android-a --output /tmp/android.png --json",
                "triton device doctor --platform harmony --json",
                "triton device list --platform harmony --json",
                "triton device start --platform harmony --hvd 'Codex Test Phone' --path ~/.Huawei/Emulator/deployed --hdc-port 10100 --plan-only --json",
                "triton device alias set harmony-a --platform harmony --target 127.0.0.1:10100 --json",
                "triton device proxy status --platform harmony --device harmony-a --json",
                "triton device wait-ready --device harmony-a --json",
                "triton device screenshot --device harmony-a --output /tmp/smoke.jpeg --json",
                "triton device runtime-url --device harmony-a --probe-manifest --json",
                "triton device runtime-url --platform harmony --target 127.0.0.1:10100 --probe-manifest --json",
                "triton device stop --platform harmony --hvd 'Codex Test Phone' --path ~/.Huawei/Emulator/deployed --confirm --json",
            ],
            successShape: "{ ok, platform, tools[]?, strongControl[]?, bridge?, targets[]?, defaultTarget?, target?, defaultsPath?, ready?, artifact?, baseURL?, manifest?, hvd?, launchdLabel?, launchdDomain?, planOnly?, started?, pid?, nextAction?, sourceCommand?, sourceCommands?[] }",
            failureShape: "{ ok:false, error:{ code: ambiguous_target|target_offline|device_not_ready|simulator_not_booted|emulator_license_agreement_required|harmony_emulator_stop_failed|host_action_failed, message, hint, nextAction? } }",
            outputSemantics: "Use device as the host target fact source before simulator, Harmony, app, screenshot, or smoke actions. Prefer aliases and current target to avoid repeated disambiguation.",
            jsonlEvents: [
                "proxy.serve.ready",
                "proxy.serve.request",
                "proxy.serve.connection-failed",
                "proxy.serve.summary",
            ],
            finalEventKind: "proxy.serve.summary",
            nextCommands: [
                "triton device resolve --device <selector> --json",
                "triton device use <selector> --json",
                "triton device wait-ready --device <selector> --json",
                "triton device proxy doctor --platform <platform> --json",
                "triton device proxy cert doctor --platform <platform> --json",
                "triton device proxy serve --listen 127.0.0.1:19431 --output <dir> --jsonl",
                "triton doctor --format json",
                "triton app launch --device <selector> --json",
            ],
            outputContracts: [
                hostDeviceListOutputContract(),
                hostDeviceListOutputContract(selector: "host.android-device"),
                hostDeviceSelectionOutputContract(),
                hostDeviceReadyOutputContract(),
                hostDeviceBridgeOutputContract(),
                hostDeviceProxyOutputContract(),
                hostDeviceProxyServeOutputContract(),
                hostArtifactOutputContract(),
                runtimeManifestOutputContract(),
            ],
            failureCodes: [
                "ambiguous_target",
                "target_not_found",
                "target_offline",
                "target_platform_mismatch",
                "parameter_conflict",
                "device_not_ready",
                "simulator_not_booted",
                "device_locked",
                "debug_runtime_disabled",
                "runtime_not_connected",
                "host_command_timeout",
                "host_action_failed",
                "emulator_license_agreement_required",
                "harmony_emulator_stop_failed",
                "unsupported_host_action",
                "unsupported_capability",
                "devicectl_not_found",
                "devicectl_json_missing",
                "devicectl_json_parse_failed",
                "device_not_trusted",
                "developer_mode_required",
                "ddi_missing",
                "xcode_signing_failed",
                "provisioning_profile_missing",
                "android_adb_not_found",
                "android_target_offline",
                "android_target_unauthorized",
                "android_debugging_disabled",
                "android_package_manager_unavailable",
                "android_app_install_failed",
                "android_activity_resolve_failed",
                "android_screenshot_failed",
                "android_bridge_not_installed",
                "android_bridge_auth_token_missing",
                "android_bridge_runner_not_configured",
                "android_bridge_install_failed",
                "android_bridge_forward_failed",
                "android_bridge_probe_failed",
                "proxy_visibility_limited",
                "proxy_cert_untrusted",
                "proxy_platform_not_supported",
                "proxy_real_device_not_supported",
                "proxy_runner_not_configured",
                "proxy_unverified_platform_proxy",
                "destructive_action_requires_policy",
                "proxy_endpoint_unreachable",
                "proxy_probe_failed",
                "proxy_status_probe_failed",
                "proxy_cert_install_failed",
                "proxy_start_failed",
                "proxy_restore_failed",
                "proxy_artifact_write_failed",
                "harmony_hdc_not_found",
                "harmony_discovery_timeout",
                "harmony_target_unauthorized",
                "harmony_target_offline",
                "harmony_debugging_disabled",
                "harmony_shell_unavailable",
                "harmony_app_install_failed",
                "harmony_ability_launch_failed",
                "harmony_screenshot_failed",
                "validation_failed",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "doctor",
                    summary: "Probe platform host tool availability",
                    optionalOptions: ["--platform", "--scope", "--hdc", "--adb", "--format", "--json"],
                    outputSelectors: ["host.device-doctor"]
                ),
                TKCommandSubcommandSchema(
                    name: "list",
                    summary: "List iOS Simulator, Android, or Harmony host targets",
                    optionalOptions: ["--platform", "--scope", "--name", "--runtime", "--state", "--ready", "--hdc", "--adb", "--format", "--json"],
                    outputSelectors: ["host.device-list"]
                ),
                TKCommandSubcommandSchema(
                    name: "use",
                    summary: "Resolve a target selector and save it as the current agent target",
                    requiredOptions: ["<selector>"],
                    optionalOptions: ["--platform", "--scope", "--name", "--runtime", "--state", "--ready", "--target", "--hdc", "--adb", "--format", "--json"],
                    outputSelectors: ["host.device-selection"]
                ),
                TKCommandSubcommandSchema(
                    name: "current",
                    summary: "Show the current agent target",
                    optionalOptions: ["--hdc", "--adb", "--format", "--json"],
                    outputSelectors: ["host.device-selection"]
                ),
                TKCommandSubcommandSchema(
                    name: "resolve",
                    summary: "Resolve a target selector without executing an action",
                    optionalOptions: ["<selector>", "--device", "--platform", "--scope", "--name", "--runtime", "--state", "--ready", "--hdc", "--adb", "--format", "--json"],
                    outputSelectors: ["host.device-selection"]
                ),
                TKCommandSubcommandSchema(
                    name: "wait-ready",
                    summary: "Wait for a host target to become ready",
                    optionalOptions: ["<selector>", "--device", "--target", "--platform", "--scope", "--name", "--runtime", "--state", "--ready", "--timeout", "--interval", "--hdc", "--adb", "--format", "--json"],
                    outputSelectors: ["host.device-ready"]
                ),
                TKCommandSubcommandSchema(
                    name: "screenshot",
                    summary: "Capture a host-side iOS, Android, or Harmony screenshot artifact",
                    requiredOptions: ["--output"],
                    optionalOptions: ["--platform", "--device", "--target", "--scope", "--name", "--runtime", "--state", "--ready", "--timeout", "--hdc", "--adb", "--format", "--json"],
                    outputSelectors: ["host.device-screenshot"]
                ),
                TKCommandSubcommandSchema(
                    name: "runtime-url",
                    summary: "Prepare and print a Harmony embedded runtime base URL",
                    optionalOptions: ["--platform", "--device", "--target", "--scope", "--name", "--runtime", "--state", "--ready", "--local-port", "--remote-port", "--no-forward", "--probe-manifest", "--timeout", "--hdc", "--format", "--json"],
                    outputSelectors: ["host.harmony-runtime-url"]
                ),
            ],
            providedCapabilities: ["host-device", "host-device-selector", "device-alias", "device-list", "device-use", "device-current", "device-resolve", "device-wait-ready", "device-screenshot", "ios-device", "ios-host-ax", "ios-host-hid", "android-device", "android-device-doctor", "android-device-list", "android-device-start", "android-device-stop", "android-device-wait-ready", "android-device-screenshot", "android-bridge", "android-bridge-install", "android-bridge-forward", "harmony-device", "harmony-device-list", "harmony-device-start", "harmony-foreground-app-identity", "harmony-runtime-url", "harmony-device-stop", "device-proxy-ios", "device-proxy-android", "device-proxy-harmony", "network-capture-export", "network-certificate-plan", "network-certificate-install"]
        ),
        TKCommandSchema(
            name: "camera",
            summary: "Configure iOS Simulator camera injection for selected apps",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-simulator",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "on --bundle-id <id>", type: "Subcommand", description: "Enable Triton simulator camera hook injection for one iOS Simulator bundle"),
                TKCommandSchemaOption(name: "off --bundle-id <id>", type: "Subcommand", description: "Disable Triton simulator camera hook injection for one iOS Simulator bundle"),
                TKCommandSchemaOption(name: "status", type: "Subcommand", description: "Show current workspace simulator camera injection config"),
                TKCommandSchemaOption(name: "build-hook", type: "Subcommand", description: "Build the bundled Triton simulator camera hook dylib into the workspace"),
                TKCommandSchemaOption(name: "serve", type: "Subcommand", description: "Serve BGRA frames over the Triton simulator camera Unix socket"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "iOS app bundle identifier to enable or disable"),
                TKCommandSchemaOption(name: "--hook", type: "Path", description: "Path to libTritonSimCameraHook.dylib; defaults to .triton/sim-camera/libTritonSimCameraHook.dylib built from TritonKit resources"),
                TKCommandSchemaOption(name: "--socket", type: "Path", defaultValue: SimCameraConfigStore.defaultSocketPath, description: "Unix socket used by the Triton simulator camera frame server"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "build-hook output dylib path"),
                TKCommandSchemaOption(name: "--source", type: "Path", description: "build-hook source override; defaults to bundled resources"),
                TKCommandSchemaOption(name: "--width", type: "Int", defaultValue: "1280", description: "serve frame width"),
                TKCommandSchemaOption(name: "--height", type: "Int", defaultValue: "720", description: "serve frame height"),
                TKCommandSchemaOption(name: "--fps", type: "Double", defaultValue: "15", description: "serve frame rate"),
                TKCommandSchemaOption(name: "--max-frames", type: "Int", description: "serve stop condition for tests or bounded captures"),
                TKCommandSchemaOption(name: "--once", type: "Flag", description: "serve exits after the first client disconnects"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            examples: [
                "triton camera build-hook --json",
                "triton camera serve --socket /tmp/tritonkit-sim-camera.sock --json",
                "triton camera on --bundle-id com.example.app --json",
                "triton app launch --bundle-id com.example.app --json",
                "triton camera off --bundle-id com.example.app --json",
                "triton camera status --json",
            ],
            successShape: "{ ok, action, configPath, provider, hookPath, socketPath, enabledBundles[], note }",
            failureShape: "{ ok:false, error:{ code, message, hint, nextAction? } }",
            outputSemantics: "Camera config is a per-workspace allowlist. `build-hook` builds the bundled hook into the workspace; `serve` emits JSONL frame-server events and streams BGRA frames over a Unix socket. Injection is applied only when `triton app launch` starts an enabled iOS Simulator bundle; real devices, Android, and Harmony are not affected.",
            artifacts: [],
            nextCommands: ["triton app launch --bundle-id <id> --json"],
            failureCodes: ["validation_failed"]
        ),
        TKCommandSchema(
            name: "sim",
            summary: "Control simulators through host-side Apple tools",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-simulator",
            exitCodeOnFailure: 1,
            outputFormats: jsonText + ["jsonl"],
            options: [
                TKCommandSchemaOption(name: "list", type: "Subcommand", description: "List available simulators"),
                TKCommandSchemaOption(name: "use <udid>", type: "Subcommand", description: "Set workspace default simulator in .triton/host-defaults.json"),
                TKCommandSchemaOption(name: "create <name> --device-type <id> --runtime <id>", type: "Subcommand", description: "Create a simulator with schema-backed simctl create"),
                TKCommandSchemaOption(name: "boot <udid>", type: "Subcommand", description: "Boot a simulator"),
                TKCommandSchemaOption(name: "--device-type", type: "String", description: "CoreSimulator device type identifier for sim create"),
                TKCommandSchemaOption(name: "--runtime", type: "String", description: "CoreSimulator runtime identifier for sim create"),
                TKCommandSchemaOption(name: "--wait", type: "Bool", defaultValue: "false", description: "Wait until booted"),
                TKCommandSchemaOption(name: "--jsonl", type: "Bool", defaultValue: "false", description: "Emit JSON Lines progress with --wait"),
                TKCommandSchemaOption(name: "shutdown <udid|booted>", type: "Subcommand", description: "Shutdown a simulator"),
                TKCommandSchemaOption(name: "screenshot --output <path>", type: "Subcommand", description: "Capture simulator framebuffer screenshot"),
                TKCommandSchemaOption(name: "type --text <ascii-text>", type: "Subcommand", description: "Reserved host-side simulator text entry; currently returns unsupported_host_input after ASCII validation"),
                TKCommandSchemaOption(name: "record --output <path.mov> --duration <seconds>", type: "Subcommand", description: "Record a simulator video"),
                TKCommandSchemaOption(name: "logs --output <path.log> --duration <seconds>", type: "Subcommand", description: "Capture bounded simulator OSLog stream output"),
                TKCommandSchemaOption(name: "diagnose [--output <path>]", type: "Subcommand", description: "Collect simulator diagnostics and logs"),
                TKCommandSchemaOption(name: "logverbose [--simulator <udid>] enable|disable", type: "Subcommand", description: "Enable or disable verbose simulator logging"),
                TKCommandSchemaOption(name: "ax --device <udid|booted>", type: "Subcommand", description: "Read host-side iOS Simulator Accessibility tree through private framework adapter"),
                TKCommandSchemaOption(name: "proxy", type: "Subcommand", description: "iOS Simulator host-side proxy takeover commands"),
                TKCommandSchemaOption(name: "proxy doctor", type: "Subcommand", description: "Probe iOS Simulator host-side proxy takeover prerequisites"),
                TKCommandSchemaOption(name: "proxy start --simulator <udid|booted> --mode record|mock|block|throttle --output <dir>", type: "Subcommand", description: "Alias to device proxy start --platform ios for host-side Simulator network takeover"),
                TKCommandSchemaOption(name: "proxy start --simulator <udid|booted> --mode record|mock|block|throttle --output <dir> --plan-only", type: "Subcommand", description: "Return iOS Simulator host-command proxy takeover plan without changing host settings"),
                TKCommandSchemaOption(name: "proxy start --simulator <udid|booted> --mode record|mock|block|throttle --output <dir> --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Execute iOS Simulator break-glass proxy runner after plan review, confirmation, and audit metadata"),
                TKCommandSchemaOption(name: "proxy status --simulator <udid|booted>", type: "Subcommand", description: "Alias to readonly device proxy status --platform ios for host-side Simulator network takeover"),
                TKCommandSchemaOption(name: "proxy status --simulator <udid|booted> --session <dir>", type: "Subcommand", description: "Inspect persisted iOS Simulator proxy session state"),
                TKCommandSchemaOption(name: "proxy export --simulator <udid|booted> --output <path.har|path.ndjson>", type: "Subcommand", description: "Alias to device proxy export --platform ios for host-side Simulator network capture artifacts"),
                TKCommandSchemaOption(name: "proxy export --simulator <udid|booted> --session <dir> --output <path.har|path.ndjson>", type: "Subcommand", description: "Export captured network traffic from a persisted iOS Simulator proxy session directory"),
                TKCommandSchemaOption(name: "proxy export --simulator <udid|booted> --output <path.har|path.ndjson> --plan-only", type: "Subcommand", description: "Return iOS Simulator network capture artifact plan without reading or writing capture files"),
                TKCommandSchemaOption(name: "proxy stop --simulator <udid|booted> --restore", type: "Subcommand", description: "Alias to device proxy stop --platform ios and restore simulator proxy settings"),
                TKCommandSchemaOption(name: "proxy stop --simulator <udid|booted> --restore --plan-only", type: "Subcommand", description: "Return iOS Simulator restore command plan without changing host settings"),
                TKCommandSchemaOption(name: "proxy stop --simulator <udid|booted> --restore-snapshot <path> --plan-only", type: "Subcommand", description: "Return iOS Simulator restore command ledger from a proxy start restore snapshot without changing host settings"),
                TKCommandSchemaOption(name: "proxy stop --simulator <udid|booted> --restore --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Execute iOS Simulator break-glass proxy restore runner after plan review, confirmation, and audit metadata"),
                TKCommandSchemaOption(name: "proxy stop --simulator <udid|booted> --restore-snapshot <path> --confirm --audit-record <id> --execute-runner", type: "Subcommand", description: "Execute iOS Simulator restore commands from a proxy start restore snapshot"),
                TKCommandSchemaOption(name: "pair <watch-device> <phone-device>", type: "Subcommand", description: "Create a watch and phone simulator pair"),
                TKCommandSchemaOption(name: "unpair <pair-uuid>", type: "Subcommand", description: "Unpair a watch and phone simulator pair"),
                TKCommandSchemaOption(name: "clone <device> <new-name> [destination-device-set]", type: "Subcommand", description: "Clone an existing simulator device"),
                TKCommandSchemaOption(name: "erase <device> --confirm", type: "Subcommand", description: "Erase simulator contents and settings with an explicit break-glass acknowledgement"),
                TKCommandSchemaOption(name: "upgrade <device> <runtime-id>", type: "Subcommand", description: "Upgrade a simulator to a newer runtime"),
                TKCommandSchemaOption(name: "runtime list|verify|add|delete|unmount|scan-and-mount", type: "Subcommand", description: "Inspect and maintain installed simulator runtimes"),
                TKCommandSchemaOption(name: "runtime match list|set", type: "Subcommand", description: "Read or override SDK-to-runtime build matching"),
                TKCommandSchemaOption(name: "runtime dyld-cache update|remove", type: "Subcommand", description: "Update or remove runtime dyld shared caches"),
                TKCommandSchemaOption(name: "personalization personalize|remove-manifest|remove-all-manifests|remove-personalization|revoke-manifests|scan-and-personalize", type: "Subcommand", description: "Manage simulator runtime personalization manifests"),
                TKCommandSchemaOption(name: "status-bar list", type: "Subcommand", description: "List simulator status bar overrides"),
                TKCommandSchemaOption(name: "status-bar clear", type: "Subcommand", description: "Clear simulator status bar overrides"),
                TKCommandSchemaOption(name: "status-bar override --time <value>", type: "Subcommand", description: "Set simulator status bar override values"),
                TKCommandSchemaOption(name: "privacy grant <service> <bundle-id>", type: "Subcommand", description: "Grant a simulator privacy permission"),
                TKCommandSchemaOption(name: "privacy revoke <service> <bundle-id>", type: "Subcommand", description: "Revoke a simulator privacy permission"),
                TKCommandSchemaOption(name: "privacy reset <service> [bundle-id]", type: "Subcommand", description: "Reset simulator privacy permissions"),
                TKCommandSchemaOption(name: "location list", type: "Subcommand", description: "List available simulated location scenarios"),
                TKCommandSchemaOption(name: "location clear", type: "Subcommand", description: "Clear simulated location"),
                TKCommandSchemaOption(name: "location set <lat>,<lon>", type: "Subcommand", description: "Set a simulated location coordinate"),
                TKCommandSchemaOption(name: "location run <scenario>", type: "Subcommand", description: "Run a simulated location scenario"),
                TKCommandSchemaOption(name: "location start <waypoints...>", type: "Subcommand", description: "Run a waypoint-based simulated route"),
                TKCommandSchemaOption(name: "ui appearance [light|dark]", type: "Subcommand", description: "Get or set the simulator appearance style"),
                TKCommandSchemaOption(name: "ui increase-contrast [enabled|disabled]", type: "Subcommand", description: "Get or set Increase Contrast"),
                TKCommandSchemaOption(name: "ui content-size [value]", type: "Subcommand", description: "Get or set the preferred content size category"),
                TKCommandSchemaOption(name: "pasteboard set <text>", type: "Subcommand", description: "Copy text onto the simulator pasteboard"),
                TKCommandSchemaOption(name: "pasteboard get", type: "Subcommand", description: "Read simulator pasteboard content"),
                TKCommandSchemaOption(name: "pasteboard sync <source> <destination>", type: "Subcommand", description: "Sync pasteboard content between host and simulator"),
                TKCommandSchemaOption(name: "push --bundle-id <id> --payload <path|->", type: "Subcommand", description: "Send a simulated push notification"),
                TKCommandSchemaOption(name: "media seed --manifest <path>", type: "Subcommand", description: "Add manifest-described media fixtures to a simulator photo library"),
                TKCommandSchemaOption(name: "--device", type: "String", defaultValue: "booted", description: "Simulator UDID or booted target selector for host AX commands"),
                TKCommandSchemaOption(name: "--simulator", type: "String", defaultValue: "booted", description: "Simulator UDID or booted target selector"),
                TKCommandSchemaOption(name: "--manifest", type: "Path", description: "Media seed manifest JSON path"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "ASCII text for host-side simulator type"),
                TKCommandSchemaOption(name: "--display", type: "String", description: "CoreSimulator display selector for screenshot or video, for example internal, external, screen id, or display UUID"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Artifact output path for screenshot, record, logs, or diagnose"),
                TKCommandSchemaOption(name: "--duration", type: "Double", description: "Bounded record or log capture duration in seconds"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "300", description: "Host command timeout in seconds"),
                TKCommandSchemaOption(name: "--no-archive", type: "Bool", defaultValue: "false", description: "Leave simulator diagnostics uncompressed"),
                TKCommandSchemaOption(name: "--all-logs", type: "Bool", defaultValue: "false", description: "Include all simulator logs"),
                TKCommandSchemaOption(name: "--data-container", type: "Bool", defaultValue: "false", description: "Include booted simulator data containers in diagnostics"),
                TKCommandSchemaOption(name: "--udid", type: "String", description: "Limit diagnostics to a simulator UDID; may be repeated"),
                TKCommandSchemaOption(name: "--style", type: "String", description: "Log output style, for example compact or ndjson"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "Bundle identifier for push payload delivery"),
                TKCommandSchemaOption(name: "--payload", type: "Path|-", description: "Push payload JSON file path or stdin"),
                TKCommandSchemaOption(name: "--mode", type: "record|mock|block|throttle", description: "Host-side proxy takeover mode for Simulator network capture or policy enforcement"),
                TKCommandSchemaOption(name: "--restore", type: "Bool", defaultValue: "false", description: "Restore simulator proxy settings when stopping a host-side proxy session"),
                TKCommandSchemaOption(name: "--plan-only", type: "Bool", defaultValue: "false", description: "Return proxy command or artifact plan without changing host settings"),
                TKCommandSchemaOption(name: "--proxy", type: "host:port", defaultValue: "127.0.0.1:19431", description: "Local proxy endpoint used by Simulator proxy start plans"),
                TKCommandSchemaOption(name: "--audit-record", type: "String", description: "Audit record id required with --confirm before break-glass Simulator proxy mutation can proceed"),
                TKCommandSchemaOption(name: "--execute-runner", type: "Bool", defaultValue: "false", description: "Required with --confirm and --audit-record before Simulator proxy mutation can call host tools"),
                TKCommandSchemaOption(name: "--session", type: "Path", description: "Proxy session directory produced by sim proxy start --output"),
                TKCommandSchemaOption(name: "--restore-snapshot", type: "Path", description: "Restore snapshot path produced by sim proxy start"),
                TKCommandSchemaOption(name: "--confirm", type: "Bool", defaultValue: "false", description: "Required for destructive simulator operations such as erase"),
                TKCommandSchemaOption(name: "--dry-run", type: "Bool", defaultValue: "false", description: "Plan destructive runtime maintenance without executing it"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            argumentForms: [
                TKCommandArgumentForm(name: "<name>", type: "String", required: true, description: "Simulator name for sim create"),
            ],
            examples: [
                "triton sim list --json",
                "triton sim use 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --json",
                "triton sim create 'Codex iPhone' --device-type com.apple.CoreSimulator.SimDeviceType.iPhone-16 --runtime com.apple.CoreSimulator.SimRuntime.iOS-26-0 --json",
                "triton sim boot 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --json",
                "triton sim boot 0333546D-2AC6-4C22-AF01-293E2F4BA5BC --wait --jsonl",
                "triton sim screenshot --simulator booted --output /tmp/sim.png --json",
                "triton sim type --simulator booted --text http://127.0.0.1:8000 --json",
                "triton sim record --simulator booted --output /tmp/sim.mov --duration 10 --json",
                "triton sim logs --simulator booted --output /tmp/sim.ndjson --duration 5 --style ndjson --json",
                "triton sim diagnose --output /tmp/sim-diagnostics --json",
                "triton sim logverbose booted enable --json",
                "triton sim proxy start --simulator booted --mode record --output /tmp/ios-network --plan-only --json",
                "triton sim proxy start --simulator booted --mode record --output /tmp/ios-network --confirm --audit-record ticket-123 --execute-runner --json",
                "triton sim proxy status --simulator booted --json",
                "triton sim proxy export --simulator booted --output /tmp/network.har --json",
                "triton sim proxy stop --simulator booted --restore --plan-only --json",
                "triton sim proxy stop --simulator booted --restore-snapshot /tmp/ios-network/restore-state.json --confirm --audit-record ticket-123 --execute-runner --json",
                "triton sim runtime list --json",
                "triton sim pair <watch-udid> <phone-udid> --json",
                "triton sim clone <udid> 'Clone for Smoke' --json",
                "triton sim erase <udid> --confirm --json",
                "triton sim runtime delete <runtime-id> --dry-run --json",
                "triton sim personalization scan-and-personalize --json",
                "triton sim media seed --manifest /tmp/gallery/manifest.json --simulator booted --json",
            ],
            successShape: "{ ok, simulators[] } or { ok, runtimes[], count, verbose, sourceCommand } or { ok, action, simulator?, defaultsPath? } or { ok, action:sim.screenshot, artifact, pixelWidth?, pixelHeight?, display, orientationPolicy, orientationNote } or { ok, action:sim.type, runtimeScope:host-simulator, target, adapter, tool, exitCode, sourceCommand, textEncoding?, note } or { ok, action, runtimeScope, target, tool, exitCode, sourceCommand, stdout?, stderr?, stdoutTruncated?, stderrTruncated?, artifacts[], note? } or { ok, action, artifact, stdoutBytes, stderrBytes, stdoutTruncated, stderrTruncated } or JSONL { ok, action, state, ready, attempt, elapsedMs }",
            failureShape: "{ ok:false, error:{ code, message, hint, nextAction? } }",
            outputSemantics: "Use sim for Apple Simulator host control and maintenance. Destructive operations require explicit confirm flags; agents should resolve/use a simulator before app or smoke flows. sim screenshot preserves simctl raw framebuffer orientation and returns screenshot metadata so agents do not assume display-normalized orientation. sim type remains a reserved host input entry and returns unsupported_host_input because the current public simctl io contract exposes no stable keyboard type primitive.",
            artifacts: ["simulator-screenshot", "simulator-video", "simulator-logs", "simulator-diagnostics"],
            nextCommands: [
                "triton sim use <udid> --json",
                "triton device use <sim-target-id> --json",
                "triton plan --json",
                "triton sim type --simulator <udid|booted> --text <text> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
                "triton app launch --device <selector> --bundle-id <id> --json",
                "triton smoke ios --device <selector> --bundle-id <id> --open-url <url> --wait-text <text> --json",
            ],
            outputContracts: [
                hostSimulatorListOutputContract(),
                hostSimulatorScreenshotOutputContract(),
                hostSimulatorAXOutputContract(),
                hostSimulatorInputOutputContract(),
                hostActionOutputContract(selector: "host.simulator-action", model: "HostActionOutput|HostArtifactCaptureOutput|HostSimulatorUseOutput|HostSimulatorCreateOutput|HostSimulatorReadyEvent"),
                hostSimulatorScreenshotMetadataOutputContract(),
                hostDeviceProxyOutputContract(),
                hostSimulatorMediaSeedOutputContract(),
            ],
            failureCodes: [
                "simulator_not_found",
                "host_command_failed",
                "host_command_timeout",
                "unsupported_host_input",
                "unsupported_text_input",
                "artifact_output_rejected",
                "sim_device_maintenance_failed",
                "status_bar_operation_failed",
                "privacy_operation_failed",
                "location_operation_failed",
                "ui_operation_failed",
                "pasteboard_operation_failed",
                "push_payload_invalid",
                "media_seed_manifest_invalid",
                "proxy_visibility_limited",
                "proxy_platform_not_supported",
                "proxy_endpoint_unreachable",
                "proxy_start_failed",
                "proxy_restore_failed",
                "sim_pair_failed",
                "sim_unpair_failed",
                "sim_clone_failed",
                "sim_erase_failed",
                "sim_upgrade_failed",
                "sim_record_failed",
                "sim_logs_failed",
                "sim_diagnose_failed",
                "sim_logverbose_failed",
                "ios_host_ax_unavailable",
                "ios_host_ax_frontmost_unavailable",
                "ios_host_ax_platform_element_unavailable",
                "ios_host_ax_tree_unavailable",
                "ios_host_ax_unsupported_platform",
                "sim_runtime_failed",
                "sim_personalization_failed",
                "runtime_list_failed",
                "runtime_verify_failed",
                "runtime_add_failed",
                "runtime_delete_failed",
                "runtime_unmount_failed",
                "runtime_scan_and_mount_failed",
                "runtime_match_failed",
                "runtime_dyld_cache_failed",
                "confirmation_required",
                "invalid_duration",
                "invalid_location_value",
                "runtime_delete_selector_required",
                "runtime_dyld_cache_selector_required",
                "runtime_match_selector_required",
                "validation_failed",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "list",
                    summary: "List available simulators",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-list"]
                ),
                TKCommandSubcommandSchema(
                    name: "use",
                    summary: "Set workspace default simulator",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "create",
                    summary: "Create a simulator",
                    requiredOptions: ["<name>", "--device-type", "--runtime"],
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"],
                    failureCodes: ["host_command_failed", "host_command_timeout", "validation_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "boot",
                    summary: "Boot a simulator",
                    optionalOptions: ["--wait", "--jsonl", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "shutdown",
                    summary: "Shutdown a simulator",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "screenshot",
                    summary: "Capture simulator framebuffer screenshot",
                    requiredOptions: ["--output"],
                    optionalOptions: ["--simulator", "--display", "--format", "--json"],
                    nextCommands: ["triton evidence capture --case <case> --output <dir.tritonevidence> --json"],
                    outputSelectors: ["host.simulator-screenshot"],
                    failureCodes: ["host_command_failed", "host_command_timeout", "simulator_not_found", "artifact_output_rejected", "validation_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "type",
                    summary: "Reserved host-side simulator text entry; currently unsupported by public simctl io after ASCII validation",
                    requiredOptions: ["--text"],
                    optionalOptions: ["--simulator", "--format", "--json"],
                    nextCommands: [
                        "triton plan --json",
                        "triton sim screenshot --simulator <udid|booted> --output <path> --json",
                        "triton verify text-exists <text> --json",
                    ],
                    outputSelectors: ["host.simulator-input"],
                    failureCodes: ["unsupported_host_input", "unsupported_text_input", "validation_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "record",
                    summary: "Record a bounded simulator video",
                    requiredOptions: ["--output"],
                    optionalOptions: ["--simulator", "--duration", "--display", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "logs",
                    summary: "Capture bounded simulator OSLog stream output",
                    requiredOptions: ["--output"],
                    optionalOptions: ["--simulator", "--duration", "--style", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "diagnose",
                    summary: "Collect simulator diagnostics and logs",
                    optionalOptions: ["--output", "--timeout", "--no-archive", "--all-logs", "--data-container", "--udid", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "logverbose",
                    summary: "Enable or disable verbose simulator logging",
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "ax",
                    summary: "Read host-side iOS Simulator Accessibility tree",
                    optionalOptions: ["--device", "--format", "--json"],
                    nextCommands: [
                        "triton sim list --json",
                        "triton sim screenshot --simulator <udid|booted> --output <path.png> --json",
                        "triton device doctor --platform ios --json",
                    ],
                    outputSelectors: ["host.simulator-ax"],
                    failureCodes: ["ios_host_ax_unavailable", "ios_host_ax_frontmost_unavailable", "ios_host_ax_platform_element_unavailable", "ios_host_ax_tree_unavailable", "ios_host_ax_unsupported_platform", "simulator_not_found"]
                ),
                TKCommandSubcommandSchema(
                    name: "proxy",
                    summary: "Run iOS Simulator host-side proxy takeover aliases",
                    optionalOptions: ["--simulator", "--mode", "--output", "--proxy", "--session", "--restore", "--restore-snapshot", "--plan-only", "--confirm", "--audit-record", "--execute-runner", "--format", "--json"],
                    outputSelectors: ["host.device-proxy"],
                    failureCodes: ["proxy_visibility_limited", "proxy_platform_not_supported", "proxy_endpoint_unreachable", "proxy_start_failed", "proxy_restore_failed", "validation_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "pair",
                    summary: "Create a watch and phone simulator pair",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "unpair",
                    summary: "Unpair a watch and phone simulator pair",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "clone",
                    summary: "Clone an existing simulator device",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "erase",
                    summary: "Erase simulator contents and settings",
                    optionalOptions: ["--confirm", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "upgrade",
                    summary: "Upgrade a simulator to a newer runtime",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "runtime",
                    summary: "Inspect and maintain installed simulator runtimes",
                    optionalOptions: ["--dry-run", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "personalization",
                    summary: "Manage simulator runtime personalization manifests",
                    optionalOptions: ["--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "status-bar",
                    summary: "Read or override the simulator status bar",
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "privacy",
                    summary: "Grant, revoke, or reset simulator privacy permissions",
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "location",
                    summary: "Control simulated location",
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "ui",
                    summary: "Read or set simulator UI appearance and accessibility settings",
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "pasteboard",
                    summary: "Read, write, or sync simulator pasteboard content",
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "push",
                    summary: "Send a simulated push notification",
                    requiredOptions: ["--bundle-id", "--payload"],
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "media",
                    summary: "Add manifest-described media fixtures to a simulator photo library",
                    requiredOptions: ["--manifest"],
                    optionalOptions: ["--simulator", "--format", "--json"],
                    outputSelectors: ["host.simulator-media-seed"],
                    failureCodes: ["media_seed_manifest_invalid", "host_command_failed", "host_command_timeout", "simulator_not_found", "validation_failed"]
                ),
            ],
            providedCapabilities: ["host-simulator", "ios-simulator-host-type", "ios-host-ax", "sim-video", "sim-logs", "sim-diagnostics", "sim-runtime", "sim-runtime-maintenance", "sim-device-maintenance", "sim-personalization", "sim-status-bar", "sim-privacy", "sim-location", "sim-ui", "sim-pasteboard", "sim-push", "sim-media-seed", "device-proxy-ios", "network-capture-export"]
        ),
        TKCommandSchema(
            name: "app",
            summary: "Control local simulator and emulator apps through host-side tools",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "host-simulator|host-android|host-harmony",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: [
                TKCommandSchemaOption(name: "list", type: "Subcommand", description: "List installed simulator apps"),
                TKCommandSchemaOption(name: "info --bundle-id <id>", type: "Subcommand", description: "Show installed app metadata"),
                TKCommandSchemaOption(name: "inspect --platform android --bundle <bundle-id>", type: "Subcommand", description: "Compatibility alias for Android package metadata inspection through adb dumpsys package"),
                TKCommandSchemaOption(name: "inspect --platform harmony --bundle <bundle>", type: "Subcommand", description: "Inspect a Harmony app with bm dump"),
                TKCommandSchemaOption(name: "install --app <path.app>", type: "Subcommand", description: "Install an .app bundle into the simulator"),
                TKCommandSchemaOption(name: "install --platform android --apk <path.apk>", type: "Subcommand", description: "Install an Android APK through adb install -r"),
                TKCommandSchemaOption(name: "install --platform harmony --hap <path.hap>|--app <signed.app>", type: "Subcommand", description: "Install a Harmony HAP through hdc install -r or signed .app archive through hdc install"),
                TKCommandSchemaOption(name: "install --device <selector> --scope real --app|--apk|--hap <path>", type: "Subcommand", description: "Real-device install contract placeholder; host action submission does not prove business readiness"),
                TKCommandSchemaOption(name: "uninstall --bundle-id <id> --confirm", type: "Subcommand", description: "Uninstall an app from the simulator"),
                TKCommandSchemaOption(name: "uninstall --platform android --package-name <package> --confirm", type: "Subcommand", description: "Uninstall an Android package through adb uninstall"),
                TKCommandSchemaOption(name: "uninstall --platform harmony --bundle-id <bundle> --confirm", type: "Subcommand", description: "Uninstall a Harmony app through hdc shell bm uninstall"),
                TKCommandSchemaOption(name: "uninstall --platform harmony --bundle <bundle> --confirm", type: "Subcommand", description: "Uninstall a Harmony app through hdc shell bm uninstall"),
                TKCommandSchemaOption(name: "launch --bundle-id <id>", type: "Subcommand", description: "Launch an installed simulator or real-device app"),
                TKCommandSchemaOption(name: "launch --platform android --package-name <package>", type: "Subcommand", description: "Launch an Android package; when --activity is omitted Triton resolves the default activity before adb am start"),
                TKCommandSchemaOption(name: "launch --platform harmony --bundle <bundle> --ability <ability>", type: "Subcommand", description: "Launch a Harmony app ability"),
                TKCommandSchemaOption(name: "launch --device <selector> --scope real --bundle-id|--package-name|--bundle <id>", type: "Subcommand", description: "Real-device launch contract placeholder; use wait/assert/evidence for business readiness"),
                TKCommandSchemaOption(name: "terminate --bundle-id <id>", type: "Subcommand", description: "Terminate a running simulator app"),
                TKCommandSchemaOption(name: "terminate --platform android --package-name <package>", type: "Subcommand", description: "Force-stop an Android package through adb shell am force-stop"),
                TKCommandSchemaOption(name: "terminate --platform harmony --bundle <bundle>", type: "Subcommand", description: "Force-stop a Harmony app"),
                TKCommandSchemaOption(name: "go <url>", type: "Subcommand", description: "Open an iOS URL, wait for embedded runtime readiness, and return a snapshot summary"),
                TKCommandSchemaOption(name: "open-url <url>", type: "Subcommand", description: "Submit a URL to the simulator"),
                TKCommandSchemaOption(name: "open-url --platform android <url>", type: "Subcommand", description: "Submit an Android VIEW intent through adb shell am start"),
                TKCommandSchemaOption(name: "open-url <url> --wait-ready --snapshot", type: "Subcommand", description: "Open a URL, wait for embedded runtime readiness, and return an app/route/AX snapshot summary"),
                TKCommandSchemaOption(name: "open-url --platform harmony --bundle <bundle> --ability <ability> <url>", type: "Subcommand", description: "Open a Harmony deep link through aa start -U"),
                TKCommandSchemaOption(name: "open-url <url> --device <selector> --scope real --bundle-id|--package-name|--bundle <id>", type: "Subcommand", description: "Real-device deep-link contract placeholder; host action submission is not business proof"),
                TKCommandSchemaOption(name: "container --bundle-id <id>", type: "Subcommand", description: "Print app container path"),
                TKCommandSchemaOption(name: "prefs dump --bundle-id <id>", type: "Subcommand", description: "Dump app preferences plist as JSON"),
                TKCommandSchemaOption(name: "prefs get <key> --bundle-id <id>", type: "Subcommand", description: "Read one app preference"),
                TKCommandSchemaOption(name: "prefs set <key> <json-value> --bundle-id <id>", type: "Subcommand", description: "Set one simulator app preference from a property-list compatible JSON value"),
                TKCommandSchemaOption(name: "prefs set <key> --type data --base64 <base64> --bundle-id <id>", type: "Subcommand", description: "Set one simulator app preference as plist Data from base64"),
                TKCommandSchemaOption(name: "prefs set <key> --type data --hex <hex> --bundle-id <id>", type: "Subcommand", description: "Set one simulator app preference as plist Data from defaults-style hex bytes"),
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony", description: "Host app platform filter; when omitted, install/launch/terminate/open-url infer the platform from the provided app identifiers"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Unified host target selector: alias, sim:<udid>, android:<serial>, harmony:<target>, raw id, booted, or current"),
                TKCommandSchemaOption(name: "--scope", type: "simulator|emulator|real|all", description: "Device scope filter for resolving host app targets"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "iOS app bundle identifier, or Harmony bundle name for uninstall"),
                TKCommandSchemaOption(name: "--package-name", type: "String", description: "Android package name for uninstall, launch, terminate, and open-url"),
                TKCommandSchemaOption(name: "--activity", type: "String", description: "Android activity name for explicit component launch"),
                TKCommandSchemaOption(name: "--bundle", type: "String", description: "Harmony bundle name for inspect, uninstall, launch, terminate, and open-url"),
                TKCommandSchemaOption(name: "--ability", type: "String", description: "Harmony ability name for launch and open-url"),
                TKCommandSchemaOption(name: "--env", type: "KEY=VALUE", description: "Repeatable iOS launch environment for app launch; values are passed as SIMCTL_CHILD_* on Simulator or DEVICECTL_CHILD_* on real devices and redacted in sourceCommand"),
                TKCommandSchemaOption(name: "--arg", type: "String", description: "Repeatable iOS Simulator app launch argument passed after the bundle identifier"),
                TKCommandSchemaOption(name: "--app", type: "Path", description: "Path to iOS .app bundle or Harmony signed .app archive for install"),
                TKCommandSchemaOption(name: "--apk", type: "Path", description: "Path to Android .apk package for install"),
                TKCommandSchemaOption(name: "--hap", type: "Path", description: "Path to Harmony .hap package for install"),
                TKCommandSchemaOption(name: "--user-only", type: "Bool", defaultValue: "false", description: "List only user-installed simulator apps"),
                TKCommandSchemaOption(name: "--confirm", type: "Bool", defaultValue: "false", description: "Required for destructive app operations such as uninstall"),
                TKCommandSchemaOption(name: "--kind", type: "String", defaultValue: "data", description: "Container kind to resolve, for example app, data, groups, or all"),
                TKCommandSchemaOption(name: "--type", type: "json|data", defaultValue: "json", description: "Preference set value type; data requires exactly one of --base64 or --hex"),
                TKCommandSchemaOption(name: "--base64", type: "String", description: "Base64 payload for prefs set --type data"),
                TKCommandSchemaOption(name: "--hex", type: "String", description: "Hex payload for prefs set --type data; optional 0x prefix and whitespace are accepted"),
                TKCommandSchemaOption(name: "--name", type: "String", description: "Device name filter, for example iPhone 15"),
                TKCommandSchemaOption(name: "--runtime", type: "String", description: "Runtime filter, for example iOS 26.5"),
                TKCommandSchemaOption(name: "--state", type: "String", description: "Target state filter, for example booted or connected"),
                TKCommandSchemaOption(name: "--ready", type: "Bool", defaultValue: "false", description: "Only match ready host targets"),
                TKCommandSchemaOption(name: "--simulator", type: "String", description: "Explicit iOS simulator selector; cannot be combined with --device"),
                TKCommandSchemaOption(name: "--runtime-target", type: "String", defaultValue: TKLocalTargetID, description: "iOS embedded runtime target for open-url readiness/snapshot verification"),
                TKCommandSchemaOption(name: "--wait-ready", type: "Bool", defaultValue: "false", description: "After open-url, wait until embedded runtime is connected with active hierarchy"),
                TKCommandSchemaOption(name: "--snapshot", type: "Bool", defaultValue: "false", description: "After open-url, return embedded runtime app/scene/route/AX/geometry snapshot summary"),
                TKCommandSchemaOption(name: "--snapshot-include", type: "String", defaultValue: "app,scene,route,ax,geometry", description: "Comma-separated snapshot sections"),
                TKCommandSchemaOption(name: "--max-ax-nodes", type: "Int", description: "Maximum AX nodes in the runtime snapshot"),
                TKCommandSchemaOption(name: "--host", type: "String", defaultValue: "127.0.0.1", description: "Triton server host for readiness/snapshot verification"),
                TKCommandSchemaOption(name: "--port", type: "Int", defaultValue: "19421", description: "Triton server port for readiness/snapshot verification"),
                TKCommandSchemaOption(name: "--timeout", type: "Double", defaultValue: "20", description: "Runtime readiness or host command timeout in seconds"),
                TKCommandSchemaOption(name: "--interval", type: "Double", defaultValue: "0.5", description: "Runtime readiness polling interval in seconds"),
                TKCommandSchemaOption(name: "--target", type: "String", description: "Compatibility Harmony target selector, for example 127.0.0.1:10100; cannot be combined with --device"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
            ],
            argumentForms: [
                TKCommandArgumentForm(name: "<url>", type: "String", required: true, description: "Deep link, universal link, or platform URL to open"),
                TKCommandArgumentForm(name: "<key>", type: "String", required: true, description: "Preference key for app prefs get/set"),
                TKCommandArgumentForm(name: "<json-value>", type: "JSON", required: true, description: "Property-list compatible JSON value for app prefs set"),
            ],
            examples: [
                "triton app list --device iphone15 --user-only --json",
                "triton app info --device iphone15 --bundle-id com.example.app --json",
                "triton app inspect --platform android --device android-a --bundle com.example.app --json",
                "triton app inspect --platform harmony --bundle com.example.app --json",
                "triton app install --device iphone15 --app /tmp/Demo.app --timeout 180 --json",
                "triton app install --device android-a --platform android --apk /tmp/Demo.apk --json",
                "triton app install --device harmony-a --hap /tmp/Demo.hap --json",
                "triton app install --platform harmony --device harmony-a --app /tmp/Signed.app --json",
                "triton app install --device <android-real-target> --platform android --scope real --apk /tmp/Demo.apk --json",
                "triton app info --device <ios-real-target> --platform ios --scope real --bundle-id com.example.app --json",
                "triton app list --device <android-real-target> --platform android --scope real --user-only --json",
                "triton app uninstall --device iphone15 --bundle-id com.example.app --confirm --json",
                "triton app uninstall --device android-a --platform android --package-name com.example.app --confirm --json",
                "triton app uninstall --platform harmony --target 127.0.0.1:10100 --bundle-id com.example.app --confirm --json",
                "triton app uninstall --platform harmony --device harmony-a --bundle com.example.app --confirm --json",
                "triton app launch --device iphone15 --bundle-id com.example.app --json",
                "triton app launch --device iphone15 --bundle-id com.example.app --env FEATURE_FLAG=1 --arg debug-route --arg demo.home --json",
                "triton app launch --platform ios --name 'iPhone 15' --bundle-id com.example.app --json",
                "triton app launch --bundle-id com.example.app --json",
                "triton app launch --device android-a --platform android --package-name com.example.app --json",
                "triton app launch --platform harmony --device harmony-a --bundle com.example.app --ability EntryAbility --json",
                "triton app launch --device <ios-real-target> --platform ios --scope real --bundle-id com.example.app --json",
                "triton app launch --platform harmony --bundle com.example.app --ability EntryAbility --json",
                "triton app open-url example://debug --device android-a --platform android --package-name com.example.app --json",
                "triton app open-url example://debug --device <android-real-target> --platform android --scope real --package-name com.example.app --json",
                "triton app open-url --platform harmony --device harmony-a --bundle com.example.app --ability EntryAbility example://debug --json",
                "triton app terminate --device iphone15 --bundle-id com.example.app --json",
                "triton app terminate --device android-a --platform android --package-name com.example.app --json",
                "triton app terminate --device <harmony-real-target> --platform harmony --scope real --bundle com.example.app --json",
                #"triton app go "example://debug""#,
                #"triton app go "example://debug" --device iphone15"#,
                #"triton app open-url "example://debug" --device iphone15 --json"#,
                #"triton app open-url "example://debug" --device iphone15 --wait-ready --snapshot --json"#,
                "triton app container --device iphone15 --bundle-id com.example.app --kind data --json",
                "triton app prefs get DEBUG-mock --device iphone15 --bundle-id com.example.app --json",
                #"triton app prefs set DEBUG-mock true --device iphone15 --bundle-id com.example.app --json"#,
                #"triton app prefs set SeedState --type data --base64 W3t9XQ== --device iphone15 --bundle-id com.example.app --json"#,
            ],
            successShape: "{ ok, action, simulatorUDID?, apps[]?, app?, bundleID?, path?, target?, sourceCommand? with launch env values redacted } or { ok, action, plistPath, value?, valuePlistType?, preferences?, preferencesPlistTypes? } or { ok, action:app.prefs.set, plistPath, key, previousValue?, previousPlistType?, newValue, newPlistType, restartAdvice } or enhanced open-url { ok, status, hostAction, ready?, snapshot? }",
            failureShape: "{ ok:false, error:{ code, message, hint, nextAction? } }",
            outputSemantics: "Use app for host-side install, launch, terminate, open-url, container, and preferences across iOS Simulator, Android Emulator, and Harmony Emulator. For iOS runtime readiness, prefer open-url with --wait-ready --snapshot; for Android host flows, verify business completion with wait/observe/screenshot or smoke evidence. If `triton camera on` enabled the launched iOS Simulator bundle, app launch injects the configured camera hook environment.",
            artifacts: ["app-container", "app-preferences", "runtime-snapshot"],
            nextCommands: [
                "triton app go <url>",
                "triton status --json",
                "triton verify text-exists <text> --json",
                "triton evidence capture --case <case> --output <dir.tritonevidence> --json",
            ],
            outputContracts: [
                hostActionOutputContract(selector: "host.app-action", model: "HostActionOutput|HostAppContainerOutput|HostAppPreferenceOutput"),
                hostAppInfoOutputContract(selector: "host.android-app-inspect"),
                hostActionOutputContract(selector: "host.android-app-install", model: "HostActionOutput"),
                hostActionOutputContract(selector: "host.android-app-launch", model: "HostActionOutput"),
                hostAppOpenURLOutputContract(),
            ],
            failureCodes: [
                "ambiguous_target",
                "target_not_found",
                "target_offline",
                "target_platform_mismatch",
                "parameter_conflict",
                "simulator_not_found",
                "unsupported_host_action",
                "device_not_ready",
                "device_locked",
                "debug_runtime_disabled",
                "runtime_not_connected",
                "devicectl_not_found",
                "device_not_trusted",
                "developer_mode_required",
                "ddi_missing",
                "xcode_signing_failed",
                "provisioning_profile_missing",
                "android_adb_not_found",
                "android_target_unauthorized",
                "android_target_offline",
                "android_debugging_disabled",
                "android_package_manager_unavailable",
                "android_app_install_failed",
                "android_activity_resolve_failed",
                "harmony_hdc_not_found",
                "harmony_target_unauthorized",
                "harmony_target_offline",
                "harmony_debugging_disabled",
                "harmony_shell_unavailable",
                "harmony_app_install_failed",
                "harmony_ability_launch_failed",
                "app_info_not_available",
                "app_container_not_found",
                "app_install_failed",
                "app_launch_failed",
                "app_terminate_failed",
                "host_open_url_failed",
                "host_command_timeout",
                "host_action_failed",
                "missing_preferences",
                "plist_not_found",
                "preference_key_not_found",
                "destructive_action_requires_policy",
                "validation_failed",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "list",
                    summary: "List installed simulator, emulator, or real-device apps",
                    optionalOptions: ["--platform", "--device", "--scope", "--simulator", "--name", "--runtime", "--state", "--ready", "--user-only", "--format", "--json"],
                    outputSelectors: ["host.app-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "info",
                    summary: "Show installed app metadata",
                    oneOfRequiredOptions: [["--bundle-id"], ["--package-name"], ["--bundle"]],
                    optionalOptions: ["--platform", "--device", "--scope", "--simulator", "--name", "--runtime", "--state", "--ready", "--format", "--json"],
                    outputSelectors: ["host.android-app-inspect"]
                ),
                TKCommandSubcommandSchema(
                    name: "inspect",
                    summary: "Inspect Android or Harmony app metadata",
                    oneOfRequiredOptions: [["--package-name"], ["--bundle"]],
                    optionalOptions: ["--platform", "--device", "--scope", "--target", "--hdc", "--format", "--json"],
                    outputSelectors: ["host.android-app-inspect"]
                ),
                TKCommandSubcommandSchema(
                    name: "install",
                    summary: "Install an iOS .app, Android APK, or Harmony HAP",
                    oneOfRequiredOptions: [["--app"], ["--apk"], ["--hap"]],
                    optionalOptions: ["--platform", "--device", "--scope", "--simulator", "--name", "--runtime", "--state", "--ready", "--timeout", "--format", "--json"],
                    outputSelectors: ["host.app-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "uninstall",
                    summary: "Uninstall an app after explicit confirmation",
                    oneOfRequiredOptions: [["--bundle-id"], ["--package-name"], ["--bundle"]],
                    optionalOptions: ["--platform", "--device", "--scope", "--simulator", "--name", "--runtime", "--state", "--ready", "--target", "--hdc", "--confirm", "--format", "--json"],
                    outputSelectors: ["host.app-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "launch",
                    summary: "Launch an installed app",
                    oneOfRequiredOptions: [["--bundle-id"], ["--package-name"], ["--bundle"]],
                    optionalOptions: ["--platform", "--device", "--scope", "--simulator", "--name", "--runtime", "--state", "--ready", "--activity", "--ability", "--env", "--arg", "--format", "--json"],
                    outputSelectors: ["host.app-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "terminate",
                    summary: "Terminate a running app",
                    oneOfRequiredOptions: [["--bundle-id"], ["--package-name"], ["--bundle"]],
                    optionalOptions: ["--platform", "--device", "--scope", "--simulator", "--format", "--json"],
                    outputSelectors: ["host.app-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "go",
                    summary: "Open an iOS URL, wait for runtime readiness, and return a snapshot",
                    requiredOptions: ["<url>"],
                    optionalOptions: ["--device", "--scope", "--simulator", "--name", "--runtime", "--state", "--ready", "--runtime-target", "--snapshot-include", "--max-ax-nodes", "--host", "--port", "--timeout", "--interval", "--format", "--json"],
                    outputSelectors: ["host.app-open-url"]
                ),
                TKCommandSubcommandSchema(
                    name: "open-url",
                    summary: "Submit a URL through host-side app tooling",
                    requiredOptions: ["<url>"],
                    optionalOptions: ["--platform", "--device", "--scope", "--simulator", "--name", "--runtime", "--state", "--ready", "--bundle-id", "--package-name", "--bundle", "--ability", "--target", "--hdc", "--runtime-target", "--wait-ready", "--snapshot", "--snapshot-include", "--max-ax-nodes", "--host", "--port", "--timeout", "--interval", "--format", "--json"],
                    outputSelectors: ["host.app-open-url"]
                ),
                TKCommandSubcommandSchema(
                    name: "container",
                    summary: "Print an app container path",
                    requiredOptions: ["--bundle-id"],
                    optionalOptions: ["--device", "--scope", "--simulator", "--kind", "--format", "--json"],
                    outputSelectors: ["host.app-action"]
                ),
                TKCommandSubcommandSchema(
                    name: "prefs",
                    summary: "Dump, read, or set simulator app preferences",
                    requiredOptions: ["--bundle-id"],
                    optionalOptions: ["<key>", "<json-value>", "--device", "--scope", "--simulator", "--type", "--base64", "--hex", "--format", "--json"],
                    outputSelectors: ["host.app-action"]
                ),
            ],
            providedCapabilities: ["host-app", "host-app-open-url-ready", "host-app-open-url-snapshot", "host-preferences", "ios-real-app", "android-app", "android-app-inspect", "android-app-install", "android-app-launch", "android-app-terminate", "android-app-open-url", "harmony-app", "harmony-app-install", "harmony-app-open-url", "harmony-app-info"]
        ),
    ]
}
