import Foundation
import TritonKitShared

func testRecorderCommandSchemas() -> [TKCommandSchema] {
    [
        TKCommandSchema(
            name: "testrec",
            summary: "Record, inspect, compile, and diagnose .tritontestcase semantic replay contracts",
            requiresServer: false,
            requiresTarget: false,
            requiresHierarchy: false,
            runtimeScope: "offline explicit-event recording, inspect, compile, proposals, page fingerprint match, replay diagnostics, and replay matrix diagnostics; never a real test executor",
            exitCodeOnFailure: 1,
            outputFormats: ["json", "text"],
            options: [
                TKCommandSchemaOption(name: "start --platform <platform> --case <name> --output <case.tritontestcase>", type: "Subcommand", description: "Start an explicit-event recording session and initialize a .tritontestcase package"),
                TKCommandSchemaOption(name: "event --session <session-id> --kind <kind> --payload-json <json>", type: "Subcommand", description: "Append one explicit JSON event to an active recording session"),
                TKCommandSchemaOption(name: "stop --session <session-id>", type: "Subcommand", description: "Stop an explicit-event recording session and summarize artifacts"),
                TKCommandSchemaOption(name: "inspect <case.tritontestcase>", type: "Subcommand", description: "Inspect a .tritontestcase directory package"),
                TKCommandSchemaOption(name: "compile <case.tritontestcase>", type: "Subcommand", description: "Run deterministic offline compile preflight for a .tritontestcase package"),
                TKCommandSchemaOption(name: "proposals <case.tritontestcase>", type: "Subcommand", description: "Read compile-proposals.jsonl without applying changes"),
                TKCommandSchemaOption(name: "match-page <case.tritontestcase> --page <page> --candidate-json <json>", type: "Subcommand", description: "Score a target-side page fingerprint against a compiled page contract"),
                TKCommandSchemaOption(name: "replay <case.tritontestcase>", type: "Subcommand", description: "Plan replay from a .tritontestcase package, or run an offline local-simulated diagnostic"),
                TKCommandSchemaOption(name: "matrix <case.tritontestcase> --targets <targets>", type: "Subcommand", description: "Build a multi-target dry-run or local-simulated diagnostic matrix"),
                TKCommandSchemaOption(name: "--case", type: "String", description: "Recorded test case name for testrec start"),
                TKCommandSchemaOption(name: "--session", type: "String", description: "Session id returned by testrec start"),
                TKCommandSchemaOption(name: "--kind", type: "String", description: "Explicit event kind for testrec event"),
                TKCommandSchemaOption(name: "--payload-json", type: "JSON", description: "Single event JSON object for testrec event"),
                TKCommandSchemaOption(name: "--candidate-json", type: "JSON", description: "Target-side page fingerprint JSON object for match-page"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Output .tritontestcase path for start, or optional compiled contract path for compile"),
                TKCommandSchemaOption(name: "--page", type: "String", description: "Compiled page selector for match-page; accepts pageId, route, or fingerprint index"),
                TKCommandSchemaOption(name: "--platform", type: "String", description: "Source platform for start or target replay platform for dry-run planning"),
                TKCommandSchemaOption(name: "--device", type: "String", description: "Optional target device selector"),
                TKCommandSchemaOption(name: "--dry-run", type: "Bool", defaultValue: "false", description: "Build an offline replay diagnostic plan without execution"),
                TKCommandSchemaOption(name: "--executor", type: "String", description: "Replay diagnostic executor; local-simulated never produces a real test verdict"),
                TKCommandSchemaOption(name: "--evidence-dir", type: "Path", description: "Optional .tritonevidence output directory for local-simulated diagnostics"),
                TKCommandSchemaOption(name: "--evidence-root", type: "Path", description: "Optional root directory for per-target local-simulated diagnostic evidence bundles"),
                TKCommandSchemaOption(name: "--target-fingerprints-json", type: "JSON", description: "Optional target-side page fingerprint object, array, or {pages:[...]} for local-simulated diagnostics"),
                TKCommandSchemaOption(name: "--targets", type: "String", description: "Comma-separated matrix targets, using platform or platform:device"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                schemaJSONAliasOption,
            ],
            usageForms: [
                TKCommandUsageForm(form: "start --platform <platform> --case <name> --output <case.tritontestcase> --json", kind: "Subcommand", description: "Initialize a .tritontestcase package and return a local recording session id"),
                TKCommandUsageForm(form: "event --session <session-id> --kind action --payload-json <json> --json", kind: "Subcommand", description: "Append one explicit action event to actions.jsonl"),
                TKCommandUsageForm(form: "stop --session <session-id> --json", kind: "Subcommand", description: "Stop a recording session and emit artifact presence"),
                TKCommandUsageForm(form: "inspect <case.tritontestcase> --json", kind: "Subcommand", description: "Validate manifest.json and contract-capabilities.json, then emit a machine-readable contract summary"),
                TKCommandUsageForm(form: "compile <case.tritontestcase> --json", kind: "Subcommand", description: "Summarize raw streams and write compiled-contract.json when deterministic inputs are complete"),
                TKCommandUsageForm(form: "proposals <case.tritontestcase> --json", kind: "Subcommand", description: "Read compile proposals without applying them to the compiled contract"),
                TKCommandUsageForm(form: "match-page <case.tritontestcase> --page <page> --candidate-json <json> --json", kind: "Subcommand", description: "Score a target-side page fingerprint using the compiled deterministic match policy"),
                TKCommandUsageForm(form: "replay <case.tritontestcase> --platform <platform> --dry-run --json", kind: "Subcommand", description: "Build an offline diagnostic plan from compiled-contract.json without executing device actions"),
                TKCommandUsageForm(form: "replay <case.tritontestcase> --platform <platform> --executor local-simulated --target-fingerprints-json <json> --evidence-dir <dir.tritonevidence> --json", kind: "Subcommand", description: "Run the compiled contract through the offline local-simulated diagnostic, score target page fingerprints, and write a non-verdict .tritonevidence bundle"),
                TKCommandUsageForm(form: "matrix <case.tritontestcase> --targets ios:sim-a,android:emu-a --json", kind: "Subcommand", description: "Fan out the compiled contract into per-target offline diagnostic plans without executing device actions"),
                TKCommandUsageForm(form: "matrix <case.tritontestcase> --targets ios:sim-a,android:emu-a --executor local-simulated --evidence-root <dir> --json", kind: "Subcommand", description: "Run the offline local-simulated diagnostic matrix and write one non-verdict evidence bundle per target"),
            ],
            argumentForms: [
                TKCommandArgumentForm(name: "<case.tritontestcase>", type: "Path", required: true, description: "Input or output .tritontestcase directory package"),
            ],
            examples: [
                "triton testrec start --platform ios --case login --output ./login.tritontestcase --json",
                "triton testrec event --session testrec-123 --kind action --payload-json '{\"kind\":\"tap\",\"target\":{\"label\":\"登录\"}}' --json",
                "triton testrec stop --session testrec-123 --json",
                "triton testrec inspect ./login.tritontestcase --json",
                "triton testrec compile ./login.tritontestcase --json",
                "triton testrec proposals ./login.tritontestcase --json",
                #"triton testrec match-page ./login.tritontestcase --page login --candidate-json '{"route":"login","hash":"abc"}' --json"#,
                "triton testrec replay ./login.tritontestcase --platform android --dry-run --json",
                #"triton testrec replay ./login.tritontestcase --platform android --executor local-simulated --target-fingerprints-json '{"pages":[{"pageId":"login","route":"login","hash":"abc"}]}' --evidence-dir ./login.tritonevidence --json"#,
            ],
            successShape: "TKTestRecorderSessionStartResponse, TKTestRecorderEventResponse, TKTestRecorderSessionStopResponse, TKTestRecorderInspectResponse, TKTestRecorderCompileResponse, TKTestRecorderProposalsResponse, TKTestRecorderFingerprintMatchResponse, TKTestRecorderReplayDryRunResponse, TKTestRecorderReplayRunResponse, or TKTestRecorderMatrixResponse with manifest, contract capabilities, artifact presence, proposals, page match evidence, warnings/blockers, planned steps/results, additive verdictBoundary, and suggested next commands.",
            failureShape: "{ ok:false, error:{ type:\"validation_error\", message, path, code, hint? } }",
            outputSemantics: "testrec start/event/stop provide an explicit-event source recording MVP without global input listeners. inspect, compile, proposals, match-page, replay dry-run, local-simulated replay, and replay matrix are offline-only diagnostics. Inspect verifies the .tritontestcase directory package has manifest.json and contract-capabilities.json, reports unsupported action/page/network capabilities without treating them as pass, and does not execute device actions. Compile performs deterministic preflight over optional raw streams, writes compiled-contract.json when inputs are complete, and does not call LLM/VLM. match-page scores a target-side VLM-style page fingerprint with deterministic evidence and no LLM decision authority. Replay with --dry-run emits a plan/blockers; replay with --executor local-simulated consumes that plan and returns diagnostic replay-result evidence without executing device commands. Matrix fans out the same diagnostic contracts across multiple platform:device targets without introducing a real device executor. replay/matrix ready, passed, and passedCount remain compatibility fields only: every new replay/matrix output carries verdictBoundary.classification=offline-diagnostic, countsAsRealTestVerdict=false, and eligibleForReliabilityGate=false. Agents that need a real verdict must use verdictBoundary.migrationCommands: triton test import, then triton test validate, then triton test run on an explicit target.",
            artifacts: [
                "tritontestcase",
                "contract-capabilities",
                "compiled-contract",
                "action-map",
                "page-map",
                "network-map",
                "network-fixture",
                "compile-proposals",
                "evidence-bundle",
            ],
            nextCommands: [
                "triton testrec start --platform <platform> --case <name> --output <case.tritontestcase> --json",
                "triton testrec event --session <session-id> --kind action --payload-json <json> --json",
                "triton testrec stop --session <session-id> --json",
                "triton testrec inspect <case.tritontestcase> --json",
                "triton testrec compile <case.tritontestcase> --json",
                "triton testrec proposals <case.tritontestcase> --json",
                "triton testrec match-page <case.tritontestcase> --page <page> --candidate-json <json> --json",
                "triton testrec replay <case.tritontestcase> --platform <platform> --dry-run --json",
                "triton testrec replay <case.tritontestcase> --platform <platform> --executor local-simulated --target-fingerprints-json <json> --evidence-dir <dir.tritonevidence> --json",
                "triton testrec matrix <case.tritontestcase> --targets ios:sim-a,android:emu-a --json",
                "triton test import <case.tritontestcase> --output <path.tritontest.yaml> --bundle-id <bundle-id> --device-platform ios-simulator --json",
            ],
            outputContracts: [
                testRecorderSessionStartOutputContract(),
                testRecorderEventOutputContract(),
                testRecorderSessionStopOutputContract(),
                testRecorderInspectOutputContract(),
                testRecorderCompileOutputContract(),
                testRecorderProposalsOutputContract(),
                testRecorderPageMatchOutputContract(),
                testRecorderReplayDryRunOutputContract(),
                testRecorderReplayRunOutputContract(),
                testRecorderMatrixOutputContract(),
            ],
            failureCodes: [
                "validation_failed",
                "missing_required_file",
                "invalid_json",
                "invalid_case_directory",
                "unsupported_schema_version",
                "dry_run_required",
                "unsupported_replay_executor",
                "target_not_found",
                "target_capability_missing",
                "missing_matrix_targets",
                "invalid_matrix_target",
                "invalid_session_id",
                "session_not_found",
                "session_not_recording",
                "unsupported_event_kind",
                "missing_compiled_contract",
                "source_fingerprint_not_found",
            ],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "start",
                    summary: "Start an explicit-event .tritontestcase recording session",
                    requiredOptions: ["--platform", "--case", "--output"],
                    optionalOptions: ["--format", "--json"],
                    artifacts: ["tritontestcase", "contract-capabilities"],
                    nextCommands: [
                        "triton testrec event --session <session-id> --kind action --payload-json <json> --json",
                        "triton testrec stop --session <session-id> --json",
                    ],
                    outputSelectors: ["testrec.session-start"],
                    failureCodes: [
                        "validation_failed",
                        "invalid_json",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "event",
                    summary: "Append an explicit JSON event to a testrec recording session",
                    requiredOptions: ["--session", "--kind", "--payload-json"],
                    optionalOptions: ["--format", "--json"],
                    artifacts: ["tritontestcase"],
                    nextCommands: [
                        "triton testrec stop --session <session-id> --json",
                        "triton testrec inspect <case.tritontestcase> --json",
                    ],
                    outputSelectors: ["testrec.event"],
                    failureCodes: [
                        "validation_failed",
                        "invalid_json",
                        "invalid_session_id",
                        "session_not_found",
                        "session_not_recording",
                        "unsupported_event_kind",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "stop",
                    summary: "Stop an explicit-event testrec recording session",
                    requiredOptions: ["--session"],
                    optionalOptions: ["--format", "--json"],
                    artifacts: ["tritontestcase"],
                    nextCommands: [
                        "triton testrec inspect <case.tritontestcase> --json",
                        "triton testrec compile <case.tritontestcase> --json",
                    ],
                    outputSelectors: ["testrec.session-stop"],
                    failureCodes: [
                        "validation_failed",
                        "invalid_json",
                        "invalid_session_id",
                        "session_not_found",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "inspect",
                    summary: "Inspect a .tritontestcase directory package",
                    requiredOptions: ["<case.tritontestcase>"],
                    optionalOptions: ["--format", "--json"],
                    nextCommands: [
                        "triton schema --command testrec --json",
                    ],
                    outputSelectors: ["testrec.inspect"],
                    failureCodes: [
                        "validation_failed",
                        "missing_required_file",
                        "invalid_json",
                        "invalid_case_directory",
                        "unsupported_schema_version",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "compile",
                    summary: "Compile-preflight a .tritontestcase directory package",
                    requiredOptions: ["<case.tritontestcase>"],
                    optionalOptions: ["--output", "--format", "--json"],
                    artifacts: ["compiled-contract", "action-map", "page-map", "network-map", "network-fixture", "compile-proposals"],
                    nextCommands: [
                        "triton testrec inspect <case.tritontestcase> --json",
                    ],
                    outputSelectors: ["testrec.compile"],
                    failureCodes: [
                        "validation_failed",
                        "missing_required_file",
                        "invalid_json",
                        "invalid_case_directory",
                        "unsupported_schema_version",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "proposals",
                    summary: "Read compile proposals for a .tritontestcase package",
                    requiredOptions: ["<case.tritontestcase>"],
                    optionalOptions: ["--format", "--json"],
                    nextCommands: [
                        "triton testrec inspect <case.tritontestcase> --json",
                    ],
                    outputSelectors: ["testrec.proposals"],
                    failureCodes: [
                        "validation_failed",
                        "missing_required_file",
                        "invalid_json",
                        "invalid_case_directory",
                        "unsupported_schema_version",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "match-page",
                    summary: "Score a target-side page fingerprint against compiled page evidence",
                    requiredOptions: ["<case.tritontestcase>", "--page", "--candidate-json"],
                    optionalOptions: ["--format", "--json"],
                    nextCommands: [
                        "triton testrec compile <case.tritontestcase> --json",
                    ],
                    outputSelectors: ["testrec.page-match"],
                    failureCodes: [
                        "validation_failed",
                        "missing_required_file",
                        "invalid_json",
                        "invalid_case_directory",
                        "unsupported_schema_version",
                        "missing_compiled_contract",
                        "source_fingerprint_not_found",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "matrix",
                    summary: "Build a multi-target offline diagnostic matrix for a .tritontestcase",
                    requiredOptions: ["<case.tritontestcase>", "--targets"],
                    optionalOptions: ["--executor", "--evidence-root", "--target-fingerprints-json", "--format", "--json"],
                    nextCommands: [
                        "triton testrec compile <case.tritontestcase> --json",
                        "triton test import <case.tritontestcase> --output <path.tritontest.yaml> --bundle-id <bundle-id> --device-platform ios-simulator --json",
                    ],
                    outputSelectors: ["testrec.matrix"],
                    failureCodes: [
                        "validation_failed",
                        "missing_required_file",
                        "invalid_json",
                        "invalid_case_directory",
                        "unsupported_schema_version",
                        "missing_matrix_targets",
                        "invalid_matrix_target",
                        "unsupported_replay_executor",
                    ]
                ),
                TKCommandSubcommandSchema(
                    name: "replay",
                    summary: "Plan or run an offline diagnostic for a .tritontestcase replay",
                    requiredOptions: ["<case.tritontestcase>", "--platform"],
                    optionalOptions: ["--dry-run", "--executor", "--target-fingerprints-json", "--evidence-dir", "--device", "--format", "--json"],
                    artifacts: ["evidence-bundle"],
                    nextCommands: [
                        "triton testrec compile <case.tritontestcase> --json",
                        "triton evidence summary <dir.tritonevidence> --json",
                        "triton test import <case.tritontestcase> --output <path.tritontest.yaml> --bundle-id <bundle-id> --device-platform ios-simulator --json",
                    ],
                    outputSelectors: ["testrec.replay-dry-run", "testrec.replay-result"],
                    failureCodes: [
                        "validation_failed",
                        "missing_required_file",
                        "invalid_json",
                        "invalid_case_directory",
                        "unsupported_schema_version",
                        "dry_run_required",
                        "unsupported_replay_executor",
                        "target_not_found",
                        "target_capability_missing",
                    ]
                ),
            ],
            providedCapabilities: [
                "testrec-session-start",
                "testrec-event-ingest",
                "testrec-session-stop",
                "testrec-inspect",
                "testrec-compile",
                "testrec-proposals-inspect",
                "testrec-page-match",
                "testrec-replay-dry-run",
                "testrec-replay-local-simulated",
                "testrec-matrix",
            ]
        ),
    ]
}
