import Foundation
import TritonKitShared

func runtimeCommandSchemas() -> [TKCommandSchema] {
    let hostPort = schemaHostPortOptions
    let target = schemaTargetOption
    let jsonText = schemaTextJSONFormats
    let jsonAlias = schemaJSONAliasOption
    let languageOption = schemaLanguageOption
    let runtimeBaseURLOption = schemaRuntimeBaseURLOption
    let runtimeTargetFailureCodes = schemaRuntimeTargetFailureCodes
    let semanticActionFailureCodes = schemaSemanticActionFailureCodes

    return [
        TKCommandSchema(
            name: "runtime",
            summary: "Inspect embedded runtime manifest, capabilities, limits, and redaction policy",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "manifest", type: "Subcommand", description: "Read embedded runtime manifest"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: ["triton runtime manifest --json", "triton runtime manifest --runtime-base-url \(TKHarmonyRuntimeDefaults.hostAccessBaseURL) --json"],
            successShape: "{ ok, platform, runtime, transport, enabled, sdkVersion, buildConfiguration, capabilities[], limits, redaction }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|request_failed|runtime_unavailable, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use runtime manifest to inspect embedded DEBUG runtime boundaries, supported capabilities, limits, and redaction policy before choosing state, snapshot, WebView, or action commands.",
            nextCommands: [
                "triton capabilities --format json",
                "triton state app --json",
                "triton snapshot --json",
            ],
            outputContracts: [runtimeManifestOutputContract()],
            failureCodes: runtimeTargetFailureCodes,
            providedCapabilities: ["runtime-manifest"]
        ),
        TKCommandSchema(
            name: "state",
            summary: "Read embedded app, scene, route, and responder state",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "app", type: "Subcommand", description: "Read app identity, locale, display style, uptime, scene/window counts"),
                TKCommandSchemaOption(name: "scene", type: "Subcommand", description: "Read UIWindowScene and UIWindow summaries"),
                TKCommandSchemaOption(name: "route", type: "Subcommand", description: "Read visible UIViewController, navigation, tab, and presented stack"),
                TKCommandSchemaOption(name: "responder", type: "Subcommand", description: "Read first responder identity and text input traits without text content"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: [
                "triton state app --json",
                "triton state scene --json",
                "triton state route --json",
                "triton state responder --json",
            ],
            successShape: "{ ok, capturedAt, runtime, targetConnectionState, app|scenes|route|firstResponder, warnings[], unsupported[] }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|request_failed|runtime_unavailable, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use state for structured app, scene, route, and responder diagnostics when a full snapshot would be too broad.",
            nextCommands: [
                "triton status --json",
                "triton snapshot --json",
                "triton observe current --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [runtimeStateOutputContract()],
            failureCodes: runtimeTargetFailureCodes,
            providedCapabilities: ["state-app", "state-scene", "state-route", "state-responder"]
        ),
        TKCommandSchema(
            name: "snapshot",
            summary: "Read one aggregated embedded runtime snapshot for agent decisions",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: hostPort + [
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--include", type: "CSV", defaultValue: "app,scene,route,ax,geometry", description: "Sections: app,scene,route,responder,ax,geometry,screenshot-metadata"),
                TKCommandSchemaOption(name: "--max-ax-nodes", type: "Int", description: "Maximum AX nodes to return before truncation"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: ["triton snapshot --include app,scene,route,ax,geometry --json"],
            successShape: "{ ok, capturedAt, include, app?, scene?, route?, responder?, geometry?, ax?, screenshot?, artifacts[], skipped[], truncation }",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|request_failed|runtime_unavailable|validation_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use snapshot as the primary aggregated runtime observation before assertions or recovery decisions; sections may be skipped or truncated but stay machine-readable.",
            artifacts: ["runtime-snapshot"],
            nextCommands: [
                "triton status --json",
                "triton assert text-exists <text> --json",
                "triton wait --text <text> --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [runtimeSnapshotOutputContract()],
            failureCodes: runtimeTargetFailureCodes,
            providedCapabilities: ["snapshot"]
        ),
        TKCommandSchema(
            name: "focus",
            summary: "Resolve a selector and focus the matching text input through the embedded runtime",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "<selector>", type: "String", description: "Text, label, identifier, or visible placeholder to focus"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one matching candidate by 1-based index"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict selector matching to bounds"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Restrict selector matching to a candidate containing this point"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: ["triton focus \"名称\" --json", "triton focus \"Email\" --within 0,120,390,220 --json"],
            successShape: "{ ok, action, strategy, targetOID?, targetClassName?, elapsedMs, message?, redaction? }",
            failureShape: "{ ok:false, action, strategy, error:{ code: target_not_found|ambiguous_target|validation_failed|semantic_action_failed, message, hint, nextAction? } }",
            outputSemantics: "Use focus for field activation after resolving ambiguity with find/node/geometry. Inspect ledger after failures to see runtime-side action diagnostics.",
            nextCommands: [
                "triton status --json",
                "triton find <selector> --all --json",
                "triton wait --text <selector> --json",
                "triton ledger --limit 20 --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [semanticActionOutputContract()],
            failureCodes: semanticActionFailureCodes,
            providedCapabilities: ["focus", "semantic-action"]
        ),
        TKCommandSchema(
            name: "set-text",
            summary: "Resolve a selector, clear editable text, and set exact text through the embedded runtime",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "<selector>", type: "String", description: "Text, label, identifier, or visible placeholder to target"),
                TKCommandSchemaOption(name: "<text>", type: "String", description: "Exact text to set"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--secure", type: "Bool", defaultValue: "false", description: "Redact text in command output and ledger"),
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one matching candidate by 1-based index"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict selector matching to bounds"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Restrict selector matching to a candidate containing this point"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: ["triton set-text \"名称\" \"alice\" --json", "triton set-text \"密码\" \"secret\" --secure --json"],
            successShape: "{ ok, action, strategy, targetOID?, targetClassName?, elapsedMs, message?, redaction: { secure, text, insertedLength? } }",
            failureShape: "{ ok:false, action, strategy, error:{ code: target_not_found|ambiguous_target|validation_failed|semantic_action_failed, message, hint, nextAction? } }",
            outputSemantics: "Use set-text for exact editable-field mutation. Pass --secure for private text so command output and ledger keep only length/redaction metadata.",
            nextCommands: [
                "triton status --json",
                "triton find <selector> --all --json",
                "triton ledger --limit 20 --json",
                "triton assert text-exists <text> --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [semanticActionOutputContract()],
            failureCodes: semanticActionFailureCodes,
            providedCapabilities: ["set-text", "semantic-action"]
        ),
        TKCommandSchema(
            name: "select-segment",
            summary: "Resolve a selector and select a segmented-control option by title or zero-based index",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "<selector>", type: "String", description: "Text, label, identifier, or visible option title to target"),
                TKCommandSchemaOption(name: "<value>", type: "String|Int", description: "Segment title or zero-based index"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one matching candidate by 1-based index"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict selector matching to bounds"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Restrict selector matching to a candidate containing this point"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: ["triton select-segment \"协议\" \"HTTP\" --json", "triton select-segment \"协议\" 1 --json"],
            successShape: "{ ok, action, strategy, targetOID?, targetClassName?, elapsedMs, message?, redaction? }",
            failureShape: "{ ok:false, action, strategy, error:{ code: target_not_found|ambiguous_target|validation_failed|semantic_action_failed, message, hint, nextAction? } }",
            outputSemantics: "Use select-segment for segmented controls when raw tap is ambiguous; resolve candidate and inspect ledger/evidence on failure.",
            nextCommands: [
                "triton status --json",
                "triton find <selector> --all --json",
                "triton wait --text <selector> --json",
                "triton ledger --limit 20 --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [semanticActionOutputContract()],
            failureCodes: semanticActionFailureCodes,
            providedCapabilities: ["select-segment", "semantic-action"]
        ),
        TKCommandSchema(
            name: "set-switch",
            summary: "Resolve a selector and set or toggle a switch through the embedded runtime",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText,
            options: hostPort + [
                TKCommandSchemaOption(name: "<selector>", type: "String", description: "Text, label, identifier, or visible option title to target"),
                TKCommandSchemaOption(name: "<value>", type: "on|off|toggle", description: "Switch state to apply"),
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one matching candidate by 1-based index"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict selector matching to bounds"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Restrict selector matching to a candidate containing this point"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: ["triton set-switch \"记住我\" on --json", "triton set-switch \"Notifications\" toggle --json"],
            successShape: "{ ok, action, strategy, targetOID?, targetClassName?, elapsedMs, message?, redaction? }",
            failureShape: "{ ok:false, action, strategy, error:{ code: target_not_found|ambiguous_target|validation_failed|semantic_action_failed, message, hint, nextAction? } }",
            outputSemantics: "Use set-switch for explicit on/off/toggle state changes; follow with assertion or snapshot when a visible state change is required.",
            nextCommands: [
                "triton status --json",
                "triton find <selector> --all --json",
                "triton wait --text <selector> --json",
                "triton ledger --limit 20 --json",
                "triton snapshot --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [semanticActionOutputContract()],
            failureCodes: semanticActionFailureCodes,
            providedCapabilities: ["set-switch", "semantic-action"]
        ),
        TKCommandSchema(
            name: "ledger",
            summary: "Read recent embedded runtime request/action ledger",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            exitCodeOnFailure: 1,
            outputFormats: jsonText + ["jsonl"],
            options: hostPort + [
                target,
                runtimeBaseURLOption,
                TKCommandSchemaOption(name: "--limit", type: "Int", defaultValue: "50", description: "Maximum entries to return"),
                TKCommandSchemaOption(name: "--jsonl", type: "Bool", defaultValue: "false", description: "Emit JSON Lines entries instead of envelope"),
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                languageOption,
            ],
            examples: ["triton ledger --limit 50 --jsonl", "triton ledger --limit 50 --json"],
            successShape: "{ ok, entries[], limit, count, maxEntries } or JSONL TKRuntimeLedgerEntry",
            failureShape: "{ ok:false, error:{ code: server_unavailable|target_unavailable|runtime_unavailable|validation_failed, message, endpoint, hint, nextAction? } }",
            outputSemantics: "Use ledger after semantic actions or runtime failures to inspect recent request/action outcomes. Use --jsonl for append-friendly audit streams.",
            artifacts: ["runtime-ledger"],
            nextCommands: [
                "triton evidence --output <dir.tritonevidence> --json",
                "triton snapshot --json",
                "triton status --json",
            ],
            outputContracts: [runtimeLedgerOutputContract(), runtimeLedgerEntryOutputContract()],
            failureCodes: runtimeTargetFailureCodes,
            providedCapabilities: ["ledger"]
        ),
    ]
}
