import Foundation
import TritonKitShared

func workspaceCommandSchemas() -> [TKCommandSchema] {
    [
        TKCommandSchema(
            name: "workspace",
            summary: "Create and inspect local agent workspace runs",
            requiresServer: false,
            requiresTarget: false,
            runtimeScope: "local workspace",
            outputFormats: ["json", "text"],
            options: [
                TKCommandSchemaOption(name: "run", type: "Subcommand", description: "Create .triton/runs/<run-id> with the first workspace facts"),
                TKCommandSchemaOption(name: "inspect <run-id>", type: "Subcommand", description: "Read run.json and events.jsonl"),
                TKCommandSchemaOption(name: "stop <run-id>", type: "Subcommand", description: "Append run.stopped if the run is not already stopped"),
                TKCommandSchemaOption(name: "export-flow <run-id>", type: "Subcommand", description: "Write a .tritonflow.yaml seed from run facts"),
                TKCommandSchemaOption(name: "--target", type: "String", defaultValue: "current", description: "Target selector recorded in the run"),
                TKCommandSchemaOption(name: "--platform", type: "ios|android|harmony|unknown", defaultValue: "unknown", description: "Target platform fact recorded in run target metadata"),
                TKCommandSchemaOption(name: "--scope", type: "simulator|emulator|real|current", defaultValue: "current", description: "Target scope fact recorded in run target metadata"),
                TKCommandSchemaOption(name: "--app", type: "String", description: "App artifact, bundle id, package name, or app id"),
                TKCommandSchemaOption(name: "--goal", type: "String", description: "Natural-language run goal"),
                TKCommandSchemaOption(name: "--runs-dir", type: "Path", defaultValue: ".triton/runs", description: "Workspace run root"),
                TKCommandSchemaOption(name: "--run-id", type: "String", description: "Optional stable run id"),
                TKCommandSchemaOption(name: "--action-policy", type: "explore|planFirst", defaultValue: "explore", description: "Runner action policy recorded in config.yaml"),
                TKCommandSchemaOption(name: "--app-mode", type: "dry|attach|launch", defaultValue: "dry", description: "App lifecycle mode. launch submits triton app launch through the host app adapter before initial observation"),
                TKCommandSchemaOption(name: "--bundle-id", type: "String", description: "iOS bundle identifier for --app-mode launch; defaults to --app for iOS targets"),
                TKCommandSchemaOption(name: "--package-name", type: "String", description: "Android package name for --app-mode launch; defaults to --app for Android targets"),
                TKCommandSchemaOption(name: "--activity", type: "String", description: "Android activity for explicit component launch"),
                TKCommandSchemaOption(name: "--bundle", type: "String", description: "Harmony bundle name for --app-mode launch; defaults to --app for Harmony targets"),
                TKCommandSchemaOption(name: "--ability", type: "String", description: "Harmony ability name for --app-mode launch"),
                TKCommandSchemaOption(name: "--adb", type: "Path", defaultValue: "adb", description: "Path to adb executable for Android app launch"),
                TKCommandSchemaOption(name: "--max-steps", type: "Int", defaultValue: "20", description: "Maximum bounded runner steps before max_steps_reached"),
                TKCommandSchemaOption(name: "--allowed-action", type: "String[]", defaultValue: "tap,swipe,type,wait,verify,stop", description: "Allowed runner action; repeat to override the default action allowlist"),
                TKCommandSchemaOption(name: "--stop-condition", type: "String[]", defaultValue: "max_steps_reached,provider_missing,unsupported_capability,policy_rejected,model_unparseable", description: "Runner stop condition; repeat to override the default stop set"),
                TKCommandSchemaOption(name: "--observation-fixture", type: "Path", description: "Optional workspace observation fixture or triton observe JSON used to seed observation.captured and Atlas screen evidence"),
                TKCommandSchemaOption(name: "--observe-live", type: "Bool", defaultValue: "false", description: "Capture initial observation through triton observe instead of placeholder evidence"),
                TKCommandSchemaOption(name: "--observe-kind", type: "current|tree", defaultValue: "tree", description: "Live observation command kind used with --observe-live"),
                TKCommandSchemaOption(name: "--observe-max-nodes", type: "Int", description: "Maximum nodes to request from live observation"),
                TKCommandSchemaOption(name: "--observe-output", type: "Path", description: "Optional host layout artifact path for live observation"),
                TKCommandSchemaOption(name: "--runtime-base-url", type: "URL", description: "Direct embedded runtime base URL for live observation"),
                TKCommandSchemaOption(name: "--observe-host", type: "String", defaultValue: "127.0.0.1", description: "Embedded runtime host for live observation"),
                TKCommandSchemaOption(name: "--observe-port", type: "Int", defaultValue: "19421", description: "Embedded runtime port for live observation"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "Path to hdc executable for Harmony live observation"),
                TKCommandSchemaOption(name: "--business-ready-text", type: "String", description: "Exact visible text from initial observation that proves the business checkpoint ready"),
                TKCommandSchemaOption(name: "--business-ready-live-wait", type: "Bool", defaultValue: "false", description: "Use runtime wait text matching instead of initial-observation-only matching for the business checkpoint"),
                TKCommandSchemaOption(name: "--business-ready-timeout", type: "Double", defaultValue: "10", description: "Timeout in seconds for --business-ready-live-wait"),
                TKCommandSchemaOption(name: "--business-ready-interval", type: "Double", defaultValue: "0.5", description: "Polling interval in seconds for --business-ready-live-wait"),
                TKCommandSchemaOption(name: "--llm-provider", type: "String", description: "Optional LLM provider id to preflight for workspace bootstrap"),
                TKCommandSchemaOption(name: "--vlm-provider", type: "String", description: "Optional VLM provider id to preflight for workspace bootstrap"),
                TKCommandSchemaOption(name: "--dry-model-fixture", type: "Bool", defaultValue: "false", description: "Append dry model/policy/action/recovery events without calling a model or device"),
                TKCommandSchemaOption(name: "--output", type: "Path", description: "Output .tritonflow.yaml path for export-flow"),
                schemaFormatJSONTextOption,
                schemaJSONAliasOption,
            ],
            usageForms: [
                TKCommandUsageForm(form: "run --target current --app <app> --goal <goal> --json", kind: "Subcommand", description: "Create a local workspace run facts directory"),
                TKCommandUsageForm(form: "inspect <run-id> --json", kind: "Subcommand", description: "Read run status and event summary"),
                TKCommandUsageForm(form: "stop <run-id> --json", kind: "Subcommand", description: "Stop a run idempotently"),
                TKCommandUsageForm(form: "export-flow <run-id> --output <file.tritonflow.yaml> --json", kind: "Subcommand", description: "Export a flow seed from run facts"),
            ],
            argumentForms: [
                TKCommandArgumentForm(name: "<run-id>", type: "String", required: true, description: "Workspace run id under --runs-dir"),
            ],
            examples: [
                #"triton workspace run --target current --app com.example.demo --goal "Explore login" --json"#,
                #"triton workspace run --target booted --platform ios --scope simulator --app com.example.demo --app-mode launch --bundle-id com.example.demo --observe-live --json"#,
                #"triton workspace run --target booted --platform ios --scope simulator --app com.example.demo --goal "Open login" --observe-live --business-ready-text Continue --json"#,
                #"triton workspace run --target booted --platform ios --scope simulator --app com.example.demo --goal "Open dashboard" --business-ready-text Dashboard --business-ready-live-wait --json"#,
                "triton workspace inspect run_123 --json",
                "triton workspace stop run_123 --json",
                "triton workspace export-flow run_123 --output flow.tritonflow.yaml --json",
            ],
            successShape: "run emits triton.workspace.run; inspect/stop emit triton.workspace.inspect; export-flow emits triton.workspace.export-flow",
            outputSemantics: "workspace run is the local Run entry. It writes .triton/runs/<run-id>/run.json, config.yaml, events.jsonl, report.json, evidence placeholders, workspace observation fixture evidence, or live/fixture triton observe output evidence, atlas/atlas.json, runner bounds, default llm/vlm enabled state, provider preflight nextActions, policy rejection nextActions, flow.bootstrap.checked, and model loop events when mock providers are ready or dry-model fixture is enabled. With --app-mode launch, workspace run submits triton app launch through the host app adapter first and writes evidence/actions/app-ready.json with launch_submitted and businessReady=false. When --observe-live succeeds in the same run after launch, app.ready phase upgrades to launch_observed, ready=true, observedAfterLifecycle=true, and observationRef=events.jsonl#observation.captured while businessReady remains false. The run still requires wait/verify/action evidence before claiming the business flow is ready. With --business-ready-text, workspace run verifies exact visible text from the initial observation, writes evidence/business/ready.json, emits business.ready plus verify.checked, and returns run.status=passed only when that checkpoint is matched. With --business-ready-live-wait, workspace run requires --business-ready-text, calls runtime wait(text), writes evidence/business/ready.json with check=runtime_wait, source=runtime.wait, phase=wait_matched|wait_timeout|wait_unmatched and nested wait evidence, emits business.ready plus verify.checked, and returns run.status=passed only when the wait result is ok. With --observe-live, workspace run calls triton observe current/tree, saves raw ObserveOutput to evidence/observations/0000.json, and derives observation.captured plus Atlas seed from that evidence. workspace inspect returns run status, event summary, latest bootstrap, latest bootstrap proposal, latest pause, and Atlas coverage summary. It does not claim a real model decision until real providers and target execution are wired.",
            jsonlEvents: [
                "run.started",
                "target.resolved",
                "provider.checked",
                "app.ready",
                "observation.captured",
                "flow.bootstrap.checked",
                "model.decided",
                "policy.checked",
                "action.executed",
                "verify.checked",
                "business.ready",
                "flow.recovery.detected",
                "flow.recovery.proposed",
                "flow.recovery.rejected",
                "atlas.updated",
                "flow.updated",
                "run.paused",
                "run.stopped",
                "run.finished",
            ],
            finalEventKind: "run.paused|run.stopped|run.finished",
            artifacts: [
                ".triton/runs/<run-id>/run.json",
                ".triton/runs/<run-id>/config.yaml",
                ".triton/runs/<run-id>/events.jsonl",
                ".triton/runs/<run-id>/report.json",
                ".triton/runs/<run-id>/atlas/atlas.json",
                ".triton/runs/<run-id>/evidence/business/ready.json",
            ],
            failureCodes: ["workspace_failed"],
            subcommands: [
                TKCommandSubcommandSchema(
                    name: "run",
                    summary: "Create a local workspace run facts directory",
                    requiredOptions: ["--app", "--goal"],
                    optionalOptions: ["--target", "--platform", "--scope", "--runs-dir", "--run-id", "--action-policy", "--app-mode", "--bundle-id", "--package-name", "--activity", "--bundle", "--ability", "--adb", "--max-steps", "--allowed-action", "--stop-condition", "--observation-fixture", "--observe-live", "--observe-kind", "--observe-max-nodes", "--observe-output", "--runtime-base-url", "--observe-host", "--observe-port", "--hdc", "--business-ready-text", "--business-ready-live-wait", "--business-ready-timeout", "--business-ready-interval", "--llm-provider", "--vlm-provider", "--dry-model-fixture", "--format", "--json"],
                    jsonlEvents: ["run.started", "target.resolved", "provider.checked", "app.ready", "observation.captured", "flow.bootstrap.checked", "business.ready", "model.decided", "policy.checked", "action.executed", "verify.checked", "flow.recovery.detected", "flow.recovery.proposed", "flow.recovery.rejected", "atlas.updated", "flow.updated", "run.paused", "run.stopped", "run.finished"],
                    finalEventKind: "run.paused|run.stopped|run.finished",
                    artifacts: ["run.json", "config.yaml", "events.jsonl", "report.json", "atlas/atlas.json", "evidence/business/ready.json"],
                    outputSelectors: ["workspace.run"],
                    failureCodes: ["workspace_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "inspect",
                    summary: "Read a local workspace run",
                    requiredOptions: ["<run-id>"],
                    optionalOptions: ["--runs-dir", "--format", "--json"],
                    outputSelectors: ["workspace.inspect"],
                    failureCodes: ["workspace_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "stop",
                    summary: "Stop a local workspace run idempotently",
                    requiredOptions: ["<run-id>"],
                    optionalOptions: ["--runs-dir", "--format", "--json"],
                    outputSelectors: ["workspace.inspect"],
                    failureCodes: ["workspace_failed"]
                ),
                TKCommandSubcommandSchema(
                    name: "export-flow",
                    summary: "Export a .tritonflow.yaml seed from a local workspace run",
                    requiredOptions: ["<run-id>", "--output"],
                    optionalOptions: ["--runs-dir", "--format", "--json"],
                    outputSelectors: ["workspace.export-flow"],
                    failureCodes: ["workspace_failed"]
                ),
            ]
        ),
    ]
}
