import Foundation
import TritonKitShared

func actionCommandSchemas() -> [TKCommandSchema] {
    let hostPort = schemaHostPortOptions
    let target = schemaTargetOption
    let jsonText = schemaTextJSONFormats
    let formatJSONText = schemaFormatJSONTextOption
    let jsonAlias = schemaJSONAliasOption
    let inputCommandFailureCodes = schemaInputCommandFailureCodes

    return [
        TKCommandSchema(
            name: "tap",
            summary: "Tap a UI target by text, coordinate, view oid, or AX node",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "harmony", description: "Tap by Harmony layout text or coordinates through hdc uitest"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<query>", type: "String", description: "Visible text, AX label, identifier, value, or option title to tap"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Coordinate selector without <query>, or query disambiguation point with <query>"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Target view oid"),
                TKCommandSchemaOption(name: "--ax-oid", type: "UInt", description: "AX target/view oid from `triton ax`; taps by runtime oid"),
                TKCommandSchemaOption(name: "--ax-label", type: "String", description: "Exact AX label from `triton ax`; taps by runtime oid"),
                TKCommandSchemaOption(name: "--strategy", type: "smart|exact|ancestor", description: "Choose query or AX text activation target: query defaults to smart; AX selectors default to exact"),
                TKCommandSchemaOption(name: "--index", type: "Int", description: "Select one query candidate by 1-based index from `triton find --all`"),
                TKCommandSchemaOption(name: "--within", type: "x,y,width,height", description: "Restrict query matching to window bounds"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                #"triton tap "HTTP""#,
                #"triton tap "我的" --platform harmony --json"#,
                #"triton tap "hello" --index 2"#,
                #"triton tap "hello" --at 240,580"#,
                #"triton tap "hello" --strategy exact"#,
                #"triton tap "hello" --within 180,0,220,500"#,
                "triton tap --at 270,300",
                "triton tap --x 270 --y 300",
                "triton tap --oid 13",
                "triton tap --ax-label Save",
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName, matchedOID?, matchedClassName?, activationOID?, activationClassName?, strategy? } or HostHarmonyTapOutput",
            outputSemantics: "Use tap after find when targets are ambiguous. Follow successful taps with wait/assert and capture evidence on failure.",
            nextCommands: [
                "triton status --json",
                "triton wait --text <text> --json",
                "triton assert text-exists <text> --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostHarmonyTapOutputContract()],
            failureCodes: ["text_not_found", "validation_failed", "unsupported_capability", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed"],
            providedCapabilities: ["tap", "harmony-tap-text"]
        ),
        TKCommandSchema(
            name: "swipe",
            summary: "Swipe inside the app using window-point coordinates",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "harmony", description: "Swipe by Harmony screen coordinates through hdc uitest"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--start-x", type: "Double", required: true, description: "Start x coordinate in window points"),
                TKCommandSchemaOption(name: "--start-y", type: "Double", required: true, description: "Start y coordinate in window points"),
                TKCommandSchemaOption(name: "--end-x", type: "Double", required: true, description: "End x coordinate in window points"),
                TKCommandSchemaOption(name: "--end-y", type: "Double", required: true, description: "End y coordinate in window points"),
                TKCommandSchemaOption(name: "--width", type: "Double", description: "Optional screen/window width in points"),
                TKCommandSchemaOption(name: "--height", type: "Double", description: "Optional screen/window height in points"),
                TKCommandSchemaOption(name: "--duration", type: "Double", description: "Gesture duration in seconds"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                "triton swipe --start-x 350 --start-y 390 --end-x 100 --end-y 390",
                "triton swipe --platform harmony --target 127.0.0.1:10100 --start-x 350 --start-y 900 --end-x 350 --end-y 300 --json",
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName } or HostHarmonySwipeOutput",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostHarmonySwipeOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["swipe", "harmony-swipe"]
        ),
        TKCommandSchema(
            name: "type",
            summary: "Type text into a focused or oid-targeted UIKeyInput",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "harmony", description: "Type into the focused Harmony field through hdc uitest"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<text>", type: "String", description: "Text to insert"),
                TKCommandSchemaOption(name: "--text", type: "String", description: "Compatibility input; mutually exclusive with <text>"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Optional responder oid from `triton nodes`"),
                TKCommandSchemaOption(name: "--secure", type: "Bool", defaultValue: "false", description: "Redact inserted text details in command output"),
                TKCommandSchemaOption(name: "--exact", type: "Bool", defaultValue: "false", description: "Use direct UIKeyInput insertion without keyboard autocorrect"),
                formatJSONText,
                jsonAlias,
            ],
            examples: ["triton type hello --exact", "triton type --text hello", "triton type --platform harmony hello --json"],
            successShape: "{ ok, action, message, targetOID, targetClassName, secure?, redacted?, insertedLength? } or HostHarmonyTextInputOutput",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostHarmonyTextInputOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["type", "harmony-type-text"]
        ),
        TKCommandSchema(
            name: "paste",
            summary: "Paste exact text into a focused, coordinate-targeted, or oid-targeted input",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "harmony", description: "Insert text into Harmony focused field or coordinate through hdc uitest"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<text>", type: "String", required: true, description: "Text to paste"),
                TKCommandSchemaOption(name: "--secure", type: "Bool", defaultValue: "false", description: "Redact inserted text details in command output"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Optional responder oid"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate to focus before paste"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate to focus before paste"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Window point to focus before paste"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                #"triton paste "console""#,
                #"triton paste --secure "aa123654""#,
                #"triton paste "console" --at 180,250"#,
                #"triton paste --x 180 --y 250 "console""#,
                #"triton paste --platform harmony --at 180,250 "console" --json"#,
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName, secure, redacted, insertedLength } or HostHarmonyTextInputOutput",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostHarmonyTextInputOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["paste", "harmony-paste-text"]
        ),
        TKCommandSchema(
            name: "clear",
            summary: "Clear a focused, coordinate-targeted, or oid-targeted input",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "harmony", description: "Return explicit unsupported until a stable Harmony clear primitive or provider exists"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "--oid", type: "UInt", description: "Optional responder oid"),
                TKCommandSchemaOption(name: "--x", type: "Double", description: "Window x coordinate to focus before clear"),
                TKCommandSchemaOption(name: "--y", type: "Double", description: "Window y coordinate to focus before clear"),
                TKCommandSchemaOption(name: "--at", type: "x,y", description: "Window point to focus before clear"),
                formatJSONText,
                jsonAlias,
            ],
            examples: [
                "triton clear",
                "triton clear --at 180,250",
                "triton clear --x 180 --y 250",
            ],
            successShape: "{ ok, action, message, targetOID, targetClassName, insertedLength: 0 }",
            failureShape: "Harmony host path returns { ok:false, error:{ code:'unsupported_capability', message, hint } }",
            nextCommands: [
                "triton status --json",
                "triton ax --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract()],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["clear", "harmony-clear-text"]
        ),
        TKCommandSchema(
            name: "press",
            summary: "Press a device button when supported by the active runtime",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded|host-harmony",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--platform", type: "harmony", description: "Press Home/Back/Power or a raw keyID through hdc uitest keyEvent"),
                TKCommandSchemaOption(name: "--hdc", type: "Path", defaultValue: "hdc", description: "HDC executable path for --platform harmony"),
                TKCommandSchemaOption(name: "<button>", type: "String", description: "Button name, for example home"),
                TKCommandSchemaOption(name: "--button", type: "String", description: "Compatibility input; mutually exclusive with <button>"),
                TKCommandSchemaOption(name: "--duration", type: "Double", description: "Hold duration in seconds"),
                formatJSONText,
                jsonAlias,
            ],
            examples: ["triton press home", "triton press --button home", "triton press back --platform harmony --json"],
            successShape: "{ ok: false, action, message } in embedded runtime; HostActionOutput for Harmony keyEvent",
            failureShape: "{ ok:false, error:{ code: unsupported_capability|validation_failed|server_unavailable|target_not_found|ambiguous_target|request_failed, message, endpoint?, hint, nextAction? } }",
            nextCommands: [
                "triton status --json",
                "triton schema --command press --json",
                "triton evidence --output <dir.tritonevidence> --json",
            ],
            outputContracts: [inputResultOutputContract(), hostActionOutputContract(selector: "host.harmony-key-action", model: "HostActionOutput")],
            failureCodes: inputCommandFailureCodes,
            providedCapabilities: ["press", "harmony-press-key"]
        ),
        TKCommandSchema(
            name: "input",
            summary: "Run newline-delimited JSON actions from stdin",
            requiresServer: true,
            requiresTarget: true,
            runtimeScope: "embedded",
            outputFormats: jsonText,
            options: hostPort + [
                target,
                TKCommandSchemaOption(name: "--format", type: "text|json", defaultValue: "json", description: "Output format"),
                jsonAlias,
                TKCommandSchemaOption(name: "--fail-fast", type: "Bool", defaultValue: "false", description: "Stop on first failed action"),
                TKCommandSchemaOption(name: "--summary", type: "Bool", defaultValue: "false", description: "Print a final JSON batch summary"),
                TKCommandSchemaOption(name: "--strict", type: "Bool", defaultValue: "false", description: "Exit non-zero when any action fails"),
            ],
            examples: [
                #"printf '%s\n' '{"type":"tap","x":270,"y":300}' '{"type":"type","text":"hello"}' | triton input --format json --summary --strict"#,
            ],
            successShape: "One TKInputResult JSON object per input line; with --summary, final { ok, actionCount, failedCount }",
            outputSemantics: "Use input for batched low-level actions. Prefer --summary --strict when an agent needs a single completion gate for a batch.",
            nextCommands: [
                "triton status --json",
                "triton evidence --output <dir.tritonevidence> --json",
                "triton wait --text <text> --json",
                "triton assert text-exists <text> --json",
            ],
            outputContracts: [inputResultOutputContract(), inputSummaryOutputContract()],
            failureCodes: ["validation_failed", "server_unavailable", "target_not_found", "ambiguous_target", "request_failed", "action_failed"],
            inputActions: inputActionSchemas(),
            providedCapabilities: ["input", "tap", "swipe", "type", "paste", "clear"]
        ),
    ]
}
